#!/bin/sh
# Freeze the reviewed fn transport into one private, self-contained operator
# helper. The generated helper checks its remote executable closure on every
# invocation and does not consult FN_B3_IMAGE or fault-injection variables.
set -eu

if [ "$#" -ne 9 ]; then
  echo "usage: $0 NEW_HELPER FN_IMAGE IMAGE_SHA CORE_SHA RUNTIME_SHA OPENSSL_PREFIX OPENSSL_SHA LIBCRYPTO_SHA LIBSSL_SHA" >&2
  exit 64
fi

output=$1
image=$2
image_sha=$3
core_sha=$4
runtime_sha=$5
openssl=$6
openssl_sha=$7
crypto_sha=$8
ssl_sha=$9
runtime=${image%/fn-host}/runtime/sbcl
here=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
source_bridge=$here/fn_bridge.sh
source_sha=01eecf764899e659ae140b5d3896883a663bd64d25d97c1ef0d8988645bb976a

case "$output" in /*) ;; *) echo "helper output must be absolute" >&2; exit 64;; esac
case "$image" in /tank/fn/gates/*/build/images/*/fn-host) ;; *) echo "image must be a qualified hbox fn-host" >&2; exit 64;; esac
case "$openssl" in /tank/fn/toolchains/openssl-*) ;; *) echo "OpenSSL must be an hbox toolchain" >&2; exit 64;; esac
for path in "$image" "$openssl"; do
  case "$path" in *[!A-Za-z0-9_./-]*|'') echo "unsafe remote path" >&2; exit 64;; esac
done
for digest in "$image_sha" "$core_sha" "$runtime_sha" "$openssl_sha" "$crypto_sha" "$ssl_sha"; do
  case "$digest" in *[!0-9a-f]*|'') echo "digest must be lowercase hex" >&2; exit 64;; esac
  [ "${#digest}" -eq 64 ] || { echo "digest must be SHA-256" >&2; exit 64; }
done
[ ! -e "$output" ] || { echo "refusing to replace helper: $output" >&2; exit 64; }
parent=$(dirname -- "$output")
[ -d "$parent" ] || { echo "helper parent is absent" >&2; exit 64; }
case "$(uname -s)" in
  Darwin) parent_mode=$(stat -f %Lp "$parent") ;;
  Linux) parent_mode=$(stat -c %a "$parent") ;;
  *) echo "unsupported operator platform" >&2; exit 64 ;;
esac
[ "$parent_mode" = 700 ] || {
  echo "helper parent must be owner-private mode 0700" >&2
  exit 64
}
if command -v sha256sum >/dev/null 2>&1; then
  actual_source_sha=$(sha256sum "$source_bridge" | awk '{print $1}')
else
  actual_source_sha=$(shasum -a 256 "$source_bridge" | awk '{print $1}')
fi
[ "$actual_source_sha" = "$source_sha" ] || {
  echo "reviewed fn bridge source changed; update renderer after review" >&2
  exit 70
}

# Client-side expansion is intentional: each path was constrained above.
# shellcheck disable=SC2029
remote_hashes=$(ssh hbox "sha256sum $image $image.core $runtime $openssl/bin/openssl $openssl/lib/libcrypto.so.3 $openssl/lib/libssl.so.3") || {
  echo "cannot inspect remote fn executable closure" >&2
  exit 70
}
expected_hashes=$(printf '%s  %s\n%s  %s\n%s  %s\n%s  %s\n%s  %s\n%s  %s' \
  "$image_sha" "$image" "$core_sha" "$image.core" \
  "$runtime_sha" "$runtime" \
  "$openssl_sha" "$openssl/bin/openssl" \
  "$crypto_sha" "$openssl/lib/libcrypto.so.3" \
  "$ssl_sha" "$openssl/lib/libssl.so.3")
[ "$remote_hashes" = "$expected_hashes" ] || {
  echo "remote fn image/core/runtime/OpenSSL bytes differ from operator pins" >&2
  exit 70
}

umask 077
temporary=$(mktemp "$output.tmp.XXXXXX")
cleanup() { rm -f -- "$temporary"; }
trap cleanup EXIT
cat >"$temporary" <<EOF
#!/bin/sh
# Generated by render-operator-bridge.sh from fn_bridge.sh SHA-256 $source_sha.
# Qualified fn image: $image_sha; core: $core_sha; runtime: $runtime_sha.
# OpenSSL executable: $openssl_sha; libcrypto: $crypto_sha; libssl: $ssl_sha.
# The source bridge intentionally expands vetted paths on the client before ssh.
# shellcheck disable=SC2029
set -eu
PATH=/usr/bin:/bin
export PATH
remote_hashes=\$(ssh hbox 'sha256sum $image $image.core $runtime $openssl/bin/openssl $openssl/lib/libcrypto.so.3 $openssl/lib/libssl.so.3') || exit 70
expected_hashes='$(printf '%s\n' "$expected_hashes")'
[ "\$remote_hashes" = "\$expected_hashes" ] || {
  echo 'operator fn executable closure changed' >&2
  exit 70
}
EOF
awk -v image="$image" -v openssl="$openssl" '
  NR <= 2 { next }
  /^[ ]*if \[ "\$\{FN_E1E2_DROP_(POST|ACK)_REPLY:-0\}" = 1 \]; then$/ {
    skipping = 1; removed++; next
  }
  skipping && /^[ ]*fi$/ { skipping = 0; next }
  skipping { next }
  /^image=\$\{FN_B3_IMAGE:/ {
    print "image=\047" image "\047"; replaced++; next
  }
  {
    gsub("/tank/fn/toolchains/openssl-3.5.8", openssl)
    print
  }
  END {
    if (skipping || removed != 2 || replaced != 1) exit 70
  }
' "$source_bridge" >>"$temporary" || {
  echo "reviewed bridge shape changed; refusing generated helper" >&2
  exit 70
}
if grep -E 'FN_B3_IMAGE|FN_E1E2_DROP_' "$temporary" >/dev/null; then
  echo "generated helper retained an ambient fn/test hook" >&2
  exit 70
fi
sh -n "$temporary"
chmod 700 "$temporary"
ln "$temporary" "$output"
rm -f -- "$temporary"
trap - EXIT
printf 'operator bridge=%s\nsource-sha256=%s\n' "$output" "$source_sha"
