/-
# Compiler — the arithmetization spine (ATLAS §7).
-/
import Compiler.Placeholder  -- carve marker: syntactic-leaf IR, fold_unique, seqDescr, descriptor + codec
import Compiler.Signature    -- N3: abstract signatures, Term (= WType), fold_unique, agree_by_initiality, the syntactic-leaves-forced obligation
import Compiler.Air  -- the arithmetization DSL (derived): circuit⟺executor by initiality (N3), the first gadget; [AIR-poseidon]/[AIR-membership] the rungs toward a note-spend
import Compiler.AirFlatten  -- [AIR-flatten] CLOSED: nested expressions → degree-≤2 gate systems with aux wires, the flatten a fold; wire-forcing refinement (sound+complete+unique) → gate system ⟺ executor
import Compiler.DialectBundle  -- typed heterogeneous ports/fingerprints and an assurance meet that prevents native/floor/unclosed artifacts from masquerading as proof-verified receipts
import Compiler.AirRange  -- [AIR-range] the bit-decomposition range gadget: k boolGadgets + recomposition as a ConstraintSystem; correct (iff) + bounds (cast of n < 2^k) + val_lt (ZMod p, 2^k ≤ p — the lift CLOSED) + complete (every n < 2^k accepted)
import Compiler.AirBignum  -- fixed-width radix-2^k addition over Theory.Bignum: emitted range/carry constraints, exact integer soundness, overflow rejection
import Compiler.AirModularView  -- exact modular-view AIR plus wide fixed-modulus scalar multiplication; FHEgg q0×24-bit quotient bounds are proved, while the signed/compressed equation frontend remains explicit
import Compiler.BignumKernelABI  -- Lean-owned versioned call envelope: metadata schedules native arithmetic only; acceptance remains exactly descriptorHolds
import Compiler.BfvAllModuliKernelCalls  -- FHEgg q0/q1/q2 fixed-modulus calls in deployed order, with exact 10/10/11 radix-64 layouts and descriptorHolds acceptance
import Compiler.BfvInputValidity  -- one committed owner witness binds selector/table validity, bounded BFV inputs, public relation identifiers, and all 384 modulus-major kernel calls
import Compiler.BfvCompressedEquation  -- audited FHEgg 12,435-coordinate/384-row schema and the first exact q0 shifted-quotient AIR join; the full signed accumulator and Lean-owned transcript control stay explicit
import Compiler.WideDigestAir  -- [AIR-wide-digest] WDG1/domain/9-limb encoding pinned through emit; canonicality and 248-bit capacity proved; sponge schedule, concrete permutation, native-output checks, and [COMMIT-CR] remain explicit
import Compiler.WideDigestByteDecodeAir  -- raw four-byte little-endian limbs are range-checked and proved < BabyBear before field recomposition; raw p is universally rejected
import Compiler.Ext6Conformance  -- BabyBear[u]/(u^6−31) irreducible with finrank six; the six-lane multiplication formula and known vectors are proved for unverified native compute to reproduce
import Compiler.GateMleExt6  -- emitted descriptor residuals lifted and gamma-batched in Ext6, with exact MLE sumcheck rounds/terminal; the succinct factored-selector commitment opening is the sole remaining gate-oracle seam
import Compiler.GateFactoredExt6 -- seven sparse selector operands give the exact gamma-batched descriptor claim, degree-two rounds, public trace functionals, and a sharp fresh-eta aggregation bound
import Compiler.GateTraceRelationExt6 -- extends eta aggregation to the entire public prefix and zero padding, and proves the exact Ext6 subfield-evaluation bound behind sampled base-limb checks
import Compiler.NextgenLightClientPublicInputs -- exact current binary light-client public schema: consuming decoder round-trip/injectivity, canonical BabyBear cells, exact framed length, and public-prefix uniqueness; handwritten native code remains unverified
import Compiler.SemanticTurnReceiptDescriptor -- Lean-authoritative semantic receipt declaration -> AIR -> emitted first-order artifact; downstream native code only reads the generated descriptor
import Compiler.SemanticController -- arbitrary native oracle may return bounded data only; Lean owns authorization, challenge/order, descriptor checks, and the sole Verified token
import Compiler.TranscriptController -- Lean-owned phased transcript program: native replies are data, challenges and query order are derived internally, and only the Lean checker can accept
import Compiler.AirHash  -- [AIR-poseidon] the hash-permutation gadget: parameterized Poseidon2-style rounds (add-rc, S-box x^α full/partial, linear layer) as DSL terms; permGadget_eval (circuit ⟺ executor, all R rounds) + hashConstraint (nullifier ≐ hash(note), iff + teeth + complete); [AIR-poseidon-params] the deployed constants, [COMMIT-CR] the crypto floor
import Compiler.AirMembership  -- [AIR-membership] the Merkle-membership gadget: mux-selected compression (permGadget reused) folded up a path as one DSL term + boolGadget per direction bit; membership_correct (iff, every depth) + membership_meaning (∃ path ⟺ member, sound+complete) + teeth (root & bits); [COMMIT-CR]/[AIR-poseidon-params] inherited — the last note-spend gadget before [PRIVATE-TURN-air] composition
import Compiler.NoteSpend  -- [PRIVATE-TURN-air] CLOSED at the arithmetization level: the shielded note-spend = rangeGadget ++ hashConstraint (nullifier) ++ hashConstraint (commitment) ++ membershipGadget over ONE shared witness; noteSpend_correct (iff = the 3 gadget meanings conjoined) + noteSpend_binds (accepted ⟹ ValidSpend) + noteSpend_meaning (∃ asg ⟺ ∃ note, ValidSpend — the relation loom_zk_argument proves knowledge of); HIDING is Loom/ZK's layer, [COMMIT-CR]/[AIR-poseidon-params] the floors
import Compiler.AdmissionAir  -- [ADMISSION-air] the kernel's GATED ADMISSION (Verb = admission × footprint), derived: admissionGadget = capabilityGadget (hashConstraint + membershipGadget — the cap hashes into the committed authority set) ++ footprintGadget (boolGadget flags + frame terms (1−fᵢ)·(postᵢ−preᵢ) — undeclared cells stand still, touched ⊆ declared) ++ targetGadget (fᵢ·(cellᵢ−target) — declared cells ARE the capability's target, the ι=1 coupling); admission_correct (iff = AdmissionHolds, statement-first) + admission_authorizes (∃-form memberAtDepth soundness) + gates_touch/covers teeth + admission_complete; keystones ZMod 7/13 with per-gadget attribution (rights-escalation forgery rejected both ways; FULL authority still rejected on an out-of-footprint touch); the Kernel correspondence (Hyperedge verbs, caps table) in PROSE — residual [ADMISSION-kernel-bridge] (Assurance-side identification with the kernel's admission predicate, rights decode, global frame, ι=N disjointness)
import Compiler.Emit  -- the EMIT PATH (verified half): ConstraintDescriptor — first-order, serializable, NO functions inside — + emit = flattenSystem (the fold, REUSED) ∘ wire layout; emit_faithful (descriptorHolds ⟺ gatesHold + root-zeros, EVERY witness, unconditional) + emit_accepts_iff (descriptor satisfiable ⟺ systemAccepts ⟺ executor) + emit_wellFormed; the note-spend emitted as the worked example; residuals [EMIT-backend] (wire-format + WGPU fold — unverified compute, adopts breadstuffs' gpu_hidingfri_fold into our work, never a Rust AIR), [EMIT-sound] (prover acceptance ⇒ descriptorHolds inherits the FRI/STARK floor), [EMIT-share] (closed by Compiler.EmitShare)
import Compiler.EmitShare  -- [EMIT-share] CLOSED: hash-consing CSE on the descriptor, a PASS with its own faithfulness theorem — cse (one walk: wire-substitution + signature table, Std.HashMap-backed); cse_holds (forward, UNCONDITIONAL, same witness) + holds_of_cse_holds (backward under SSA, witness through cseSubst) + cse_faithful (satisfiability-equivalence); the SSA hypothesis is REAL (backward is FALSE without it — counterexamples in the header) and DISCHARGED at the deployed shape by emit_ssa (inputs-below-output from flattenSystem_scoped + allocation order made explicit); cse_emit_accepts_iff re-closes the seam THROUGH the CSE (the prover on the SMALL descriptor proves the SAME statement); note-spend measured 2,696,666 → 220 gates (compiled #eval, ≈12,258×); residual [EMIT-share-compact] (wire renumbering + dead-gate sweep; structural sharing only — no algebraic identities)
import Compiler.EmitSerialize  -- [PROVER-serialize] CLOSED: the descriptor wire-format concretized (JSON, constants as canonical ZMod.val, modulus stamped) + reader/writer over ZMod p, round-trip checked at build time with teeth; [PROVER-field] BabyBear p = 2^31−2^27+1 proved prime (norm_num) so the emit-path theorems apply verbatim; the 4-bit rangeGadget emitted over BabyBear as prover/testdata/demo_descriptor.json (satisfiable at x=13 + teeth at x=14, decided) — the conformance anchor for the UNVERIFIED Rust prover/ crate, which only ever reads
import Compiler.SumcheckVerifierAir  -- [RECURSE-verifier] first component: the sumcheck VERIFIER as a ConstraintSystem (round checks g_i(0)+g_i(1) ≐ chain_i with chain the values-form scChain — the (1−r)·g(0)+r·g(1) fold — + the final oracle-wire check); sumcheckVerifier_correct (iff = SumcheckVerifierAccepts, statement-first) + emit_accepts_iff consumed on the gadget (the recursion apex: "the verifier accepted" is itself an emitted, Loom-provable statement); keystones ZMod 7/13 (honest MLE-of-AND transcript accepted, claim/final wires FORCED, tampered message & tampered challenge rejected with per-check attribution); residuals [RECURSE-sumcheck-bridge] (the Loom.SumcheckAccepts identification, Assurance-side) + [RECURSE-verifier] (FS challenge-binding via AirHash, oracle-binding via AirMembership, FRI-query gadget)
import Compiler.FriQueryVerifierAir  -- [RECURSE-verifier] last major component: the FRI query's fold-consistency check as a ConstraintSystem (per round: twiddle-inverse tw·twoX ≐ 1 — the fold's division WITNESSED, a mul gate — + fold-consistency next ≐ (lo+hi)·half + β·(lo−hi)·tw, Loom.Proximity.fold's twiddle form; + the final low-degree check); friQueryVerifier_correct (iff = FriQueryAccepts, statement-first) + _correct_div (under 2·half=1 acceptance IS the divided Loom-fold equations) + recursiveVerifierPair_correct (sumcheck ++ FRI-query = both accept, the apex composition step) + emit_accepts_iff consumed on the gadget; keystones ZMod 7/13 (honest 2-round fold of X+1 accepted incl. the chained wiring next₀ = lo₁, tampered opening & fake twiddle rejected with per-check attribution, opened/twiddle/final wires FORCED quantified); residuals [RECURSE-fri-bridge] (the Loom.fold identification, Assurance-side) + [RECURSE-verifier] (the wire-sharing composition: FS challenges via AirHash, openings via AirMembership, twoX via the index's domain point)
import Compiler.FiatShamirAir  -- [RECURSE-verifier] the Fiat–Shamir challenge BINDING: fsBindingGadget = one AirHash hashTerm per squeeze, the absorb–squeeze chain carried by wire-sharing (prev challenge wire = slot 0 of the next block); fsBinding_correct (iff = FsBound: every challenge wire ≐ the chain hash of its transcript PREFIX — round-local hash equations ⟺ global chain, one induction) + teeth + complete; boundVerifier = fsBinding ++ sumcheckVerifier ++ friQueryVerifier (boundVerifier_correct = the 3 meanings conjoined; boundVerifier_challenges_bound: with chal/β wires SHARED with squeeze wires, acceptance FORCES derived challenges — the composed AIR is a SELF-CONTAINED non-interactive verifier) + emit_accepts_iff consumed on the composed demo; keystones ZMod 7/13 (honest derived-challenge transcripts accepted; the free-challenge forgery ACCEPTED by the unbound pair and REJECTED by the binding with per-squeeze attribution; ZMod 7 challenge wires FULLY determined, 49-case quantified); residuals [RECURSE-merkle-bind] (openings/roots via AirMembership — the last composition piece) + [RECURSE-fs-sponge] (deployed sponge mode) + [RECURSE-fs-bridge] (the Loom FS identification, Assurance-side) + [FS-oracle] floor
import Compiler.MerkleBindAir  -- [RECURSE-merkle-bind] CLOSED: openingBindingGadget = one AirMembership membershipGadget per FRI round (opened wire = leaf, commitment-root wire = root; pair-per-leaf: hi IS lo's first path sibling by wire-sharing); openingBinding_correct (iff = OpeningsBound, statement-first) + _member (every accepting asg's openings are memberAtDepth members) + _complete + _meaning (∃ asg ⟺ ∀ k member, both ways); fullVerifier = boundVerifier ++ openingBindingGadget (fullVerifier_correct = FS-bound ∧ sumcheck ∧ FRI ∧ Merkle-bound; fullVerifier_binds: at shared wiring NOTHING on the proof-carrying wires is free — derived challenges + member openings) + emit_accepts_iff consumed: the WHOLE light-client verifier is ONE emitted Loom-provable statement (a proof verifies a proof); keystones ZMod 7/13 (ZMod 7 opened wire FULLY forced; ZMod 13: all 13 fold-consistent forged openings pass the FS-bound verifier, the binding cuts to the collision fiber {1,2,8} — [COMMIT-CR] made concrete); residual [RECURSE-full-resid] (root absorption into FS transcript, sumcheck-oracle opening, twoX/domain points, query multiplicity, Loom bridges) + floors inherited
import Compiler.SumcheckConformance  -- [PROVER-sumcheck] conformance vector: Loom's mle/roundSum instantiated at a fixed m=3 BabyBear table (LSB-first index convention pinned), all reference values KERNEL-DECIDED + the chain identities (roundSum_zero/_succ/_last) instantiated as theorems; writes prover/testdata/sumcheck_conformance.json for the UNVERIFIED Rust sumcheck engine to reproduce — vector agreement, never refinement
import Compiler.FriConformance
import Compiler.PredCompile  -- [PRED-COMPILE] the GENERAL Pred → ConstraintSystem compiler (ATLAS law 11, n=1 → n=∀): lowerA/lowerL one fold over the Pred AST (isZero-witnessed atoms, presence-masked fail-closed absence, not/all/any as indicator algebra, witnessed = fail-closed 0, order atoms LOUDLY unsatisfiable per law 10) + wit the emitted witness generator; lower_correct (∃ aux, accepts ⟺ Pred.eval — sound ∀-aux + complete at wit, ONE mutual induction over ALL constructors) + lower_subsumes_boolGadget (the hand gadget reproduced through the general theorem); castInjOn the deployment cast label; residuals [PRED-COMPILE-order]/[PRED-COMPILE-oracle]/[PRED-COMPILE-quant]  -- [PROVER-fri-fold] conformance vector: Loom/Proximity's VERIFIED fold instantiated on the canonical 16-point two-adic BabyBear domain (16→8→4 tower, FoldingData laws kernel-decided); the folded words are THEOREM-equal to Loom.fold via the division-free characterization fold_eq_of_mul_eq (numeric leaf kernel-decided), the arity-4 β-squaring chain pinned; ext4Mul (the deployed BabyBear⁴ X⁴=11 formula) PROVED to be multiplication in BabyBear[X]/(X⁴−11) (ext4Mul_correct, AdjoinRoot) + known-answer products decided; writes prover/testdata/fri_conformance.json for the UNVERIFIED Rust fold (adopting breadstuffs' wgsl fold MATH) to reproduce — vector agreement, never refinement; residual [PROVER-field-ext4-irred] (X⁴−11 irreducibility, field-ness of the quotient) named, not claimed
