/-
# Compiler — the arithmetization spine (ATLAS §7).
-/
import Compiler.Placeholder  -- carve marker: syntactic-leaf IR, fold_unique, seqDescr, descriptor + codec
import Compiler.Signature    -- N3: abstract signatures, Term (= WType), fold_unique, agree_by_initiality, the syntactic-leaves-forced obligation
import Compiler.Air  -- the arithmetization DSL (derived): circuit⟺executor by initiality (N3), the first gadget; [AIR-poseidon]/[AIR-membership] the rungs toward a note-spend
import Compiler.AirFlatten  -- [AIR-flatten] CLOSED: nested expressions → degree-≤2 gate systems with aux wires, the flatten a fold; wire-forcing refinement (sound+complete+unique) → gate system ⟺ executor
import Compiler.AirRange  -- [AIR-range] the bit-decomposition range gadget: k boolGadgets + recomposition as a ConstraintSystem; correct (iff) + bounds (cast of n < 2^k) + val_lt (ZMod p, 2^k ≤ p — the lift CLOSED) + complete (every n < 2^k accepted)
import Compiler.AirHash  -- [AIR-poseidon] the hash-permutation gadget: parameterized Poseidon2-style rounds (add-rc, S-box x^α full/partial, linear layer) as DSL terms; permGadget_eval (circuit ⟺ executor, all R rounds) + hashConstraint (nullifier ≐ hash(note), iff + teeth + complete); [AIR-poseidon-params] the deployed constants, [COMMIT-CR] the crypto floor
import Compiler.AirMembership  -- [AIR-membership] the Merkle-membership gadget: mux-selected compression (permGadget reused) folded up a path as one DSL term + boolGadget per direction bit; membership_correct (iff, every depth) + membership_meaning (∃ path ⟺ member, sound+complete) + teeth (root & bits); [COMMIT-CR]/[AIR-poseidon-params] inherited — the last note-spend gadget before [PRIVATE-TURN-air] composition
import Compiler.NoteSpend  -- [PRIVATE-TURN-air] CLOSED at the arithmetization level: the shielded note-spend = rangeGadget ++ hashConstraint (nullifier) ++ hashConstraint (commitment) ++ membershipGadget over ONE shared witness; noteSpend_correct (iff = the 3 gadget meanings conjoined) + noteSpend_binds (accepted ⟹ ValidSpend) + noteSpend_meaning (∃ asg ⟺ ∃ note, ValidSpend — the relation loom_zk_argument proves knowledge of); HIDING is Loom/ZK's layer, [COMMIT-CR]/[AIR-poseidon-params] the floors
import Compiler.Emit  -- the EMIT PATH (verified half): ConstraintDescriptor — first-order, serializable, NO functions inside — + emit = flattenSystem (the fold, REUSED) ∘ wire layout; emit_faithful (descriptorHolds ⟺ gatesHold + root-zeros, EVERY witness, unconditional) + emit_accepts_iff (descriptor satisfiable ⟺ systemAccepts ⟺ executor) + emit_wellFormed; the note-spend emitted as the worked example; residuals [EMIT-backend] (wire-format + WGPU fold — unverified compute, adopts breadstuffs' gpu_hidingfri_fold into our work, never a Rust AIR), [EMIT-sound] (prover acceptance ⇒ descriptorHolds inherits the FRI/STARK floor), [EMIT-share] (tree-flatten duplicates subterm gates; CSE is a future derived rung)
