/-
# Compiler — the arithmetization spine (ATLAS §7).
-/
import Compiler.Placeholder  -- carve marker: syntactic-leaf IR, fold_unique, seqDescr, descriptor + codec
import Compiler.Signature    -- N3: abstract signatures, Term (= WType), fold_unique, agree_by_initiality, the syntactic-leaves-forced obligation
import Compiler.Air  -- the arithmetization DSL (derived): circuit⟺executor by initiality (N3), the first gadget; [AIR-poseidon]/[AIR-membership] the rungs toward a note-spend
import Compiler.AirFlatten  -- [AIR-flatten] CLOSED: nested expressions → degree-≤2 gate systems with aux wires, the flatten a fold; wire-forcing refinement (sound+complete+unique) → gate system ⟺ executor
import Compiler.AirRange  -- [AIR-range] the bit-decomposition range gadget: k boolGadgets + recomposition as a ConstraintSystem; correct (iff) + bounds (cast of n < 2^k) + val_lt (ZMod p, 2^k ≤ p — the lift CLOSED) + complete (every n < 2^k accepted)
import Compiler.AirHash  -- [AIR-poseidon] the hash-permutation gadget: parameterized Poseidon2-style rounds (add-rc, S-box x^α full/partial, linear layer) as DSL terms; permGadget_eval (circuit ⟺ executor, all R rounds) + hashConstraint (nullifier ≐ hash(note), iff + teeth + complete); [AIR-poseidon-params] the deployed constants, [COMMIT-CR] the crypto floor
import Compiler.AirMembership  -- [AIR-membership] the Merkle-membership gadget: mux-selected compression (permGadget reused) folded up a path as one DSL term + boolGadget per direction bit; membership_correct (iff, every depth) + membership_meaning (∃ path ⟺ member, sound+complete) + teeth (root & bits); [COMMIT-CR]/[AIR-poseidon-params] inherited — the last note-spend gadget before [PRIVATE-TURN-air] composition
import Compiler.NoteSpend  -- [PRIVATE-TURN-air] CLOSED at the arithmetization level: the shielded note-spend = rangeGadget ++ hashConstraint (nullifier) ++ hashConstraint (commitment) ++ membershipGadget over ONE shared witness; noteSpend_correct (iff = the 3 gadget meanings conjoined) + noteSpend_binds (accepted ⟹ ValidSpend) + noteSpend_meaning (∃ asg ⟺ ∃ note, ValidSpend — the relation loom_zk_argument proves knowledge of); HIDING is Loom/ZK's layer, [COMMIT-CR]/[AIR-poseidon-params] the floors
import Compiler.Emit  -- the EMIT PATH (verified half): ConstraintDescriptor — first-order, serializable, NO functions inside — + emit = flattenSystem (the fold, REUSED) ∘ wire layout; emit_faithful (descriptorHolds ⟺ gatesHold + root-zeros, EVERY witness, unconditional) + emit_accepts_iff (descriptor satisfiable ⟺ systemAccepts ⟺ executor) + emit_wellFormed; the note-spend emitted as the worked example; residuals [EMIT-backend] (wire-format + WGPU fold — unverified compute, adopts breadstuffs' gpu_hidingfri_fold into our work, never a Rust AIR), [EMIT-sound] (prover acceptance ⇒ descriptorHolds inherits the FRI/STARK floor), [EMIT-share] (closed by Compiler.EmitShare)
import Compiler.EmitShare  -- [EMIT-share] CLOSED: hash-consing CSE on the descriptor, a PASS with its own faithfulness theorem — cse (one walk: wire-substitution + signature table, Std.HashMap-backed); cse_holds (forward, UNCONDITIONAL, same witness) + holds_of_cse_holds (backward under SSA, witness through cseSubst) + cse_faithful (satisfiability-equivalence); the SSA hypothesis is REAL (backward is FALSE without it — counterexamples in the header) and DISCHARGED at the deployed shape by emit_ssa (inputs-below-output from flattenSystem_scoped + allocation order made explicit); cse_emit_accepts_iff re-closes the seam THROUGH the CSE (the prover on the SMALL descriptor proves the SAME statement); note-spend measured 2,696,666 → 220 gates (compiled #eval, ≈12,258×); residual [EMIT-share-compact] (wire renumbering + dead-gate sweep; structural sharing only — no algebraic identities)
import Compiler.EmitSerialize  -- [PROVER-serialize] CLOSED: the descriptor wire-format concretized (JSON, constants as canonical ZMod.val, modulus stamped) + reader/writer over ZMod p, round-trip checked at build time with teeth; [PROVER-field] BabyBear p = 2^31−2^27+1 proved prime (norm_num) so the emit-path theorems apply verbatim; the 4-bit rangeGadget emitted over BabyBear as prover/testdata/demo_descriptor.json (satisfiable at x=13 + teeth at x=14, decided) — the conformance anchor for the UNVERIFIED Rust prover/ crate, which only ever reads
import Compiler.SumcheckConformance  -- [PROVER-sumcheck] conformance vector: Loom's mle/roundSum instantiated at a fixed m=3 BabyBear table (LSB-first index convention pinned), all reference values KERNEL-DECIDED + the chain identities (roundSum_zero/_succ/_last) instantiated as theorems; writes prover/testdata/sumcheck_conformance.json for the UNVERIFIED Rust sumcheck engine to reproduce — vector agreement, never refinement
import Compiler.FriConformance  -- [PROVER-fri-fold] conformance vector: Loom/Proximity's VERIFIED fold instantiated on the canonical 16-point two-adic BabyBear domain (16→8→4 tower, FoldingData laws kernel-decided); the folded words are THEOREM-equal to Loom.fold via the division-free characterization fold_eq_of_mul_eq (numeric leaf kernel-decided), the arity-4 β-squaring chain pinned; ext4Mul (the deployed BabyBear⁴ X⁴=11 formula) PROVED to be multiplication in BabyBear[X]/(X⁴−11) (ext4Mul_correct, AdjoinRoot) + known-answer products decided; writes prover/testdata/fri_conformance.json for the UNVERIFIED Rust fold (adopting breadstuffs' wgsl fold MATH) to reproduce — vector agreement, never refinement; residual [PROVER-field-ext4-irred] (X⁴−11 irreducibility, field-ness of the quotient) named, not claimed