/-
# Loom — the proof system.

Import-boundary-checked: Loom/ may import only Mathlib, Theory, and Loom
(`scripts/check-import-boundary.sh`).
-/
import Loom.Statements  -- OB-2 / OB-6 statements, statement-first
import Loom.CorrelatedAgreement  -- OB-6 realized: mutual correlated agreement at unique decoding (WHIR Lemma 4.10), proved
import Loom.ReedSolomon  -- RS instantiation: Cor 4.11's UD shape (exact min distance; Thm 4.8 stays a hypothesis)
import Loom.ConstrainedCode -- WHIR Def 4.5 CRS: the claim object the accumulator folds; γ-batch completeness PROVED + exact-word Schwartz-Zippel soundness; proximity lift stays prose [CRS-batch-sound]
import Loom.OutOfDomain -- OOD sampling (WHIR Lem 4.25 / Arc Lem 3.4): pairwise pin + (ℓ choose 2) union bound + ∃!-pin all PROVED; oodConstraint bridges OOD claims into the CRS channel; keystones over F₅ (bound ATTAINED); proximity lift stays prose [OOD-pin-proximity]
import Loom.Rbr         -- RBR knowledge-soundness vocabulary (WARP §4 + App. B); [OB-2] depth composition stated
import Loom.Depth       -- [OB-2] audit: as-stated REFUTED (Z = ∅ corner); [OB-2′] repair + Thm B.4 tower (B.5 extractor, Claim B.6, fresh-slot bound) modulo one named seam [OB-2a]
import Loom.Sumcheck    -- sumcheck soundness: single-round root-counting (reuses ReedSolomon), v-round union bound (reuses uniformProb toolkit); adaptive prefix-dependent union bound DISCHARGED (adaptiveUnionBound_holds)
import Loom.SumcheckReduction -- the bridge: a LinearConstraint IS a sumcheck sum-claim (constraint_as_sumcheck, rfl); sumcheck retires a violated constraint at v·d/|F| (fixed + ADAPTIVE packaging assembled from sumcheck_reduction + adaptiveUnionBound_holds); §6 list absorption via γ-batch; keystones over F₅; MLE realizer stays prose [SC-reshape]
import Loom.FiatShamir  -- the transcript layer: the ROM as an INHABITED lazy-sampling handler (laws proved; the landed SR game machine-checked to BE a handler run), fiatShamir transform + teeth, FS-of-RBR keystone ⟺ [OB-2′] (BCS bridge PROVED) — sound modulo the one seam [OB-2a]; idealization named [FS-ROM]
import Loom.Accumulator -- THE HEART: the WARP-shape accumulated claim (rt,α,μ,β,η) as a constrained-codeword claim + the γ-fold (Constr 5.5/7.4); closure PROVED, keystones built over F₅; [ACC-sound]/[ACC-extract] prose residuals
import Loom.AccSound    -- [ACC-sound] closed at the bound level: exact-word soundness for BOTH fold rules + δ-proximity (t−1)ℓ/|F| (list-size hypothesis; ℓ=1 discharged at UD) + the cross-word accumulation step at UD with mutual CA consumed (err⋆ + (s−1)ℓ/|F|); keystones ATTAIN every bound over F₅; residuals [ACC-sound-list]/[ACC-sound-rbr]
import Loom.AccSoundRbr -- [ACC-sound-rbr] round-error bound PROVED: accRbrError (= foldClaims_sound_proximity_UD's err⋆+1/|F|, exact-word 1/|F| at errstar≡0) packaged as an RBR round-error function in Rbr's uniformProb-over-Chal shape; accFsSound wires it into FiatShamir's FsOfRbrSound (PROVED, cited not re-derived) — [LC-fs-adaptive]'s (t+n) grinding factor discharged MODULO the game instance; keystones ATTAIN accRbrError over F₅; residual [ACC-sound-rbr-game] names the obstruction (unconditional per-round bound vs AccSound's falseness-hypothesis bound; the natural realizer is AccExtract's two-point extractor at the chain level, not a naive single-round backward extractor)
import Loom.ZK          -- OB-4 (contribution slot, confirmed open): compliance/accumulation split (2026/289 Thm 1 generic) on the real append algebra + the masked γ-fold's word-level hiding PROVED (mask bijection, uniform-on-public-support simulator, witness independence); sharp F₅ keystone zk ⟺ γ≠0; the opening-leakage mathematics stays [OB-4-hiding] prose
import Loom.LightClient -- the v0 apex: history = chain of links (AccClaim + seam roots), SeamOk decidable, aggregate = foldClaims composed; derandomized light-client theorem PROVED (lightClient_attests), naive one-shot form REFUTED (oneShot_lightClient_false); seam/reorder teeth decided; soundness upgrade named [LC-sound]
import Loom.Decider     -- D_ACC, the light client's one-time final check: decider ⟺ AccClaim.Satisfies (decider_sound), DECIDABLE and computing over F₅ (accept + three reject modes by decide, code membership included via the span presentation); depth independence PROVED structurally (foldChain_weights + decider_depth_independent); residuals [DEC-proximity]/[DEC-open]/[DEC-succinct]
import Loom.LightClientSound -- [LC-sound] closed at the bound level: ONE uniformly sampled schedule replaces the ∀-schedule quantifier — exact-word SHARP 1/|F| (two-point extractor, whole chain) + the deployable δ-form n·(err⋆+1/|F|) (full chain induction, AccSound's per-fold UD bound composed by the Depth union-bound pattern); phantomChain's forging set computed = the diagonal, bound ATTAINED at 1/5; residuals [LC-sound-fs] (FS transport) + [ACC-extract] (unchanged)
import Loom.LightClientFS -- [LC-sound-fs] closed at the fixed-chain level: the FS-HASH-DERIVED schedule (oracle at each link's transcript prefix, σ-before-γ) inherits BOTH light-client bounds verbatim — prefix distinctness PROVED (growing lengths) + the handler-fold law (distinct fresh queries each draw their own coin), so the derived schedule IS the fresh coins and the pushforward is uniform on the nose; phantom keystones recomputed in COIN space (forging event = the diagonal, 1/5 attained); residuals [LC-fs-adaptive] (t-query grinding, rides [ACC-sound-rbr]+fsKeystone_proved) + [FS-ROM]/[ACC-extract] (inherited)
import Loom.ZKHiding    -- [OB-4-hiding] advanced: the opening-leakage core PROVED — MDS t-wise independence (interpolation bijection ∃!/BijOn at t=d, fiber-translation uniformity at t≤d) + MaskedOpeningHiding for RS at t≤d, γ≠0 (uniform-tuple simulator, witness-free) via the surjectivity reduction; teeth BOTH dials (γ=0 leaks the witness's symbols; t=d+1 refuted at EVERY γ — parity check computed over F₅, unreachable tuple exhibited); sharp F₅ iff; remaining research edge named [OB-4-hiding-rbr] (constrained-mask surjectivity, joint word+opening simulator, multi-step schedule, RBR re-proof)
import Loom.ConstrainedMask -- [OB-4-hiding-rbr] gap (1) closed at r=1: constrainedMaskSpace (RS ⊓ ker(eval at pt), a genuine Submodule, tied back to ConstrainedCode's constrainedRS) + exists_constrainedMask_open (vanishing-polynomial factorization: t+1≤d suffices, distinct from the query points) fed through maskedOpeningHiding_of_surj into constrainedMask_hiding — the mask CAN be constraint-respecting and still hide; F₅ keystones ATTAIN the tight bound (t+1=d=2) and REFUTE one query past it (unreachable tuple, decide-checked); general r and non-evaluation linear channels stay prose [CMASK-multi]
import Loom.AccExtract  -- [ACC-extract] advanced: KNOWLEDGE soundness of the γ-fold — extractPair (the two-point straightline extractor, g=(γ−γ')⁻¹•(h−h'), f=h−γ•g) PROVED to invert the fold exactly + uniquely; accKnowledgeSound: two VERIFYING folds at distinct challenges yield genuine witnesses of the INDIVIDUAL claims + transcript consistency; backwards peel iterated at depth 2 (the wAt shape); keystones over F₅ (recovery by decide; teeth = diagonal collapse (h,0) AND single-fold ambiguity — two transcripts are information-theoretically necessary); residuals [ACC-extract-chain] (chain recursion + Depth Thm B.4) / [ACC-extract-bind] (Merkle/BCS binding + erasure recovery from opened columns)
import Loom.SmallField  -- [OB-8] deployed-field reality: securityBits calculus (λ bits ⟺ N·2^λ ≤ q^k, monotone in the extension degree), sumcheck_lambda_secure (+ _ext at |F_{q^k}| = q^k) instantiating the landed v·d/|F| bound against a λ target; base-committed words with extension challenges (F_q-linear lift, RS membership + γ-fold closure at the same degree bound); keystones COMPUTED both directions (2³¹ → 24 bits, deg-4 → 117; REAL BabyBear prime deg-4 → 116, NOT 117); teeth: F₅ at N=100 is VACUOUS (every event, certainty included, satisfies the "bound") and the same numerator clears λ=128 at deg 60 — extension load-bearing; end-to-end F₅ λ=2 ceiling vs GF(25) λ=4; residual [OB-8-tower] (binary-tower specifics + WARP App. D linearity loss)
import Loom.Proximity   -- [DEC-proximity]/[OB3-c-prox] core: the FRI/WHIR folding LDT — fold + even/odd algebra + fold_preserves_code + full completeness PROVED; round-reduction soundness proximity_sound(_prob) at m·b/|F| PROVED modulo per-level [PROX-fold-distance], which is itself PROVED at sub-quantization δ (b=1, exact-membership regime end-to-end sound TODAY, F₅ keystone attains the bound) and REDUCED at macroscopic δ to the ONE standing RS proximity-gap hypothesis (WHIR Thm 4.8 / BCIKS = ReedSolomon's hPG); query/Merkle layer stays [DEC-open]-adjacent prose
import Loom.Commitment  -- the vector-commitment (Merkle/BCS) binding layer under [ACC-extract-bind]/[DEC-open]: OpeningScheme + PositionBinding + BindingCommitment (binding a Prop FIELD — honest floor), INHABITED by idealCommitment (identity scheme, binding PROVED, axiom-free); seams closed at the all-positions resolution (committed_extract_bind/committed_fold_bind attribution + decider_open_sound/complete), word_binding + commit_injective derived; keystones over F₅ (binding fires generic+computed; equivocator: a genuine OpeningScheme with NO BindingCommitment extension, and the attribution conclusion FAILS for it — binding load-bearing, refuted not unproved); deployed Merkle/sponge stays [COMMIT-CR]; t-column erasure lift stays [ACC-extract-bind](b)
import Loom.AccExtractChain -- [ACC-extract-chain] CLOSED at the word level, arbitrary depth: extractChain (one extractPair per link, flat n+1-schedule family) recovers BUILT per-link witnesses of the whole history — aggregate_channel_peel (the aggregate at ANY schedule IS one γ-fold of the peeled remainder with link k's claim), accKnowledgeSound REUSED per link, no induction residual; extract_head_recurses = the wAt backwards-recursion step on the chain; lightClientKnowledgeSound upgrades lightClient_attests' ∃ to constructed witnesses at n+1 transcripts; failure price = the landed [LC-sound] bounds (1/|F| sharp, n·(err⋆+1/|F|) δ), depth composition cited from OB2_depth_composition_nonneg_proved; keystones over F₅ on goodChain (recovery by decide; teeth = diagonal collapse + single-schedule ambiguity); residuals [ACC-extract-bind]/[ACC-sound-rbr] (pre-existing, unchanged)
import Loom.Erasure     -- [ACC-extract-bind](b) CLOSED at unique decoding: recoverFromColumns (Lagrange-interpolate d of t opened columns, evaluate on the whole domain) + recoverFromColumns_sound (t ≥ d distinct opened symbols of a genuine codeword recover it EXACTLY — full word equality, via ZKHiding's open_determines root-counting, reused not re-derived) + committed_word_recovered (composes BindingCommitment binding with the recovery, closing the t-column erasure lift Commitment.lean deferred); keystones over F₅ (xWord recovered from 2 of its symbols, reaching an UNOPENED coordinate; teeth: t=d−1=1 column is consistent with TWO distinct codewords, the bound load-bearing; junk-0 outside the regime, honest not silently wrong); beyond unique decoding stays prose [ERASURE-list] (rides CorrelatedAgreement + OutOfDomain's [OOD-pin-proximity], never assumed here)
import Loom.DeciderProximity -- [DEC-proximity] deployed decider: deciderProx (close δ + channels, collapses to the exact decider below quantization — deciderProx_iff_decider_of_lt_inv_card) + deciderProxLDT (ONE proximityTest descent + channels); soundness COMPOSED from proximity_sound (deciderProx_sound(_prob): δ-far accepted ≤ m·b·|F|^{m−1}, prob m·b/|F|) — UNCONDITIONAL b=1 at sub-quantization δ (deciderProx_sound_subquant), macroscopic δ rides the ONE standing hPG (consumed, not claimed); certification bridge deciderProx_of_card_gt (counts beyond error mass ⇒ semantic verdict); depth independence + [DEC-open] seam transported; F₅ keystones accept+reject per conjunct, spike acceptance set EXACT ({![3]}, bound attained), zero-residual head fired; spot-check/query layer stays [DEC-prox-query] prose
import Loom.ZkArgument   -- [OB-4-hiding-rbr] gap (2) closed at the single-round level: ZkArgument bundles completeness (foldClaims_satisfies) + knowledge-soundness (accKnowledgeSound, TWO transcripts) + zero-knowledge (MaskedOpeningHiding, ONE transcript), composed non-vacuously via the mask-space bridge (Loom/ZK.lean's satWords C B IS Loom/ConstrainedMask.lean's constrainedMaskSpace for a single evaluation constraint — mem_constrainedMaskSpace_iff_satisfies); F₅ keystone fires all three fields on ONE transcript (completeness_fired/knowledge_sound_fired/zero_knowledge_fired) with teeth both directions (γ=0 kills hiding not knowledge; one transcript kills knowledge not hiding, single_fold_ambiguous_masked); the multi-round game — every round simultaneously extractable (chain-level two-point, per [ACC-sound-rbr-game]) and simulatable, interleaved over depth — stays genuinely open, named [ZK-RBR-game]
