/- Objective Bend Core4 metatheory: the proofs about the default-build definitions
(Theory.ObjectiveBend{Types,OpenRecursion,Typing,DemandMachine,DemandData,
DemandCapacity,Extensions}). A separate library so its build is its own gate:
`lake build ObjectiveProofs`. -/
import Theory.ObjectiveBendDemandInvariant
import Theory.ObjectiveBendDemandTyping
import Theory.ObjectiveBendDemandPreservation
import Theory.ObjectiveBendDemandAdequacy
import Theory.ObjectiveBendDemandCompleteness
import Theory.ObjectiveBendDemandDataSoundness
import Theory.ObjectiveBendDemandCollectProofs
import Theory.ObjectiveBendDemandSettleProofs
import Theory.ObjectiveBendDemandForceProofs
import Theory.ObjectiveBendLedgerPoles
import Theory.ObjectiveBendTemplates
import Theory.ObjectiveBendCheckpointRoundTrip
import Kernel.ObjectiveBendAdmissionSemantics
import Theory.ObjectiveBendDemandForcingExtract
import Theory.ObjectiveBendDemandForcingBack
import Theory.ObjectiveBendDemandForcingConverse
import Theory.ObjectiveBendInteraction
import Theory.ObjectiveBendDemandForcingBackFail
import Kernel.ObjectiveResumeContract
import Kernel.ObjectiveCheckpointInvariant
import Kernel.ObjectiveUpgradeInvariant
import Kernel.ObjectiveDomainInvariant
import Kernel.ObjectLawEnforced
import Kernel.ObjectiveReferenceLift
import Kernel.ObjectiveCallReference
import Kernel.ObjectiveActivityGateRoute
import Compiler.ObjectiveBendFrontEndAdequacy
import Compiler.ObjectiveBendSpecificationClosure
