/-
# Theory — the candidate-independent core (ATLAS §7).

Everything here must be the metatheory of *any* system built this way: abstract
parameters only, no imports outside Mathlib + Theory itself (enforced by
`scripts/check-import-boundary.sh`).
-/
import Theory.Knowledge  -- the verify/find seam: Verifiable/Discharged/Searchable, Claim/Holds/Knower
import Theory.PrivacyProfile  -- observer-indexed privacy axes, typed same-opening/release joins, and compositional noninterference
import Theory.DisclosureDeclaration  -- first-order observer releases require both request-indexed authorization and a checked same-opening witness before VerifiedRelease exists
import Theory.PrivateComputationDeclaration  -- typed ZK/MPC/FHE requests complete only with authorization, named representation bridges, same-opening, evidence, and an explicit disclosure effect
import Theory.IndexedProgram  -- indexed free programs with response-dependent typestate, executable handlers, fold fusion, and cross-carrier logical-relation folds
import Theory.GuardedAdvice  -- eager hole shape, typed late advice, total verification, and durable replay refusal
import Theory.ReactiveReceipt  -- authoritative receipt deltas, dependency-local reactive projections, atomic rejection, and witness-cursor snapshots
import Theory.ReactiveController  -- Lean-owned guarded-hole/reactive control derives Pending/Reject/CommitIntent from data-only host observations; physical CAS remains external
import Theory.CellState  -- typed logical cells, canonical materialization, and validated footprint patches make root coherence, frame, rejection atomicity, and no-ghost state structural
import Theory.CellStateWitness  -- ANTI-VACUITY: a closed schema/codec/materializer/cell whose patch actually reaches `ValidatedPatch` through `validate`, plus stale-root and both footprint-mismatch rejections computed
import Theory.TypedAuthorizationWitness  -- ANTI-VACUITY: a built portal/state/request that reaches `Authorized`, with the policy gate and the epoch equation shown load-bearing as refutations (evidence exists; authority does not follow)
import Theory.AcceptedCellEffectWitness  -- ANTI-VACUITY, the summit: a closed `AcceptedCellEffect` standing on the two witnesses above, forced sealed, with both request-binding equations exhibited as refutations
import Theory.CanonicalTransitionWitness  -- ANTI-VACUITY: a `PreparedTurn` whose derived post-root actually MOVES (`⟨0⟩` to `⟨1⟩`) — a singleton state space would have inhabited the type while testing nothing
import Theory.ReactiveCellTransition  -- declaration-derived reactive control plus validated typed patches; physical CAS/nullifier insertion is an explicit handler premise
import Theory.CanonicalTransition  -- one canonical materialized post and proof-relevant typed delta unify ordinary and reactive prepared turns without a parallel store or caller-supplied roots
import Theory.ResourceCost  -- Lean-owned multi-lane bounds/exact debits, checked word overflow, canonical-turn metering, atomic refusal, and additive composition
import Theory.CanonicalResourceKernel  -- typed sparse asset/account nucleus: transfer, issuer-backed mint/burn, fees, and prepaid leases share one patch-derived conservation law
import Theory.CellSlot  -- stable heterogeneous absent/present slots, canonical payload decoding, and monotone identifiers make creation and retirement first-class transitions
import Theory.CanonicalReactiveView  -- observer-indexed typed lenses advance directly from canonical deltas; accepted guarded holes retain eager nullifiers without a parallel uniform post
import Theory.TypedAuthorization  -- complete-request-indexed authority evidence, explicit bearer/subject holders, exact epochs/revocation, and monotone capability attenuation
import Theory.AuthorizationDeclaration  -- first-order authorization plans compiled to indexed programs; accepted plans construct the request-indexed Authorized proposition
import Theory.CredentialAuthorityFamily  -- signature/proof/capability/token carriers share exact request digests, holder/scope/current-policy semantics, and proof-relevant strict attenuation without mode bypasses
import Theory.EffectDeclaration  -- target-indexed effects derive exact footprints and full-width resource deltas; only authorized, balanced declarations yield an AuthorizedEffect token
import Theory.DeclaredActionLowering  -- a closed create/write/move action language lowers into exact accepted semantic effects without reviving the legacy runtime
import Theory.DeclaredTurn  -- data-only authorization/effect execution with exact-post semantic certification and definitional rejection atomicity
import Theory.TurnTransition  -- ordinary and resumed reactive turns share canonical roots, exact footprints/deltas, frame laws, and atomic refusal
import Theory.AcceptedCellEffect  -- request-indexed semantic effect families admit ZK/MPC/FHE results as canonical cell transitions; sealed is the default and release is explicit
import Theory.AcceptedCellEffectRequestBinding  -- family-selected lawful argument projections close the common request's args digest without duplicating authorization or overbinding envelopes
import Theory.CredentialAuthorityState  -- capability lineage, current epochs/policies, revocations, and operation nullifiers occupy one canonical typed sparse CellState; AuthState roots/reads project from that exact cell
import Theory.CanonicalAuthorityProjection  -- the finite revocation universe is derived from the authority cell's own sparse support, so omitted caller keys cannot erase a live revocation
import Theory.MaterializerCardinality  -- REGRESSION TOOTH: the deleted total-function carrier was uncountable; the landed sparse carrier is characterized by ordinary countability
import Theory.DeployedTotalCarrierAudit  -- closes the deleted total-carrier impossibility teeth for authority and Hyperdocument, completing all four migrated deployed schemas
import Theory.StoreFiniteSupport  -- total semantic stores reachable from zero have an exact sparse realization, while arbitrary infinite-support functions still do not acquire canonical bytes
import Theory.SparseLogicalState  -- the canonical dependent finite-map carrier, with primitive absence and explicit total `readD` views above it
import Theory.DeployedMaterializerWitness  -- effect, authority, and Hyperdocument schemas now have concrete materializers and cells; existence codecs are not deployment wire claims
import Theory.CredentialAuthorityEffects  -- issuance, strict attenuation, revocation, and epoch rotation are sealed AcceptedCellEffect families with exact atomic patches and same-canonical-pre authorization
import Theory.Hyperdocument  -- versioned domain-separated hyperdocument identity, authenticated principals, typed sparse namespaces, and exact canonical CellState mapping
import Theory.StableRanges  -- insertion-stable atom/range anchors, explicit deletion policies, and exact adapters into durable Hyperdocument marks/annotations
import Theory.HyperdocumentOperationIntent  -- acyclic pre-commit OperationId binds canonical action bytes but excludes post/request/effect/final-version identities
import Theory.HyperdocumentOperations  -- first-order create/edit/link/transclude/mark/annotate declarations derive exact accepted content patches, requests, and concrete post records
import Theory.HyperdocumentInterface  -- versioned capability-scoped interface negotiation for content/history reads and mutations; query never grants ambient object authority
import Theory.CausalVersionDag  -- content-addressed causal events admit exact resolved parents and concurrent siblings; current-tip-only is an explicit optional policy
import Theory.HyperdocumentCausalFamily -- ordinary accepted content effects instantiate the causal semantic family; includes one real deployed-schema genesis/history witness
import Theory.CausalVersionAncestry  -- admitted parent edges induce proof-relevant ancestry, acyclicity, and conservative common-base certificates without a fake unique LCA
import Theory.Bignum  -- canonical fixed-width little-endian limbs + proved Nat/Int codec (wide digest/challenge substrate)
import Theory.CrossModulus  -- one canonical integer with exact quotient/remainder views in two coprime moduli; CRT/range/canonicality seams for RNS/FHE bridges
import Theory.CompressedLinearEquation  -- exact signed integer equations normalized to canonical unsigned limb/carry balances for compressed RNS/FHE checks
import Theory.BinaryTower  -- [OB-8-tower] the GF(2) binary-tower field substrate (Binius path)
import Theory.BinaryTowerCodec  -- exact recursive Fan--Paar coordinates and fixed-width 32-byte round-trip; native code remains opaque
import Theory.BinaryTowerFanPaarCodec  -- concrete recursive Fan--Paar coordinate codec and canonical fixed-width byte realization; still no native representation theorem
import Theory.BinaryTowerFanPaar  -- [BTOWER-fanpaar] the Fan–Paar generator recursion + fast tower multiplication
import Theory.BinaryTowerTrace  -- [BTOWER-fanpaar-basis] CLOSED (Wiedemann trace induction) — FanPaarRecursion holds
import Theory.ExtensionBasis  -- [RS-basis] the ring-switching connector (Diamond–Posen 2024/504): the B_κ-indexed K-basis of L (cubeBasis, mathlib finBasisOfFinrankEq reindexed), Definition 2.2's packing as a K-LINEAR EQUIVALENCE (packEquiv/packCube — `.symm` IS Thm 3.5's "reversing Definition 2.2", the emulator's step 3), zero-embedding-overhead as a finrank identity + the element-wise lift's 2^κ overhead factor; tower instantiation [T_{j+d} : T_j] = 2^d so κ = d exactly (deployed Binius shape T₀ ⊂ T₇, deg 128); TEETH — wrong κ admits no cube basis, a repeated coordinate makes packing non-injective (extraction dies), and the element-wise lift is NOT surjective hence refused as a packing map
import Theory.AdditiveNTT  -- [BTOWER-additive-fri] additive domains + subspace-vanishing (GF(2)-linear) + novelpolynomial basis + the additive FRI fold
import Theory.AdditiveNTTTransform  -- [ANTT-transform] CLOSED: the additive NTT is a linear bijection; Selvage/AdditiveProximity now realizes a macroscopic one-round [ANTT-proximity] band, while an executable butterfly/tower backend remains separate runtime work
import Theory.IntegerFingerprint  -- the Zaratan/Limber integer relation `a*b = c + u*m` and its random-prime fingerprint: counting core proved, prime-counting denominator left as a named hypothesis
import Theory.CyclotomicInertia  -- [SIS-inertia] ord_{3^k}(KoalaBear) = phi(3^k) at EVERY k, so Phi_81 is IRREDUCIBLE over F_KB and `F_KB[X]/(Phi_81)` is a FIELD of degree 54 -- maximal inertia, the best possible splitting for a lattice/module-SIS commitment. Both teeth: same conductor 81 is REDUCIBLE over BabyBear (2 factors) and M31 (6); same field F_KB SPLITS `X^(2^k)+1` completely for every k+1 <= 24, which is why the negacyclic lattice-PCS family is arithmetically dead on KoalaBear. ARITHMETIC POSSIBILITY ONLY -- the security bill is unpriced.
import Theory.ZkmlTensorOps  -- the zkML tensor-op vocabulary: an IxSignature over the intersection op set (scalar un/bin/cmp/select/fma, matmul-as-ordered-fold, ordered reduce, pure map, index read, shape-only reshaping), with a TOTAL denotation at an abstract ScalarOps carrier; NO op carries tensor data ([N3-converse]: constants are context entries, a commitment surface, never a payload). run = fold denAlg, so there is one program and N readings; run_transport (fold_rel, ONE induction, none at the use site) relates any two ScalarHom-related readings on EVERY trace; arith_transport does the same along a RingHom on the fragment TOp.arithmetic, whose complement -- div, pow, cmp, map, gather, dtype-changing cast -- IS the derived arithmetization bill; census_macs_eq_macAlg is the same collapse by fold_fusion for the cost reading. Teeth: a wrong cost algebra (matmul at m*n vs m*k*n), a wrong scalar reading (sub read as add), and the div gap exhibited on a pair of readings that agree on the arithmetic fragment. All witnesses kernel-decided; axiom footprints guarded.
import Theory.ZkmlMatmulSum  -- the foldl->Finset.sum BRIDGE every matmul statement waits on, in TWO NAMED STEPS so the boundary is visible: foldl_add_eq_listSum needs only ASSOCIATIVITY (AddMonoid), listSum_finRange_eq_sum is where the ORDER is discarded (AddCommMonoid -- Finset.sum over Fin k cannot be written without it, so that step has no counterexample, it has a missing typeclass). run_matmul_sum: the ordered fold of TOp.denote IS the contraction over a ring-shaped reading. The load-bearing property is ASSOCIATIVITY, not commutativity: IEEE-754 addition commutes and does not associate, and SatExample REFUTES the bridge on a real trace with a saturating add (denotation 5, Finset.sum 9, kernel-decided) plus an order-reversal tooth. Padding: padded_contraction + padded_matmul_table zero-extend to a DYADIC domain with the contraction unchanged -- so matmul needs NO new TOp constructor and NO non-dyadic MLE machinery (the build log's 4.5 fork resolves to neither branch); the pad is a COMMITMENT-layer obligation, not a denotational one.
import Theory.EvmFragment  -- EVM decompilation Stage 0, the semantics anchor: the five-opcode-kind fragment {PUSH1, CALLDATALOAD, ADD, MSTORE, RETURN} as a byte-level interpreter (byte-granular PC, real stack + 1024 check, byte memory, CALLDATALOAD zero-padding, implicit STOP), DIRECT statement — fidelity register is DIFFERENTIAL: five conformance vectors executed by a real EVM (anvil v1.7.1/revm) as kernel-decided named theorems, incl. wraparound ADD and a read past the calldata end; the byte codec is Theory.Bignum reversed (beBytes_inj + calldata-slicing lemmas). GAS-FREE: statements speak about executions the deployed EVM completes within gas.
import Theory.EvmResidual  -- EVM decompilation Stage 0, the residual + the UNTRUSTED decompiler: role-carrying context (which calldata word entered which wire) + intrinsically scoped add-expressions; decompile = a refusing symbolic stack machine over the same bytes (data-dependent offsets, STOP, foreign opcodes, non-unit memory shapes all REFUSED); the per-output TV pair — decompile fragmentCode = .ok fragmentResidual (kernel-computed) and fragment_faithful : ∀ cd, the machine run equals the residual's denotation, proved by rfl (the machine reduces away; that reduction IS the decompilation theorem). NO theorem quantifies over the decompiler's inputs — trust lives in the per-output pair only.
import Theory.ExceptionalSetLocalRing  -- exceptional sets (pairwise-UNIT differences: the sumcheck sampling set / lattice challenge set) over a LOCAL ring are exactly the sets on which the residue map is injective (iff, for any local hom into a field), so |A| ≤ |residue field| — the theorem-level ceiling that makes Z/2^k-style rings (residue F_2) useless for challenges and Galois rings GR(p^k, d) worth exactly p^d. Teeth on Mathlib's real ZMod 4: {0,1} exceptional, {0,2} not (2 is a non-unit; residues collide), ceiling 2 derived twice.
import Theory.CyclotomicExceptionalSet  -- the instance the joint-algebra question needs: over (ZMod n)[X]/(f) with p | n | p^e and f irreducible mod p (via AdjoinRoot, general), every fixed-weight set of root-sums is exceptional and |A_h| = C(deg f, h) for ANY monic f over ANY nontrivial commutative ring (modByMonic degree argument — (ZMod 4)[X] is not a domain); conductor 9 at ZMod 4 exhibited, conductor 6561 PROVED (ord_6561(2) = 4374 by kernel powMod), falsifier (ZMod 4)[X]/(X^2+1) where X − 1 is not a unit; the coefficient shift bound ‖X^m·v‖_∞ ≤ 2‖v‖_∞ for the Φ_{3^a} reduction.
import Theory.Confluence  -- the INDEPENDENCE logic: IConfluent over a join-semilattice, ONE name; I-confluence = Subtype.semilatticeSup's hypothesis, so the merge of lawful views IS their coproduct (merge_is_coproduct) and the converse is refuted at a 5-point lattice (subtype_lub_does_not_imply_iconfluent: HasBinaryCoproducts ∧ ¬ IConfluent); Guard classifier (monotone_free / bounded_breaks / bounded_forces_ordering); the constitution's own example as a real two-replica PN-counter (balance ≥ 0 linear but NOT confluent, value −3 computed). Residuals [CONFLUENCE-pred-dial] [CONFLUENCE-finality]
import Theory.ViewMerge  -- N6 at the poset shadow: partial views a SemilatticeSup, federation merge = the join = the colimit (binary_merge_is_colimit, finite_merge_is_colimit via isColimitOfIsLUB, chain_merge_is_colimit over any Preorder), strict upper bounds are not colimits; the overdraft pair of lawful views has NO colimit among lawful views (overdraft_pair_has_no_colimit) — "forces ordering" as a missing colimit. Residuals [N6-receipt-colimit] [N6-blocklace] [N6-cross-canonical]
import Theory.Finality  -- the ORDERING logic: the four-tier ladder (causal < ackThreshold < bft < constitutional) as a LinearOrder with ⊥ = causal, the cross-tier rule is the lattice join, FinalityRule + Config/Selector.tau_unified, commit_at_join_of_tiers (join dominates every leg AND canonicity only from the join-tier rule), no-downgrade with its tooth (downgrade_unreachable); tier1_requires_iconfluent links to Theory.Confluence, guardTier_sound over well-formed guards, naiveTier_unsound (a classifier sending bounded guards to tier 1 is refuted by the {0},{1} clash). Residuals [FINALITY-blocklace] [FINALITY-liveness]
import Theory.EpistemicConsensus  -- ATLAS §3 item 5: Frame/Knows/DistKnows and `verified X w₀`, a CONSTANT proposition over worlds — a discharged claim is known by every agent in every frame regardless of who is faulty (knows_verified_iff_discharged, knows_verified_frame_independent, honest_distributed_knows_discharged), an unrealizable claim by nobody (no_dist_knowledge_of_unrealizable); keystones on a two-world two-agent frame with a `p = 2·w` verifier so wrong witnesses exist. Residuals [EPISTEMIC-common] [EPISTEMIC-threshold] [EPISTEMIC-uc] [EPISTEMIC-adjudication]
import Theory.LaceMerge  -- the replica keyset merge over CausalVersionDag's AddressedEvent: ids_merge and the CRDT laws; the ancestor's anonymously-carried CrossCanonical gap DERIVED from the typed realizer slot BindingPremise (crossCanonical_of_binding, sameView_of_binding, merge_converges — replication converges on CONTENT); premise inhabited (injectiveScheme_binding, ideal digest) and refuted (lengthScheme_not_binding, crossCanonical_is_the_gap, merge_drops_at_collision) over one computable lawful codec. Residuals [LACE-frontier] [LACE-equivocation] [LACE-order] [LACE-catchup]
import Theory.RevocationConsensus  -- the negative lifecycle is consensus-bound and the positive one is not: revocation_needs_consensus (cross-vat sound + gated ⇒ Consensus) with its satisfiable and teeth poles, LocalCollect separated from Consensus on ONE decision, and dead_undecidable ported (deadness across the halting family is not computably decidable; resolved operationally by leases). Residuals [LIVENESS-lease] [LIVENESS-crossvat-cycle]
import Theory.PrivateTrace  -- the learn/infer-only interface as a state-machine fact, candidate-independent: a deterministic Machine S C O (step, out), an ADAPTIVE policy π : List O → C, trace M π s n. trace_eq_of_preserved (NO axioms): a relation preserved by EVERY allowed command and respected by out gives equal finite traces under every adaptive policy — the multi-step lift of Kernel/PrivateTurn.lean's one-step post_public_agrees (its hblind IS the preservation premise); randomized state needs a coupling version, not done. The byte toy as theorems: with output = high bit and update +128 only, the honest invariant is EQUAL HIGH BIT (highR; lowR fails hout — lowR_traces_differ), flip_trace_eq_of_highR, and the visible state genuinely changes (flip_trace_alternates). Falsifier for preservation: add the update +1 (twoMachine) — equal next answers (highR_two_out) yet not_highR_two_step (127 ↦ 128, 0 ↦ 1) and highR_two_traces_differ: certify the COMBINED learn-and-infer interface, not the two verbs independently. Recovery, sharp both ways: with arbitrary chosen offsets a binary-search policy recovers the byte in 8 observations (search_recovers, decide +kernel over all 256; exists_policy_recovers over all pairs), 7 are insufficient for that policy (search_seven_insufficient) and for EVERY policy (no_policy_recovers_seven, pigeonhole over List.Vector Bool 7); {+1,+128} alone cannot recover in 8 and is used only for the falsifier.
