/-
# Kernel.Job — a job is a cell with a law (COMPUTE.md §2)

The kernel has no job object. A job is one declared cell whose installed law is
`deploy/shell/templates/job/law.job` (rendered to `law.job.json`): the whole lifecycle of COMPUTE.md
§2.3 — order → claim → answer → truth → decide → close, with void and the stall — as one `Pred` over
`request/verb`, `request/subject`, the cell's fields, `clock/now` and one run slot. §2 below is that
JSON written out as a `Pred` term, one `def` per clause, placeholder `{X}` ↦ `p.X`; it is generated by
`scripts/gen-joblaw.py` (`--check` fails when the grammar, the JSON and §2 disagree).

**The run fact.** The truth edge needs the kernel's verdict that it re-executed the job's program:
K-RAN's atom `ran PROGRAM` (policy tag 14, clause 22), which reads the slot `run/program/<decimal
programId> ↦ 1` (`Pred.ranSlot`) that the controller projects only when the command carries a run claim
for PROGRAM that it re-executed on its own sample and whose product is exactly the command's writes.
The referee is K-EVAL's generic `Kernel.Run.checkRun E` with `E` resolved from the evaluator the
program record names (`Kernel.Run.resolve`); `programId` commits to that evaluator, so for a Nock
program the slot is projected only through `checkRun` at `Evaluator.nock`
(`Kernel.Run.nock.checkRun_sound`, `Kernel.Run.nock.no_accepted_of_output_mismatch`), and the
controller projects the evaluator beside it (`Pred.evaluatorSlot`). No write of any field supplies
that slot, so `caller_cannot_forge_truth` is a statement about who can make the kernel run the program.

**The money fact.** Fund, claim and close are the job-money receiver's turns (`Kernel.JobMoney`, C3): a
write that moves escrow or bond, claims or closes carries `authority/operation/job-money ↦ 1`
(`moneySlot`, clause 44), which only that receiver projects, beside the Book transfers it commits in the
same CAS. An order is born unfunded (escrow 0, bond 0, provider 0); the caller funds it in state 0.

**What the kernel supplies.** As in `Kernel.LawView` §2: the policy reads `old = project(pre, pre)` and
`new = project(pre, post)` (`DeclaredResourceProjection.scalarSlots`), behind the request slots and
`clock/now` (K-CLOCK, on resource invocations only — reads see no clock, so every clause but
management is guarded to writes). §5 reuses `LawView.view` and adds the run slot after it.

**Deviations from COMPUTE.md §2.2's field list.** `window` is not a field: `finalAt = clock/now + window`
is a three-slot relation that no atom states with a field-valued window, so the window is the law
constant `{WINDOW}` (two `leSlotsOff`, clauses 34–35) and the field would be a second copy of it.
Fields `bond` and `escrow` exist from birth (`bond = 0`), so `close` can require both `= 0` on every
path, void included.

**Counterexamples the poles caught** (§6, each a named theorem): a negated deadline atom passes
without a clock (`negated_timeout_fails_open`); `not (price <= 0)` passes on an absent price
(`negated_price_fails_open`).

**Every field, not only the declared ones (K-FIELD-CLOSURE).** `Pred` cannot say "no other field", so
the law alone admitted, on a closed job, a write that creates field 20. The kernel closes that: a job
cell is born declaring its sixteen fields (`jobFields`), and the scalar receiver refuses a write that
changes any other field by name, before the law runs (`Kernel.FieldClosure`). `kernelAdmits` is that
verdict; `no_double_settle` is over every field, and `closed_job_refuses_undeclared_field` names 20.
-/
import Pred.Core
import Pred.Leaf
import Kernel.LawView
import Kernel.FieldClosure

namespace Minidregg.Kernel.Job

open Minidregg.Pred (Pred State eval firstFailingLeaf ranSlot)
open Minidregg.Kernel.DeclaredResourceProjection (Values fieldName scalarSlots get)
open Minidregg.Kernel.LawView (ev_eq ev_le ev_memberOf ev_eqSlots ev_leSlots ev_leSlotsOff ev_not ev_all
  ev_any)
set_option autoImplicit false

/-! ## §1. The constants a job's law is instantiated at -/

/-- The `{UPPER}` placeholders of `law.job` (`job/fields.json` `placeholders`). -/
structure Params where
  CALLER : Int
  /-- The programId: `ran PROGRAM` reads `ranSlot PROGRAM`; field `program` holds it. -/
  PROGRAM : Nat
  WINDOW : Int
  NEG_WINDOW : Int

/-- The slot only the job-money receiver projects (`JobMoneyReceiver.moneySlots`). -/
def moneySlot : String := "authority/operation/job-money"

-- The field numbers (`job/fields.json`).
namespace F
def state : Nat := 0
def program : Nat := 1
def input : Nat := 2
def caller : Nat := 3
def callerAcct : Nat := 4
def price : Nat := 5
def claimBy : Nat := 6
def answerBy : Nat := 7
def escrow : Nat := 8
def provider : Nat := 9
def providerAcct : Nat := 10
def bond : Nat := 11
def output : Nat := 12
def steps : Nat := 13
def finalAt : Nat := 14
def truth : Nat := 15
/-- Every declared field. -/
def all : List Nat := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
end F

/-! ## §2. The law, literally (`deploy/shell/templates/job/law.job.json`, clauses 0–44) -/

section Law
set_option linter.unusedVariables false

/-- clause 0 -/
def jobClause0 (p : Params) : Pred :=
  Pred.any [
    .eq "request/verb" 1,
    .eq "request/verb" 2,
    Pred.all [
      .eq "request/verb" 3,
      .eq "request/subject" p.CALLER]]

/-- clause 1 -/
def jobClause1 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .memberOf "resource/field/0/after" [0, 1, 2, 3, 4, 5, 6]]

/-- clause 2 -/
def jobClause2 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/0/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
      .eq "resource/field/0/after" 0],
    Pred.all [
      .eq "resource/field/0/before" 0,
      .memberOf "resource/field/0/after" [1, 5]],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .memberOf "resource/field/0/after" [2, 3, 4]],
    Pred.all [
      .eq "resource/field/0/before" 2,
      .memberOf "resource/field/0/after" [3, 4]],
    Pred.all [
      .memberOf "resource/field/0/before" [3, 4, 5],
      .eq "resource/field/0/after" 6]]

/-- clause 3 -/
def jobClause3 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "request/subject" p.CALLER]

/-- clause 4 -/
def jobClause4 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "resource/field/3/after" p.CALLER]

/-- clause 5 -/
def jobClause5 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "resource/field/1/after" (p.PROGRAM : Int)]

/-- clause 6 -/
def jobClause6 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eqSlots "resource/field/2/after" "resource/field/2/after"]

/-- clause 7 -/
def jobClause7 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eqSlots "resource/field/4/after" "resource/field/4/after"]

/-- clause 8 -/
def jobClause8 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    Pred.all [
      .eqSlots "resource/field/5/after" "resource/field/5/after",
      .not (.le "resource/field/5/after" 0)]]

/-- clause 9 -/
def jobClause9 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .leSlots "clock/now" "resource/field/6/after"]

/-- clause 10 -/
def jobClause10 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .leSlots "resource/field/6/after" "resource/field/7/after"]

/-- clause 11 -/
def jobClause11 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "resource/field/8/after" 0]

/-- clause 12 -/
def jobClause12 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    Pred.all [
      .eq "resource/field/11/after" 0,
      .eq "resource/field/9/after" 0,
      .eq "resource/field/10/after" 0]]

/-- clause 13 -/
def jobClause13 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    Pred.all [
      .eq "resource/field/1/delta" 0,
      .eq "resource/field/2/delta" 0,
      .eq "resource/field/3/delta" 0,
      .eq "resource/field/4/delta" 0,
      .eq "resource/field/5/delta" 0,
      .eq "resource/field/6/delta" 0,
      .eq "resource/field/7/delta" 0]]

/-- clause 14 -/
def jobClause14 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    .eq "resource/field/8/delta" 0,
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 0,
      .eq "resource/field/8/before" 0,
      .eqSlots "resource/field/8/after" "resource/field/5/after"],
    Pred.all [
      .memberOf "resource/field/0/before" [3, 4, 5],
      .eq "resource/field/0/after" 6]]

/-- clause 15 -/
def jobClause15 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    .eq "resource/field/11/delta" 0,
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 1],
    Pred.all [
      .memberOf "resource/field/0/before" [3, 4, 5],
      .eq "resource/field/0/after" 6]]

/-- clause 16 -/
def jobClause16 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    .eq "resource/field/9/delta" 0,
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 1]]

/-- clause 17 -/
def jobClause17 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    .eq "resource/field/10/delta" 0,
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 1]]

/-- clause 18 -/
def jobClause18 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/12/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/12/before" "resource/field/12/before"),
      .not (.eqSlots "resource/field/12/after" "resource/field/12/after")],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .eq "resource/field/0/after" 2]]

/-- clause 19 -/
def jobClause19 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/13/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/13/before" "resource/field/13/before"),
      .not (.eqSlots "resource/field/13/after" "resource/field/13/after")],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .eq "resource/field/0/after" 2]]

/-- clause 20 -/
def jobClause20 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/14/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/14/before" "resource/field/14/before"),
      .not (.eqSlots "resource/field/14/after" "resource/field/14/after")],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .eq "resource/field/0/after" 2]]

/-- clause 21 -/
def jobClause21 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/15/delta" 0,
    .not (.eqSlots "resource/field/15/before" "resource/field/15/before")]

/-- clause 22 -/
def jobClause22 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .ran p.PROGRAM]

/-- clause 23 -/
def jobClause23 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    Pred.all [
      .memberOf "resource/field/0/before" [1, 2],
      .eq "resource/field/0/delta" 0]]

/-- clause 24 -/
def jobClause24 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .not (.eq "resource/field/0/before" 1),
    .eqSlots "request/subject" "resource/field/9/after"]

/-- clause 25 -/
def jobClause25 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .not (.eq "resource/field/0/before" 1),
    .leSlots "clock/now" "resource/field/7/after"]

/-- clause 26 -/
def jobClause26 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .not (.eq "resource/field/0/before" 2),
    .leSlots "clock/now" "resource/field/14/after"]

/-- clause 27 -/
def jobClause27 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .leSlots "clock/now" "resource/field/6/after"]

/-- clause 28 -/
def jobClause28 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .eqSlots "request/subject" "resource/field/9/after"]

/-- clause 29 -/
def jobClause29 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .eqSlots "resource/field/10/after" "resource/field/10/after"]

/-- clause 30 -/
def jobClause30 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .leSlots "resource/field/5/after" "resource/field/11/after"]

/-- clause 31 -/
def jobClause31 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .eqSlots "request/subject" "resource/field/9/after"]

/-- clause 32 -/
def jobClause32 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .leSlots "clock/now" "resource/field/7/after"]

/-- clause 33 -/
def jobClause33 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    Pred.all [
      .eqSlots "resource/field/12/after" "resource/field/12/after",
      .eqSlots "resource/field/13/after" "resource/field/13/after"]]

/-- clause 34 -/
def jobClause34 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .leSlotsOff "resource/field/14/after" "clock/now" p.WINDOW]

/-- clause 35 -/
def jobClause35 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .leSlotsOff "clock/now" "resource/field/14/after" p.NEG_WINDOW]

/-- clause 36 -/
def jobClause36 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .not (.eqSlots "resource/field/15/before" "resource/field/15/before")]

/-- clause 37 -/
def jobClause37 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 3]),
    .eqSlots "resource/field/15/before" "resource/field/15/before"]

/-- clause 38 -/
def jobClause38 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 2,
        .eq "resource/field/0/after" 3]),
    .eqSlots "resource/field/15/after" "resource/field/12/after",
    Pred.all [
      .not (.eqSlots "resource/field/15/after" "resource/field/15/after"),
      .leSlotsOff "resource/field/14/after" "clock/now" (-1)]]

/-- clause 39 -/
def jobClause39 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 2,
        .eq "resource/field/0/after" 4]),
    Pred.all [
      .eqSlots "resource/field/15/after" "resource/field/15/after",
      .eqSlots "resource/field/12/after" "resource/field/12/after",
      .not (.eqSlots "resource/field/15/after" "resource/field/12/after")]]

/-- clause 40 -/
def jobClause40 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 4]),
    Pred.all [
      .not (.eqSlots "resource/field/15/after" "resource/field/15/after"),
      .leSlotsOff "resource/field/7/after" "clock/now" (-1)]]

/-- clause 41 -/
def jobClause41 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 5]),
    .eq "request/subject" p.CALLER,
    .leSlotsOff "resource/field/6/after" "clock/now" (-1)]

/-- clause 42 -/
def jobClause42 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .memberOf "resource/field/0/before" [3, 4, 5],
        .eq "resource/field/0/after" 6]),
    .eq "resource/field/8/after" 0]

/-- clause 43 -/
def jobClause43 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .memberOf "resource/field/0/before" [3, 4, 5],
        .eq "resource/field/0/after" 6]),
    .eq "resource/field/11/after" 0]

/-- clause 44 -/
def jobClause44 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    Pred.all [
      .eq "resource/field/8/delta" 0,
      .eq "resource/field/11/delta" 0,
      .not (Pred.all [
          .eq "resource/field/0/before" 0,
          .eq "resource/field/0/after" 1]),
      .not (Pred.all [
          .memberOf "resource/field/0/before" [3, 4, 5],
          .eq "resource/field/0/after" 6])],
    .eq "authority/operation/job-money" 1]

/-- The clauses in the installed order. -/
def jobClauses (p : Params) : List Pred :=
  [jobClause0 p, jobClause1 p, jobClause2 p, jobClause3 p, jobClause4 p, jobClause5 p, jobClause6 p, jobClause7 p, jobClause8 p, jobClause9 p, jobClause10 p, jobClause11 p, jobClause12 p, jobClause13 p, jobClause14 p, jobClause15 p, jobClause16 p, jobClause17 p, jobClause18 p, jobClause19 p, jobClause20 p, jobClause21 p, jobClause22 p, jobClause23 p, jobClause24 p, jobClause25 p, jobClause26 p, jobClause27 p, jobClause28 p, jobClause29 p, jobClause30 p, jobClause31 p, jobClause32 p, jobClause33 p, jobClause34 p, jobClause35 p, jobClause36 p, jobClause37 p, jobClause38 p, jobClause39 p, jobClause40 p, jobClause41 p, jobClause42 p, jobClause43 p, jobClause44 p]

end Law

/-- The job law: `all` of its clauses, as installed. -/
def jobLaw (p : Params) : Pred := Pred.all (jobClauses p)

/-! ## §3. Reading the law -/

theorem job_clause {p : Params} {o n : State} (h : eval (jobLaw p) o n = true) {q : Pred}
    (hq : q ∈ jobClauses p) : eval q o n = true :=
  ev_all.mp h q hq

/-- `present s` (COMPUTE §2.3's `eqSlots s s`, §10 A6) holds exactly when the slot is present. -/
theorem present_iff {o n : State} {s : String} :
    eval (.eqSlots s s) o n = true ↔ ∃ x, n.get s = some x := by
  rw [ev_eqSlots]; simp

/-- A6 settled: a slot-pair atom on an absent slot is false. -/
theorem present_false_on_absent {o n : State} {s : String} (h : n.get s = none) :
    eval (.eqSlots s s) o n = false := by
  simp [eval, Minidregg.Pred.evalWith, h]

/-- K-RAN's atom reads its slot: `ran P` holds exactly when `ranSlot P ↦ 1` is projected. -/
theorem ev_ran {o n : State} {program : Nat} :
    eval (.ran program) o n = true ↔ n.get (ranSlot program) = some 1 := by
  simp [eval, Minidregg.Pred.evalWith]

/-! ## §4. Law-level theorems: every (old, new) pair the job law admits

Slot names are the projection's (`resource/field/{n}/{view}`; fields as in `F`). Every statement
below is about an admitted WRITE (`request/verb = 2`); a read changes no field. -/

section LawLevel
variable (p : Params) (o n : State)

/-- **`caller_cannot_forge_truth`.** An admitted write either leaves the truth slot alone (unchanged
when present, absent when absent) or carries the run verdict `ranSlot PROGRAM = 1`. The slot is the kernel's
projection of a re-execution it performed (K-RAN); no field write, by any subject, supplies it. -/
theorem caller_cannot_forge_truth (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) :
    n.get "resource/field/15/delta" = some 0 ∨
      (n.get "resource/field/15/before" = none ∧ n.get "resource/field/15/after" = none) ∨
      n.get (ranSlot p.PROGRAM) = some 1 := by
  have c21 := job_clause adm (q := jobClause21 p) (by simp [jobClauses])
  have c22 := job_clause adm (q := jobClause22 p) (by simp [jobClauses])
  simp only [jobClause21, jobClause22, ev_any, ev_all, ev_not, ev_eq, ev_ran, ev_eqSlots, List.mem_cons,
    List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, not_true_eq_false, false_or,
    forall_eq_or_imp, forall_eq, and_self] at c21 c22
  rcases c21 with c21 | c21
  · exact .inl c21
  · rcases c22 with c22 | c22
    · right; left
      refine ⟨Option.eq_none_iff_forall_ne_some.mpr fun x hx => c21 ⟨x, hx⟩, ?_⟩
      exact Option.eq_none_iff_forall_ne_some.mpr fun x hx =>
        c22 ⟨fun ⟨y, hy⟩ => c21 ⟨y, hy⟩, ⟨x, hx⟩⟩
    · exact .inr (.inr c22)

/-- **`truth_needs_ran`.** An admitted write that introduces the truth carries `ranSlot PROGRAM = 1`, is in
state 1 or 2, and moves no state. -/
theorem truth_needs_ran (adm : eval (jobLaw p) o n = true) (w : n.get "request/verb" = some 2)
    (fresh : n.get "resource/field/15/before" = none) (x : Int)
    (written : n.get "resource/field/15/after" = some x) :
    n.get (ranSlot p.PROGRAM) = some 1 ∧
      (n.get "resource/field/0/before" = some 1 ∨ n.get "resource/field/0/before" = some 2) ∧
      n.get "resource/field/0/delta" = some 0 := by
  have c22 := job_clause adm (q := jobClause22 p) (by simp [jobClauses])
  have c23 := job_clause adm (q := jobClause23 p) (by simp [jobClauses])
  simp only [jobClause22, jobClause23, ev_any, ev_all, ev_not, ev_eq, ev_ran, ev_eqSlots, ev_memberOf,
    List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, fresh, written,
    not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self, reduceCtorEq, exists_false,
    not_false_eq_true, Option.some.injEq, exists_eq'] at c22 c23
  obtain ⟨⟨s, hs, hmem⟩, hd⟩ := c23
  refine ⟨c22, ?_, hd⟩
  rcases hmem with rfl | rfl
  · exact .inl hs
  · exact .inr hs

/-- **`bond_slashed_iff_mismatch`.** A decide out of state 2 with the kernel's truth on the cell is
admitted into `slashed` (4) exactly when the truth disagrees with the posted output, and into `upheld`
(3) exactly when it agrees. The truth is the kernel's (`caller_cannot_forge_truth`). -/
theorem bond_slashed_iff_mismatch (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (from2 : n.get "resource/field/0/before" = some 2)
    (decided : n.get "resource/field/0/after" = some 3 ∨ n.get "resource/field/0/after" = some 4)
    (t : Int) (truth : n.get "resource/field/15/after" = some t) :
    n.get "resource/field/0/after" = some 4 ↔
      ∃ y, n.get "resource/field/12/after" = some y ∧ t ≠ y := by
  have c38 := job_clause adm (q := jobClause38 p) (by simp [jobClauses])
  have c39 := job_clause adm (q := jobClause39 p) (by simp [jobClauses])
  simp [jobClause38, jobClause39, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_leSlotsOff, w, from2,
    truth] at c38 c39
  rcases decided with d | d <;> simp [d] at c38 c39 ⊢
  · intro x hx
    rw [c38] at hx
    exact Option.some.inj hx
  · obtain ⟨⟨y, hy⟩, hne⟩ := c39
    exact ⟨y, hy, fun e => hne (by rw [e]; exact hy)⟩


/-- **The stall (`stall_forfeits_bond`), and the only two ways into `slashed`.** An admitted write into
state 4 came out of state 2 with the truth present and different from the output, or out of state 1
with no truth and `answerBy` strictly before `clock/now`. -/
theorem slashed_only_by_mismatch_or_stall (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (into4 : n.get "resource/field/0/after" = some 4)
    (from12 : n.get "resource/field/0/before" = some 1 ∨ n.get "resource/field/0/before" = some 2) :
    (n.get "resource/field/0/before" = some 2 ∧
      ∃ x y, n.get "resource/field/15/after" = some x ∧ n.get "resource/field/12/after" = some y ∧
        x ≠ y) ∨
    (n.get "resource/field/0/before" = some 1 ∧ n.get "resource/field/15/after" = none ∧
      ∃ a now, n.get "resource/field/7/after" = some a ∧ n.get "clock/now" = some now ∧
        a ≤ now + -1) := by
  have c39 := job_clause adm (q := jobClause39 p) (by simp [jobClauses])
  have c40 := job_clause adm (q := jobClause40 p) (by simp [jobClauses])
  rcases from12 with f | f
  · simp only [jobClause40, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_leSlotsOff,
      List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into4,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c40
    obtain ⟨hn, a, now, ha, hnow, hle⟩ := c40
    exact .inr ⟨f, Option.eq_none_iff_forall_ne_some.mpr fun x hx => hn ⟨x, hx⟩, a, now, ha, hnow, hle⟩
  · simp only [jobClause39, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, List.mem_cons,
      List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into4,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c39
    obtain ⟨⟨x, hx⟩, ⟨y, hy⟩, hne⟩ := c39
    refine .inl ⟨f, x, y, hx, hy, fun e => hne ⟨x, hx, e ▸ hy⟩⟩

/-- **Into `upheld`, per step.** An admitted write from state 1 or 2 into state 3 had the provider's
own run on the cell (from 1), or the truth equal to the output, or no truth and `finalAt` strictly
before `clock/now` (from 2). -/
theorem upheld_requires_match_or_timeout (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (into3 : n.get "resource/field/0/after" = some 3)
    (from12 : n.get "resource/field/0/before" = some 1 ∨ n.get "resource/field/0/before" = some 2) :
    (n.get "resource/field/0/before" = some 1 ∧ ∃ x, n.get "resource/field/15/before" = some x) ∨
    (n.get "resource/field/0/before" = some 2 ∧
      ∃ x, n.get "resource/field/15/after" = some x ∧ n.get "resource/field/12/after" = some x) ∨
    (n.get "resource/field/0/before" = some 2 ∧ n.get "resource/field/15/after" = none ∧
      ∃ f now, n.get "resource/field/14/after" = some f ∧ n.get "clock/now" = some now ∧
        f ≤ now + -1) := by
  have c37 := job_clause adm (q := jobClause37 p) (by simp [jobClauses])
  have c38 := job_clause adm (q := jobClause38 p) (by simp [jobClauses])
  rcases from12 with f | f
  · simp only [jobClause37, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, List.mem_cons,
      List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into3,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c37
    obtain ⟨x, hx⟩ := c37
    exact .inl ⟨f, x, hx⟩
  · simp only [jobClause38, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_leSlotsOff,
      List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into3,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c38
    rcases c38 with ⟨x, hx, hy⟩ | ⟨hn, g, now, hg, hnow, hle⟩
    · exact .inr (.inl ⟨f, x, hx, hy⟩)
    · exact .inr (.inr ⟨f, Option.eq_none_iff_forall_ne_some.mpr fun x hx => hn ⟨x, hx⟩,
        g, now, hg, hnow, hle⟩)

/-- **Closing pays out nothing the cell still holds**: an admitted write into state 6 from 3, 4 or 5
leaves `escrow = 0` and `bond = 0` (the pay-out legs are K-JOB-MONEY's, C3). -/
theorem close_empties_cell (adm : eval (jobLaw p) o n = true) (w : n.get "request/verb" = some 2)
    (s : Int) (from345 : n.get "resource/field/0/before" = some s) (hs : s = 3 ∨ s = 4 ∨ s = 5)
    (into6 : n.get "resource/field/0/after" = some 6) :
    n.get "resource/field/8/after" = some 0 ∧ n.get "resource/field/11/after" = some 0 := by
  have c42 := job_clause adm (q := jobClause42 p) (by simp [jobClauses])
  have c43 := job_clause adm (q := jobClause43 p) (by simp [jobClauses])
  simp only [jobClause42, jobClause43, ev_any, ev_all, ev_not, ev_eq, ev_memberOf, List.mem_cons,
    List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, from345, into6,
    not_true_eq_false, false_or, forall_eq_or_imp, forall_eq,
    Option.some.injEq, exists_eq_left'] at c42 c43
  rcases hs with rfl | rfl | rfl <;> simp_all

/-- **`no_double_settle`, per step (slot form).** An admitted write on a closed job (state 6 before)
keeps the state and leaves every declared field alone: unchanged where present, absent where absent. -/
theorem closed_step_frame (adm : eval (jobLaw p) o n = true) (w : n.get "request/verb" = some 2)
    (closed : n.get "resource/field/0/before" = some 6) :
    ∀ N ∈ F.all, n.get (fieldName N "delta") = some 0 ∨
      (n.get (fieldName N "before") = none ∧ n.get (fieldName N "after") = none) := by
  have c2 := job_clause adm (q := jobClause2 p) (by simp [jobClauses])
  have c13 := job_clause adm (q := jobClause13 p) (by simp [jobClauses])
  have c14 := job_clause adm (q := jobClause14 p) (by simp [jobClauses])
  have c15 := job_clause adm (q := jobClause15 p) (by simp [jobClauses])
  have c16 := job_clause adm (q := jobClause16 p) (by simp [jobClauses])
  have c17 := job_clause adm (q := jobClause17 p) (by simp [jobClauses])
  have c18 := job_clause adm (q := jobClause18 p) (by simp [jobClauses])
  have c19 := job_clause adm (q := jobClause19 p) (by simp [jobClauses])
  have c20 := job_clause adm (q := jobClause20 p) (by simp [jobClauses])
  have c21 := job_clause adm (q := jobClause21 p) (by simp [jobClauses])
  have c23 := job_clause adm (q := jobClause23 p) (by simp [jobClauses])
  simp [jobClause2, jobClause13, jobClause14, jobClause15, jobClause16, jobClause17, jobClause18,
    jobClause19, jobClause20, jobClause21, jobClause23, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots,
    ev_memberOf, w, closed] at c2 c13 c14 c15 c16 c17 c18 c19 c20 c21 c23
  have nn : ∀ x : Option Int, (∀ y, ¬ x = some y) → x = none :=
    fun x h => Option.eq_none_iff_forall_ne_some.mpr h
  intro N hN
  simp only [F.all, List.mem_cons, List.not_mem_nil, or_false] at hN
  rcases hN with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact .inl c2
  · exact .inl c13.1
  · exact .inl c13.2.1
  · exact .inl c13.2.2.1
  · exact .inl c13.2.2.2.1
  · exact .inl c13.2.2.2.2.1
  · exact .inl c13.2.2.2.2.2.1
  · exact .inl c13.2.2.2.2.2.2
  · exact .inl c14
  · exact .inl c16
  · exact .inl c17
  · exact .inl c15
  · rcases c18 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c19 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c20 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c21 with h | h
    · exact .inl h
    · exact .inr ⟨nn _ h, nn _ (c23 h)⟩

/-- **Money moves only by the receiver** (C3's `standInLaw_money_frozen_without_slot`, now on the job
law itself). After the order, an admitted write without `moneySlot ↦ 1` leaves escrow and bond
unchanged, claims nothing and closes nothing: fund, claim and settle are the job-money receiver's
turns, which commit the Book transfers in the same CAS. -/
theorem money_frozen_without_slot (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (s : Int) (born : n.get "resource/field/0/before" = some s)
    (noSlot : n.get moneySlot ≠ some 1) :
    n.get "resource/field/8/delta" = some 0 ∧ n.get "resource/field/11/delta" = some 0 ∧
      ¬ (s = 0 ∧ n.get "resource/field/0/after" = some 1) ∧
      ¬ ((s = 3 ∨ s = 4 ∨ s = 5) ∧ n.get "resource/field/0/after" = some 6) := by
  have c44 := job_clause adm (q := jobClause44 p) (by simp [jobClauses])
  simp only [jobClause44, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_memberOf,
    List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, born,
    not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self, Option.some.injEq,
    exists_eq', not_and] at c44
  unfold moneySlot at noSlot
  rcases c44 with ⟨e, b, cl, cs⟩ | m
  · refine ⟨e, b, fun ⟨h0, h1⟩ => ?_, fun ⟨h0, h1⟩ => ?_⟩
    · exact cl h0 h1
    · exact cs (by rcases h0 with rfl | rfl | rfl <;> simp) h1
  · exact absurd m noSlot

/-- **Escrow moves only on fund or close.** After the order, an admitted write that changes escrow is
the fund edge (open, escrow `0 → price`) or a close out of 3, 4 or 5. -/
theorem escrow_moves_only_on_fund_or_close (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (s : Int) (born : n.get "resource/field/0/before" = some s)
    (moved : n.get "resource/field/8/delta" ≠ some 0) :
    (s = 0 ∧ n.get "resource/field/0/after" = some 0 ∧ n.get "resource/field/8/before" = some 0 ∧
      ∃ x, n.get "resource/field/8/after" = some x ∧ n.get "resource/field/5/after" = some x) ∨
    ((s = 3 ∨ s = 4 ∨ s = 5) ∧ n.get "resource/field/0/after" = some 6) := by
  have c14 := job_clause adm (q := jobClause14 p) (by simp [jobClauses])
  simp only [jobClause14, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_memberOf,
    List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, born,
    not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self, Option.some.injEq,
    exists_eq'] at c14
  rcases c14 with d | ⟨h0, a0, e0, x, hx, hp⟩ | ⟨hs, a6⟩
  · exact absurd d moved
  · exact .inl ⟨h0, a0, e0, x, hx, hp⟩
  · exact .inr ⟨by omega, a6⟩

end LawLevel

/-! ## §5. The kernel's view, and histories -/

section View
open Minidregg.Kernel.LawView (Turn view request clockSlots)

/-- One write (or read) on a job cell: who, which verb, the clock, the run verdict the controller
projects (K-RAN; `none` when the command carries no run claim) and the post-state. -/
structure JobTurn where
  verb : Int
  subject : Int
  now : Option Int
  ran : Option Int
  /-- `moneySlot`'s value: `some 1` on the job-money receiver's turns (fund, claim, settle). -/
  money : Option Int
  post : Values

/-- The LawView turn with no joint participants. -/
def JobTurn.base (t : JobTurn) : Turn := ⟨t.verb, t.subject, t.now, [], t.post⟩

def ranSlots (p : Params) : Option Int → List (String × Int)
  | none => []
  | some v => [(ranSlot p.PROGRAM, v)]

def moneySlots : Option Int → List (String × Int)
  | none => []
  | some v => [(moneySlot, v)]

/-- The controller's slots after the view: the run slot (K-RAN) and the money slot (C3). -/
def extraSlots (p : Params) (t : JobTurn) : List (String × Int) := ranSlots p t.ran ++ moneySlots t.money

/-- The policy's view: `LawView.view` (request, fields, clock), then the run and money slots. -/
def jview (p : Params) (t : JobTurn) (pre post : Values) : State :=
  ⟨(view t.base pre post).slots ++ extraSlots p t⟩

/-- The law's verdict on a turn from `pre`. -/
def admits (p : Params) (pre : Values) (t : JobTurn) : Bool :=
  eval (jobLaw p) (jview p t pre pre) (jview p t pre t.post)

/-- The clause a refusal names (`Compiler.RefusalReason.LawLeaf`'s path), on the same views. -/
def refusalPath (p : Params) (pre : Values) (t : JobTurn) : Option (List Nat) :=
  firstFailingLeaf (jobLaw p) (jview p t pre pre) (jview p t pre t.post)

/-- The run slot is none of the declared fields' names. -/
def Params.Fresh (p : Params) : Prop :=
  ∀ N ∈ F.all, ∀ v ∈ ["before", "after", "delta"], ranSlot p.PROGRAM ≠ fieldName N v

/-- Nor is the money slot. -/
theorem money_fresh : ∀ N ∈ F.all, ∀ v ∈ ["before", "after", "delta"], moneySlot ≠ fieldName N v := by
  decide

theorem money_not_clock : moneySlot ≠ "clock/now" := by decide

instance (p : Params) : Decidable p.Fresh := by unfold Params.Fresh; infer_instance

theorem jget (p : Params) (t : JobTurn) (pre post : Values) (k : String) :
    (jview p t pre post).get k =
      ((view t.base pre post).get k).or ((State.mk (extraSlots p t)).get k) := by
  unfold jview State.get
  rw [List.find?_append]
  cases (view t.base pre post).slots.find? (fun q => q.1 == k) <;> rfl

theorem ran_get_ne (p : Params) (t : JobTurn) (k : String) (h : ranSlot p.PROGRAM ≠ k)
    (hm : moneySlot ≠ k) : (State.mk (extraSlots p t)).get k = none := by
  cases hr : t.ran <;> cases hmo : t.money <;>
    simp [extraSlots, ranSlots, moneySlots, State.get, hr, hmo, h, hm]

theorem jget_field (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) (v : String) (hv : v ∈ ["before", "after", "delta"]) :
    (jview p t pre post).get (fieldName N v) = (view t.base pre post).get (fieldName N v) := by
  rw [jget, ran_get_ne p _ _ (fr N hN v hv) (money_fresh N hN v hv)]
  cases (view t.base pre post).get (fieldName N v) <;> rfl

theorem jget_after (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) : (jview p t pre post).get (fieldName N "after") = get post N := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact Minidregg.Kernel.LawView.get_after _ _ _ _

theorem jget_before (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) : (jview p t pre post).get (fieldName N "before") = get pre N := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact Minidregg.Kernel.LawView.get_before _ _ _ _

theorem jget_delta (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) (o : Int) (hpre : get pre N = some o) :
    (jview p t pre post).get (fieldName N "delta") = (get post N).map (· - o) := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact Minidregg.Kernel.LawView.get_delta _ _ _ _ _ hpre

/-- The `delta` slot is absent when the pre-state lacks the field. -/
theorem view_delta_none (t : Turn) (pre post : Values) (N : Nat) (hpre : get pre N = none) :
    (view t pre post).get (fieldName N "delta") = none := by
  open Minidregg.Kernel.LawView in
  have hw : lastc "delta" = some 'r' ∨ lastc "delta" = some 'e' ∨ lastc "delta" = some 'a' :=
    .inr (.inr (by decide))
  open Minidregg.Kernel.LawView in
  have hreq := find_none (l := request t.verb t.subject) (k := fieldName N "delta")
    (fun q hq => request_ne_field hq N _ hw (by decide))
  open Minidregg.Kernel.LawView in
  have hbef := find_none (l := pre.map (fun p => (fieldName p.1 "before", p.2))) (k := fieldName N "delta")
    (fun q hq => by
      simp only [List.mem_map] at hq
      obtain ⟨p, -, rfl⟩ := hq
      exact ne_of_lastc (by rw [lastc_before, lastc_delta]; decide))
  open Minidregg.Kernel.LawView in
  have haft := find_none (l := post.map (fun p => (fieldName p.1 "after", p.2))) (k := fieldName N "delta")
    (fun q hq => by
      simp only [List.mem_map] at hq
      obtain ⟨p, -, rfl⟩ := hq
      exact ne_of_lastc (by rw [lastc_delta, lastc_after]; decide))
  open Minidregg.Kernel.LawView in
  have hdel := find_none (k := fieldName N "delta")
    (l := post.filterMap (fun p => (get pre p.1).map fun old => (fieldName p.1 "delta", p.2 - old)))
    (fun q hq => by
      simp only [List.mem_filterMap, Option.map_eq_some_iff] at hq
      obtain ⟨a, -, old, hold, rfl⟩ := hq
      intro e
      have : a.1 = N := fieldName_inj.mp e
      rw [this, hpre] at hold
      cases hold)
  open Minidregg.Kernel.LawView in
  have hpair := find_none (k := fieldName N "delta")
    (l := post.flatMap (fun a => post.filterMap fun b => do
        let oldA ← get pre a.1
        let oldB ← get pre b.1
        return (Minidregg.Kernel.DeclaredResourceProjection.pairName a.1 b.1, a.2 + b.2 - oldA - oldB)))
    (fun q hq => by
      obtain ⟨a, b, e⟩ := mem_pairs hq
      rw [e]; exact pairName_ne_fieldName a b N _)
  open Minidregg.Kernel.LawView in
  have hclock := find_none (k := fieldName N "delta") (l := clockSlots t.now)
    (fun q hq => clock_ne_field hq N _ hw (by decide))
  open Minidregg.Kernel.LawView in
  have hjoint := find_none (k := fieldName N "delta") (l := jointSlots t.joint)
    (fun q hq => joint_ne_field hq N _)
  open Minidregg.Kernel.LawView in
  simp only [view, state_get, scalarSlots_split, List.find?_append, hreq, hbef, haft, hdel, hpair,
    hclock, hjoint, Option.or_none, Option.map_none]

theorem jget_delta_none (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) (hpre : get pre N = none) :
    (jview p t pre post).get (fieldName N "delta") = none := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact view_delta_none _ _ _ _ hpre

theorem jget_verb (p : Params) (t : JobTurn) (pre post : Values) :
    (jview p t pre post).get "request/verb" = some t.verb := by
  rw [jget, Minidregg.Kernel.LawView.get_verb]; rfl

theorem jget_clock (p : Params) (fr : ranSlot p.PROGRAM ≠ "clock/now") (t : JobTurn) (pre post : Values) :
    (jview p t pre post).get "clock/now" = t.now := by
  rw [jget, Minidregg.Kernel.LawView.get_clock, ran_get_ne p _ _ fr money_not_clock, Option.or_none]; rfl

/-- A field the slot-pair frame leaves alone is unchanged in the store. -/
theorem frame_eq (p : Params) (fr : p.Fresh) (t : JobTurn) (pre : Values) (N : Nat) (hN : N ∈ F.all)
    (h : (jview p t pre t.post).get (fieldName N "delta") = some 0 ∨
      ((jview p t pre t.post).get (fieldName N "before") = none ∧
        (jview p t pre t.post).get (fieldName N "after") = none)) :
    get t.post N = get pre N := by
  rw [jget_before p fr t pre t.post N hN, jget_after p fr t pre t.post N hN] at h
  cases hp : get pre N with
  | none =>
    rcases h with h | h
    · rw [jget_delta_none p fr t pre t.post N hN hp] at h; cases h
    · exact h.2
  | some o =>
    rcases h with h | h
    · rw [jget_delta p fr t pre t.post N hN o hp] at h
      cases hq : get t.post N with
      | none => rw [hq] at h; cases h
      | some x => rw [hq] at h; simp at h; rw [show x = o by omega]
    · rw [hp] at h; cases h.1

/-- The job kind's declaration: a job cell is born declaring exactly its sixteen fields
(K-FIELD-CLOSURE; the cell holds none of them until the order creates them). -/
def jobFields : FieldClosure.FieldSet := .closed F.all

/-- The first field a turn changes that a job cell does not declare. The kernel refuses such a turn by
name (`DeclaredResourceScalar.Reject.undeclaredField`), at preparation, before the law runs; this is
the same function the receiver applies (`FieldClosure.check`), on the same field values. -/
def undeclared (pre : Values) (t : JobTurn) : Option Nat :=
  FieldClosure.firstUndeclared jobFields.covers pre t.post

/-- The kernel's verdict on a turn on a job cell: the field closure, then the law. -/
def kernelAdmits (p : Params) (pre : Values) (t : JobTurn) : Bool :=
  (undeclared pre t).isNone && admits p pre t

/-- Inside the declaration the kernel's verdict is the law's: the closure made nothing else stricter
or looser. -/
theorem kernelAdmits_inside (p : Params) (pre : Values) (t : JobTurn)
    (inside : undeclared pre t = none) : kernelAdmits p pre t = admits p pre t := by
  simp [kernelAdmits, inside]

/-- **`no_double_settle`.** On a closed job (state 6) a write the kernel admits changes NO field: the
law freezes every declared field (state 6 has no outgoing edge, and nothing a closed job holds moves
again), and the field closure refuses every other. -/
theorem no_double_settle (p : Params) (fr : p.Fresh) (pre : Values) (t : JobTurn)
    (adm : kernelAdmits p pre t = true) (w : t.verb = 2) (closed : get pre F.state = some 6) :
    ∀ N, get t.post N = get pre N := by
  simp only [kernelAdmits, Bool.and_eq_true, Option.isNone_iff_eq_none] at adm
  obtain ⟨inside, lawAdm⟩ := adm
  have w' : (jview p t pre t.post).get "request/verb" = some 2 := by rw [jget_verb, w]
  have c' : (jview p t pre t.post).get "resource/field/0/before" = some 6 := by
    rw [show "resource/field/0/before" = fieldName 0 "before" from rfl,
      jget_before p fr t pre t.post 0 (by decide)]
    exact closed
  intro N
  by_cases hN : N ∈ F.all
  · exact frame_eq p fr t pre N hN (closed_step_frame p _ _ lawAdm w' c' N hN)
  · by_contra changed
    have covered := (FieldClosure.firstUndeclared_none_iff _ _ _).mp inside N
      (fun same => changed same.symm)
    simp [jobFields, FieldClosure.FieldSet.covers, hN] at covered

/-- The state field after an admitted write that enters 3 from anything but 3 was 1 or 2. -/
theorem enters_upheld_from (p : Params) (fr : p.Fresh) (pre : Values) (t : JobTurn)
    (adm : admits p pre t = true) (w : t.verb = 2) (into3 : get t.post F.state = some 3)
    (was : get pre F.state ≠ some 3) : get pre F.state = some 1 ∨ get pre F.state = some 2 := by
  have c2 := job_clause adm (q := jobClause2 p) (by simp [jobClauses])
  have w' : (jview p t pre t.post).get "request/verb" = some 2 := by rw [jget_verb, w]
  have hb : (jview p t pre t.post).get "resource/field/0/before" = get pre 0 :=
    jget_before p fr t pre t.post 0 (by decide)
  have ha : (jview p t pre t.post).get "resource/field/0/after" = get t.post 0 :=
    jget_after p fr t pre t.post 0 (by decide)
  simp only [F.state] at into3 was ⊢
  simp [jobClause2, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_memberOf, w', hb, ha, into3] at c2
  cases hp : get pre 0 with
  | none =>
    have hd : (jview p t pre t.post).get "resource/field/0/delta" = none :=
      jget_delta_none p fr t pre t.post 0 (by decide) hp
    simp [hd, hp] at c2
  | some s =>
    have hd : (jview p t pre t.post).get "resource/field/0/delta" = (get t.post 0).map (· - s) :=
      jget_delta p fr t pre t.post 0 (by decide) s hp
    rw [hp] at was
    simp [hd, hp, into3] at c2
    simp only [Option.some.injEq, ne_eq] at was ⊢
    omega


/-- The (pre, turn) pairs of a log started at `v`. -/
def stepsOf : Values → List JobTurn → List (Values × JobTurn)
  | _, [] => []
  | v, t :: ts => (v, t) :: stepsOf t.post ts

def final : Values → List JobTurn → Values
  | v, [] => v
  | _, t :: ts => final t.post ts

/-- A job cell's write history: every step a write the law admits from the previous step's post
(`SheetLaw.Accepted`, over job turns). -/
def Accepted (p : Params) (v : Values) (ts : List JobTurn) : Prop :=
  ∀ s ∈ stepsOf v ts, s.2.verb = 2 ∧ admits p s.1 s.2 = true

theorem Accepted.tail {p : Params} {v : Values} {t : JobTurn} {ts : List JobTurn}
    (h : Accepted p v (t :: ts)) : Accepted p t.post ts :=
  fun s hs => h s (by simp [stepsOf, hs])

theorem Accepted.head {p : Params} {v : Values} {t : JobTurn} {ts : List JobTurn}
    (h : Accepted p v (t :: ts)) : t.verb = 2 ∧ admits p v t = true :=
  h (v, t) (by simp [stepsOf])

/-- Why a step entered `upheld` (COMPUTE §2.7 `settle_requires_match_or_timeout`'s disjuncts). -/
def UpheldBy (pre : Values) (t : JobTurn) : Prop :=
  (get pre F.state = some 1 ∧ ∃ x, get pre F.truth = some x) ∨
  (get pre F.state = some 2 ∧ ∃ x, get t.post F.truth = some x ∧ get t.post F.output = some x) ∨
  (get pre F.state = some 2 ∧ get t.post F.truth = none ∧
    ∃ f now, get t.post F.finalAt = some f ∧ t.now = some now ∧ f < now)

theorem upheld_by (p : Params) (fr : p.Fresh) (fc : ranSlot p.PROGRAM ≠ "clock/now") (pre : Values)
    (t : JobTurn) (adm : admits p pre t = true) (w : t.verb = 2) (into3 : get t.post F.state = some 3)
    (was : get pre F.state ≠ some 3) : UpheldBy pre t := by
  have from12 := enters_upheld_from p fr pre t adm w into3 was
  have w' : (jview p t pre t.post).get "request/verb" = some 2 := by rw [jget_verb, w]
  have g := fun N v (hN : N ∈ F.all) (hv : v ∈ ["before", "after", "delta"]) =>
    jget_field p fr t pre t.post N hN v hv
  have r := upheld_requires_match_or_timeout p _ _ adm w'
  rw [show "resource/field/0/after" = fieldName 0 "after" from rfl, jget_after p fr _ _ _ 0 (by decide),
    show "resource/field/0/before" = fieldName 0 "before" from rfl, jget_before p fr _ _ _ 0 (by decide),
    show "resource/field/15/before" = fieldName 15 "before" from rfl,
    jget_before p fr _ _ _ 15 (by decide),
    show "resource/field/15/after" = fieldName 15 "after" from rfl, jget_after p fr _ _ _ 15 (by decide),
    show "resource/field/12/after" = fieldName 12 "after" from rfl, jget_after p fr _ _ _ 12 (by decide),
    show "resource/field/14/after" = fieldName 14 "after" from rfl, jget_after p fr _ _ _ 14 (by decide),
    jget_clock p fc] at r
  have r := r into3 from12
  unfold UpheldBy
  rcases r with ⟨a, b⟩ | ⟨a, b⟩ | ⟨a, b, f, now, hf, hn, hle⟩
  · exact .inl ⟨a, b⟩
  · exact .inr (.inl ⟨a, b⟩)
  · exact .inr (.inr ⟨a, b, f, now, hf, hn, by omega⟩)

/-- Along an accepted history from a cell without state 3, a cell that reaches state 3 got there by a
step `UpheldBy` justifies. -/
theorem reached_upheld (p : Params) (fr : p.Fresh) (fc : ranSlot p.PROGRAM ≠ "clock/now") :
    ∀ (v : Values) (ts : List JobTurn), Accepted p v ts → get v F.state ≠ some 3 →
      get (final v ts) F.state = some 3 → ∃ s ∈ stepsOf v ts, UpheldBy s.1 s.2
  | v, [], _, was, now => absurd now was
  | v, t :: ts, acc, was, now => by
    obtain ⟨w, adm⟩ := acc.head
    by_cases h3 : get t.post F.state = some 3
    · exact ⟨(v, t), by simp [stepsOf], upheld_by p fr fc v t adm w h3 was⟩
    · obtain ⟨s, hs, hu⟩ := reached_upheld p fr fc t.post ts acc.tail h3 now
      exact ⟨s, by simp [stepsOf, hs], hu⟩

theorem stepsOf_prefix : ∀ (v : Values) (ts : List JobTurn) (s : Values × JobTurn),
    s ∈ stepsOf v ts → ∃ pre, s.1 = final v pre ∧ ∀ q ∈ stepsOf v pre, q ∈ stepsOf v ts
  | v, [], s, h => by simp [stepsOf] at h
  | v, t :: ts, s, h => by
    simp only [stepsOf, List.mem_cons] at h
    rcases h with rfl | h
    · exact ⟨[], rfl, by simp [stepsOf]⟩
    · obtain ⟨pre, e, sub⟩ := stepsOf_prefix t.post ts s h
      exact ⟨t :: pre, e, fun q hq => by
        simp only [stepsOf, List.mem_cons] at hq ⊢
        rcases hq with rfl | hq
        · exact .inl rfl
        · exact .inr (sub q hq)⟩

/-- **`settle_requires_match_or_timeout`.** In any accepted history of a job cell from a store with no
state (a fresh declared cell, `unborn`, before its order), every admitted close out of `upheld` (3 → 6) is preceded by the step that entered
`upheld`, and that step had the provider's own run on the cell (from 1), or the kernel's truth equal to
the posted output, or no truth and the clock past `finalAt` (from 2). -/
theorem settle_requires_match_or_timeout (p : Params) (fr : p.Fresh) (fc : ranSlot p.PROGRAM ≠ "clock/now")
    (v : Values) (unordered : get v F.state = none)
    (ts : List JobTurn) (acc : Accepted p v ts) (s : Values × JobTurn) (hs : s ∈ stepsOf v ts)
    (closesUpheld : get s.1 F.state = some 3) (_into6 : get s.2.post F.state = some 6) :
    ∃ u ∈ stepsOf v ts, UpheldBy u.1 u.2 := by
  obtain ⟨pre, e, sub⟩ := stepsOf_prefix v ts s hs
  have accPre : Accepted p v pre := fun q hq => acc q (sub q hq)
  rw [e] at closesUpheld
  obtain ⟨u, hu, by_⟩ := reached_upheld p fr fc v pre accPre (by rw [unordered]; simp) closesUpheld
  exact ⟨u, sub u hu, by_⟩

end View

/-! ## §6. Both poles of every edge, by `decide`, and the counterexamples -/

section Poles

/-- A job: caller 7, program 42, a 600-second window. -/
def demo : Params := ⟨7, 42, 600, -600⟩

/-- The run slot is K-RAN's spelling. -/
theorem demo_ranSlot : ranSlot demo.PROGRAM = "run/program/42" := by decide
theorem demo_fresh : demo.Fresh := by decide
theorem demo_ran_not_clock : ranSlot demo.PROGRAM ≠ "clock/now" := by decide

/-- A fresh declared cell, before the order: it is born holding no field, only its declaration
(`NativeHostGenesis.declaredCell`, K-FIELD-CLOSURE), so the order creates every field it writes. -/
def unborn : Values := []

/-- The order: price 100, claimBy 160, answerBy 700, born unfunded (escrow, provider, providerAcct and
bond 0); input 5; account 70. -/
def ordered : Values :=
  [(0, 0), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 0), (9, 0), (10, 0),
    (11, 0)]
/-- Funded by the caller's money turn: escrow = price. -/
def funded : Values :=
  [(0, 0), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 100), (9, 0), (10, 0),
    (11, 0)]
/-- Claimed by subject 8 (account 80) with bond 100. -/
def claimed : Values :=
  [(0, 1), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 100), (9, 8),
    (10, 80), (11, 100)]
/-- Answered at clock 300: output 77, 1345 steps, finalAt 900. -/
def answered : Values :=
  [(0, 2), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 100), (9, 8),
    (10, 80), (11, 100), (12, 77), (13, 1345), (14, 900)]
def withTruth (base : Values) (x : Int) : Values := base ++ [(15, x)]
def setState (base : Values) (s : Int) : Values := base.map fun q => if q.1 = 0 then (0, s) else q
def setField (base : Values) (n : Nat) (x : Int) : Values :=
  base.map fun q => if q.1 = n then (n, x) else q
def closedOf (base : Values) : Values := setField (setField (setState base 6) 8 0) 11 0

def w (subject : Int) (now : Int) (post : Values) : JobTurn := ⟨2, subject, some now, none, none, post⟩
def wRan (subject : Int) (now : Int) (post : Values) : JobTurn :=
  ⟨2, subject, some now, some 1, none, post⟩
/-- A job-money receiver turn (fund, claim, settle): the money slot projected. -/
def wMoney (subject : Int) (now : Int) (post : Values) : JobTurn :=
  ⟨2, subject, some now, none, some 1, post⟩

set_option maxRecDepth 20000

-- order (birth)
theorem order_admitted : admits demo unborn (w 7 100 ordered) = true := by decide
/-- A provider cannot order a job in the caller's name: clause 3. -/
theorem order_by_stranger_refused : refusalPath demo unborn (w 8 100 ordered) = some [3] := by decide
/-- An order without a clock is refused (clause 9 fails closed). -/
theorem order_without_clock_refused :
    refusalPath demo unborn ⟨2, 7, none, none, none, ordered⟩ = some [9] := by decide
/-- An order born claiming escrow nobody deposited: clause 11 (escrow is the fund turn's). -/
theorem order_prefunded_refused :
    refusalPath demo unborn (w 7 100 funded) = some [11] := by decide

-- fund (state 0, escrow 0 → price): the caller's money turn
theorem fund_admitted : admits demo ordered (wMoney 7 120 funded) = true := by decide
/-- **Money without the receiver.** The same fund as an ordinary write: clause 44. -/
theorem fund_without_receiver_refused :
    refusalPath demo ordered (w 7 120 funded) = some [44] := by decide
/-- A fund short of the price: clause 14. -/
theorem fund_short_refused :
    refusalPath demo ordered (wMoney 7 120 (setField ordered 8 50)) = some [14] := by decide

-- claim 0 → 1: the provider's money turn (the bond)
theorem claim_admitted : admits demo funded (wMoney 8 150 claimed) = true := by decide
/-- **A claim as an ordinary write** (a bond that no Book transfer backs): clause 44. -/
theorem claim_without_receiver_refused :
    refusalPath demo funded (w 8 150 claimed) = some [44] := by decide
/-- Past `claimBy`: clause 27. -/
theorem claim_late_refused : refusalPath demo funded (wMoney 8 200 claimed) = some [27] := by decide
/-- Claiming in another subject's name (subject 9 writes provider := 8): clause 28. -/
theorem claim_for_another_refused :
    refusalPath demo funded (wMoney 9 150 claimed) = some [28] := by decide
/-- A bond below the price: clause 30. -/
theorem claim_underbonded_refused :
    refusalPath demo funded (wMoney 8 150 (setField claimed 11 50)) = some [30] := by decide

-- answer 1 → 2
theorem answer_admitted : admits demo claimed (w 8 300 answered) = true := by decide
/-- The caller posting the answer: clause 31. -/
theorem answer_by_caller_refused : refusalPath demo claimed (w 7 300 answered) = some [31] := by decide
/-- After `answerBy`: clause 32. -/
theorem answer_late_refused :
    refusalPath demo claimed (w 8 800 (setField answered 14 1400)) = some [32] := by decide
/-- A `finalAt` that shortens the window: clause 35. -/
theorem answer_short_window_refused :
    refusalPath demo claimed (w 8 300 (setField answered 14 800)) = some [35] := by decide
/-- **Counterexample pole: a second answer.** Rewriting the output in state 2: clause 18. -/
theorem second_answer_refused :
    refusalPath demo answered (w 8 400 (setField answered 12 78)) = some [18] := by decide

-- truth (state unchanged)
/-- Anyone (subject 9) writes the truth in state 2 inside the window, with the run verdict. -/
theorem truth_admitted : admits demo answered (wRan 9 400 (withTruth answered 77)) = true := by decide
/-- **`caller_cannot_forge_truth`, both poles.** The caller writes a truth without the run verdict:
clause 22. -/
theorem forged_truth_refused :
    refusalPath demo answered (w 7 400 (withTruth answered 77)) = some [22] := by decide
/-- After the window: clause 26. -/
theorem truth_late_refused :
    refusalPath demo answered (wRan 9 1000 (withTruth answered 77)) = some [26] := by decide
/-- The synchronous path: the provider's own run in state 1. -/
theorem sync_truth_admitted : admits demo claimed (wRan 8 300 (withTruth claimed 77)) = true := by
  decide
/-- In state 1 only the provider runs it: clause 24. -/
theorem sync_truth_by_stranger_refused :
    refusalPath demo claimed (wRan 9 300 (withTruth claimed 77)) = some [24] := by decide
/-- A truth write that also moves the state (truth and decide in one turn): clause 23. -/
theorem truth_with_decide_refused :
    refusalPath demo answered (wRan 9 400 (setState (withTruth answered 77) 3)) = some [23] := by
  decide

-- decide → 3
theorem upheld_match_admitted :
    admits demo (withTruth answered 77) (w 9 500 (setState (withTruth answered 77) 3)) = true := by
  decide
/-- **Counterexample pole: the provider closing early.** Upheld from 2 with no truth inside the window:
clause 38. -/
theorem early_upheld_refused :
    refusalPath demo answered (w 8 500 (setState answered 3)) = some [38] := by decide
theorem upheld_timeout_admitted : admits demo answered (w 8 901 (setState answered 3)) = true := by
  decide
/-- Upheld against a mismatched truth: clause 38. -/
theorem upheld_mismatch_refused :
    refusalPath demo (withTruth answered 78) (w 8 500 (setState (withTruth answered 78) 3)) =
      some [38] := by decide
theorem upheld_sync_admitted :
    admits demo (withTruth claimed 77) (w 9 300 (setState (withTruth claimed 77) 3)) = true := by
  decide
/-- Upheld from 1 without the provider's run: clause 37. -/
theorem upheld_from1_without_run_refused :
    refusalPath demo claimed (w 8 300 (setState claimed 3)) = some [37] := by decide

-- decide → 4
theorem slashed_mismatch_admitted :
    admits demo (withTruth answered 78) (w 9 500 (setState (withTruth answered 78) 4)) = true := by
  decide
/-- Slashing a provider whose output the truth matches: clause 39. -/
theorem slashed_match_refused :
    refusalPath demo (withTruth answered 77) (w 7 500 (setState (withTruth answered 77) 4)) =
      some [39] := by decide
/-- The stall: no truth, past `answerBy`. -/
theorem stall_admitted : admits demo claimed (w 7 701 (setState claimed 4)) = true := by decide
/-- Slashing before `answerBy`: clause 40. -/
theorem stall_early_refused : refusalPath demo claimed (w 7 700 (setState claimed 4)) = some [40] := by
  decide

-- decide → 5
theorem void_by_caller_admitted : admits demo ordered (w 7 100 (setState ordered 5)) = true := by decide
/-- A stranger voiding before `claimBy`: clause 41. -/
theorem void_by_stranger_early_refused :
    refusalPath demo ordered (w 9 100 (setState ordered 5)) = some [41] := by decide
theorem void_by_stranger_late_admitted : admits demo ordered (w 9 161 (setState ordered 5)) = true := by
  decide

-- close → 6: the settle money turn
theorem close_upheld_admitted :
    admits demo (setState (withTruth answered 77) 3)
      (wMoney 9 600 (closedOf (withTruth answered 77))) = true := by decide
theorem close_slashed_admitted :
    admits demo (setState (withTruth answered 78) 4)
      (wMoney 9 600 (closedOf (withTruth answered 78))) = true := by decide
theorem close_void_admitted :
    admits demo (setState funded 5) (wMoney 9 600 (closedOf funded)) = true := by decide
/-- **A close as an ordinary write** (escrow and bond zeroed with no payout): clause 44. -/
theorem close_without_receiver_refused :
    refusalPath demo (setState (withTruth answered 77) 3)
      (w 9 600 (closedOf (withTruth answered 77))) = some [44] := by decide
/-- Closing with the bond still held: clause 43. -/
theorem close_holding_bond_refused :
    refusalPath demo (setState (withTruth answered 77) 3)
      (wMoney 9 600 (setField (closedOf (withTruth answered 77)) 11 100)) = some [43] := by decide
/-- Closing an undecided job (2 → 6): clause 2. -/
theorem close_undecided_refused :
    refusalPath demo answered (w 9 600 (closedOf answered)) = some [2] := by decide

-- closed (no_double_settle, poles)
/-- Re-opening a closed job: clause 2. -/
theorem reopen_refused :
    refusalPath demo (closedOf (withTruth answered 77))
      (w 9 700 (setState (closedOf (withTruth answered 77)) 3)) = some [2] := by decide
/-- A truth on a closed job, even with the run verdict: clause 23. -/
theorem truth_after_close_refused :
    refusalPath demo (closedOf answered) (wRan 9 700 (withTruth (closedOf answered) 77)) =
      some [23] := by decide
/-- **A closed job refuses a write that creates an undeclared field, by name**: the kernel names field
20 before the law runs (K-FIELD-CLOSURE; this replaces C1's `closed_job_admits_undeclared_field`). -/
theorem closed_job_refuses_undeclared_field :
    undeclared (closedOf answered) (w 9 700 (closedOf answered ++ [(20, 1)])) = some 20 ∧
      kernelAdmits demo (closedOf answered) (w 9 700 (closedOf answered ++ [(20, 1)])) = false := by
  decide

/-- The order creates only declared fields, so the kernel's verdict on it is the law's. -/
theorem order_inside_declaration : undeclared unborn (w 7 100 ordered) = none := by decide

-- management (clause 0)
/-- The caller delegates (verb 3; a non-write sees no field or clock slot). -/
theorem delegate_by_caller_admitted : admits demo ordered ⟨3, 7, none, none, none, ordered⟩ = true := by
  decide
theorem delegate_by_provider_refused :
    refusalPath demo ordered ⟨3, 8, none, none, none, ordered⟩ = some [0] := by decide
/-- **Nobody installs a new law on a live job** — not even the caller: clause 0. -/
theorem install_by_caller_refused :
    refusalPath demo claimed ⟨4, 7, none, none, none, claimed⟩ = some [0] := by decide
/-- **Nor revokes**: a revoke after claim would cut the bonded provider off and force the stall. -/
theorem revoke_by_caller_refused :
    refusalPath demo claimed ⟨5, 7, none, none, none, claimed⟩ = some [0] := by decide
/-- A read by anyone is judged only by management. -/
theorem read_admitted : admits demo claimed ⟨1, 9, none, none, none, claimed⟩ = true := by decide

-- the counterexamples to the wrong spellings
/-- **Counterexample: a negated deadline passes without a clock.** `not (leSlots clock/now finalAt)`
("now > finalAt") is TRUE on a step that has no `clock/now`, so a law written that way would let the
provider take `upheld` by timeout on a clockless write; clause 38's positive `leSlotsOff finalAt
clock/now -1` refuses it (`early_upheld_refused` is the clocked pole). -/
theorem negated_timeout_fails_open :
    eval (.not (.leSlots "clock/now" "resource/field/14/after"))
      (jview demo ⟨2, 8, none, none, none, setState answered 3⟩ answered answered)
      (jview demo ⟨2, 8, none, none, none, setState answered 3⟩ answered (setState answered 3)) = true ∧
    refusalPath demo answered ⟨2, 8, none, none, none, setState answered 3⟩ = some [38] := by decide
/-- **Counterexample: `not (price <= 0)` passes on an absent price**; clause 8's presence conjunct
refuses the priceless order. -/
theorem negated_price_fails_open :
    eval (.not (.le "resource/field/5/after" 0))
      (jview demo (w 7 100 (ordered.filter (·.1 ≠ 5))) unborn unborn)
      (jview demo (w 7 100 (ordered.filter (·.1 ≠ 5))) unborn (ordered.filter (·.1 ≠ 5))) = true ∧
    refusalPath demo unborn (w 7 100 (ordered.filter (·.1 ≠ 5))) = some [8] := by decide

end Poles

/-! ## §7. Axiom pins -/

-- Pins re-read on merging into the K-HASHEQ line (sealed-market): `Pred.eval` reaches the Keccak-f[1600]
-- sponge since K-HASHEQ (`[propext, Quot.sound]`), so statements that mention `eval` gain `Quot.sound`.
-- It is the closure of a definition, not a step of any proof here; `Classical.choice` stays out.
/-- info: 'Minidregg.Kernel.Job.job_clause' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.job_clause
/-- info: 'Minidregg.Kernel.Job.present_iff' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.present_iff
/-- info: 'Minidregg.Kernel.Job.present_false_on_absent' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.present_false_on_absent
/-- info: 'Minidregg.Kernel.Job.caller_cannot_forge_truth' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.caller_cannot_forge_truth
/-- info: 'Minidregg.Kernel.Job.truth_needs_ran' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_needs_ran
/-- info: 'Minidregg.Kernel.Job.bond_slashed_iff_mismatch' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.bond_slashed_iff_mismatch
/-- info: 'Minidregg.Kernel.Job.slashed_only_by_mismatch_or_stall' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.slashed_only_by_mismatch_or_stall
/-- info: 'Minidregg.Kernel.Job.upheld_requires_match_or_timeout' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_requires_match_or_timeout
/-- info: 'Minidregg.Kernel.Job.close_empties_cell' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_empties_cell
/-- info: 'Minidregg.Kernel.Job.ev_ran' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.ev_ran
/-- info: 'Minidregg.Kernel.Job.money_frozen_without_slot' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.money_frozen_without_slot
/-- info: 'Minidregg.Kernel.Job.escrow_moves_only_on_fund_or_close' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.escrow_moves_only_on_fund_or_close
/-- info: 'Minidregg.Kernel.Job.money_fresh' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.money_fresh
/-- info: 'Minidregg.Kernel.Job.money_not_clock' does not depend on any axioms -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.money_not_clock
/-- info: 'Minidregg.Kernel.Job.closed_step_frame' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.closed_step_frame
/-- info: 'Minidregg.Kernel.Job.jget' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget
/-- info: 'Minidregg.Kernel.Job.ran_get_ne' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.ran_get_ne
/-- info: 'Minidregg.Kernel.Job.jget_field' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_field
/-- info: 'Minidregg.Kernel.Job.jget_after' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_after
/-- info: 'Minidregg.Kernel.Job.jget_before' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_before
/-- info: 'Minidregg.Kernel.Job.jget_delta' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_delta
/-- info: 'Minidregg.Kernel.Job.view_delta_none' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.view_delta_none
/-- info: 'Minidregg.Kernel.Job.jget_delta_none' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_delta_none
/-- info: 'Minidregg.Kernel.Job.jget_verb' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_verb
/-- info: 'Minidregg.Kernel.Job.jget_clock' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_clock
/-- info: 'Minidregg.Kernel.Job.frame_eq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.frame_eq
/-- info: 'Minidregg.Kernel.Job.no_double_settle' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.no_double_settle
/-- info: 'Minidregg.Kernel.Job.enters_upheld_from' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.enters_upheld_from
/-- info: 'Minidregg.Kernel.Job.Accepted.tail' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.Accepted.tail
/-- info: 'Minidregg.Kernel.Job.Accepted.head' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.Accepted.head
/-- info: 'Minidregg.Kernel.Job.upheld_by' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_by
/-- info: 'Minidregg.Kernel.Job.reached_upheld' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.reached_upheld
/-- info: 'Minidregg.Kernel.Job.stepsOf_prefix' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.stepsOf_prefix
/-- info: 'Minidregg.Kernel.Job.settle_requires_match_or_timeout' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.settle_requires_match_or_timeout
/-- info: 'Minidregg.Kernel.Job.demo_ranSlot' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.demo_ranSlot
/-- info: 'Minidregg.Kernel.Job.demo_fresh' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.demo_fresh
/-- info: 'Minidregg.Kernel.Job.order_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_admitted
/-- info: 'Minidregg.Kernel.Job.order_by_stranger_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_by_stranger_refused
/-- info: 'Minidregg.Kernel.Job.order_without_clock_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_without_clock_refused
/-- info: 'Minidregg.Kernel.Job.order_prefunded_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_prefunded_refused
/-- info: 'Minidregg.Kernel.Job.fund_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.fund_admitted
/-- info: 'Minidregg.Kernel.Job.fund_without_receiver_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.fund_without_receiver_refused
/-- info: 'Minidregg.Kernel.Job.fund_short_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.fund_short_refused
/-- info: 'Minidregg.Kernel.Job.claim_without_receiver_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_without_receiver_refused
/-- info: 'Minidregg.Kernel.Job.close_without_receiver_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_without_receiver_refused
/-- info: 'Minidregg.Kernel.Job.claim_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_admitted
/-- info: 'Minidregg.Kernel.Job.claim_late_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_late_refused
/-- info: 'Minidregg.Kernel.Job.claim_for_another_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_for_another_refused
/-- info: 'Minidregg.Kernel.Job.claim_underbonded_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_underbonded_refused
/-- info: 'Minidregg.Kernel.Job.answer_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_admitted
/-- info: 'Minidregg.Kernel.Job.answer_by_caller_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_by_caller_refused
/-- info: 'Minidregg.Kernel.Job.answer_late_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_late_refused
/-- info: 'Minidregg.Kernel.Job.answer_short_window_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_short_window_refused
/-- info: 'Minidregg.Kernel.Job.second_answer_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.second_answer_refused
/-- info: 'Minidregg.Kernel.Job.truth_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_admitted
/-- info: 'Minidregg.Kernel.Job.forged_truth_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.forged_truth_refused
/-- info: 'Minidregg.Kernel.Job.truth_late_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_late_refused
/-- info: 'Minidregg.Kernel.Job.sync_truth_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.sync_truth_admitted
/-- info: 'Minidregg.Kernel.Job.sync_truth_by_stranger_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.sync_truth_by_stranger_refused
/-- info: 'Minidregg.Kernel.Job.truth_with_decide_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_with_decide_refused
/-- info: 'Minidregg.Kernel.Job.upheld_match_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_match_admitted
/-- info: 'Minidregg.Kernel.Job.early_upheld_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.early_upheld_refused
/-- info: 'Minidregg.Kernel.Job.upheld_timeout_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_timeout_admitted
/-- info: 'Minidregg.Kernel.Job.upheld_mismatch_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_mismatch_refused
/-- info: 'Minidregg.Kernel.Job.upheld_sync_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_sync_admitted
/-- info: 'Minidregg.Kernel.Job.upheld_from1_without_run_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_from1_without_run_refused
/-- info: 'Minidregg.Kernel.Job.slashed_mismatch_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.slashed_mismatch_admitted
/-- info: 'Minidregg.Kernel.Job.slashed_match_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.slashed_match_refused
/-- info: 'Minidregg.Kernel.Job.stall_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.stall_admitted
/-- info: 'Minidregg.Kernel.Job.stall_early_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.stall_early_refused
/-- info: 'Minidregg.Kernel.Job.void_by_caller_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.void_by_caller_admitted
/-- info: 'Minidregg.Kernel.Job.void_by_stranger_early_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.void_by_stranger_early_refused
/-- info: 'Minidregg.Kernel.Job.void_by_stranger_late_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.void_by_stranger_late_admitted
/-- info: 'Minidregg.Kernel.Job.close_upheld_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_upheld_admitted
/-- info: 'Minidregg.Kernel.Job.close_slashed_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_slashed_admitted
/-- info: 'Minidregg.Kernel.Job.close_void_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_void_admitted
/-- info: 'Minidregg.Kernel.Job.close_holding_bond_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_holding_bond_refused
/-- info: 'Minidregg.Kernel.Job.close_undecided_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_undecided_refused
/-- info: 'Minidregg.Kernel.Job.reopen_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.reopen_refused
/-- info: 'Minidregg.Kernel.Job.truth_after_close_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_after_close_refused
/-- info: 'Minidregg.Kernel.Job.closed_job_refuses_undeclared_field' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.closed_job_refuses_undeclared_field
/-- info: 'Minidregg.Kernel.Job.order_inside_declaration' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_inside_declaration
/-- info: 'Minidregg.Kernel.Job.kernelAdmits_inside' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.kernelAdmits_inside
/-- info: 'Minidregg.Kernel.Job.delegate_by_caller_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.delegate_by_caller_admitted
/-- info: 'Minidregg.Kernel.Job.delegate_by_provider_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.delegate_by_provider_refused
/-- info: 'Minidregg.Kernel.Job.install_by_caller_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.install_by_caller_refused
/-- info: 'Minidregg.Kernel.Job.revoke_by_caller_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.revoke_by_caller_refused
/-- info: 'Minidregg.Kernel.Job.read_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.read_admitted
/-- info: 'Minidregg.Kernel.Job.negated_timeout_fails_open' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.negated_timeout_fails_open
/-- info: 'Minidregg.Kernel.Job.negated_price_fails_open' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.negated_price_fails_open

/-- info: 'Minidregg.Kernel.Job.demo_ran_not_clock' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.demo_ran_not_clock

end Minidregg.Kernel.Job
