/-
# Kernel.Job — a job is a cell with a law (COMPUTE.md §2)

The kernel has no job object. A job is one declared cell whose installed law is
`deploy/shell/templates/job/law.job` (rendered to `law.job.json`): the whole lifecycle of COMPUTE.md
§2.3 — order → claim → answer → truth → decide → close, with void and the stall — as one `Pred` over
`request/verb`, `request/subject`, the cell's fields, `clock/now` and one run slot. §2 below is that
JSON written out as a `Pred` term, one `def` per clause, placeholder `{X}` ↦ `p.X`; it is generated by
`scripts/gen-joblaw.py` (`--check` fails when the grammar, the JSON and §2 disagree).

**The run fact.** The truth edge needs the kernel's verdict that it re-executed the job's program:
K-RAN's atom `ran PROGRAM` (policy tag 14), which reads the controller-projected slot
`run/program/<decimal programId> ↦ 1` (`Pred.ranSlot`, planning/nock/k-ran.md:61;
`lowerA_ran_eq : lowerA (.ran P) = lowerA (.eq (ranSlot P) 1)`). This tree does not have K-RAN, so the
law spells it `eq {RAN_SLOT} 1` and the slot is a parameter: on a tree with K-RAN the integrator binds
`RAN_SLOT := run/program/{PROGRAM}` (`ranSlot` below; the poles use exactly that spelling), and may
replace the atom with `.ran p.PROGRAM`, which lowers to the same circuit. Nothing here assumes who
projects the slot: `caller_cannot_forge_truth` is stated over the slot.

**What the kernel supplies.** As in `Theory.SheetLaw` §6: the policy reads `old = project(pre, pre)` and
`new = project(pre, post)` (`DeclaredResourceProjection.scalarSlots`), behind the request slots and
`clock/now` (K-CLOCK, on resource invocations only — reads see no clock, so every clause but
management is guarded to writes). §5 reuses `SheetLaw.view` and adds the run slot after it.

**Deviations from COMPUTE.md §2.2's field list.** `window` is not a field: `finalAt = clock/now + window`
is a three-slot relation that no atom states with a field-valued window, so the window is the law
constant `{WINDOW}` (two `leSlotsOff`, clauses 34–35) and the field would be a second copy of it.
Fields `bond` and `escrow` exist from birth (`bond = 0`), so `close` can require both `= 0` on every
path, void included.

**Counterexamples the poles caught** (§6, each a named theorem): a negated deadline atom passes
without a clock (`negated_timeout_fails_open`); `not (price <= 0)` passes on an absent price
(`negated_price_fails_open`); and a closed job still admits a write that creates an UNDECLARED field
(`closed_job_admits_undeclared_field`) — `Pred` cannot say "no other field", so `no_double_settle` is
over the sixteen declared fields only; closing it is a kernel item (a declared kind's field set).
-/
import Pred.Core
import Pred.Leaf
import Theory.SheetLaw

namespace Minidregg.Kernel.Job

open Minidregg.Pred (Pred State eval firstFailingLeaf)
open Minidregg.Kernel.DeclaredResourceProjection (Values fieldName scalarSlots get)
open Minidregg.Theory.SheetLaw (ev_eq ev_le ev_memberOf ev_eqSlots ev_leSlots ev_leSlotsOff ev_not ev_all
  ev_any)
set_option autoImplicit false

/-! ## §1. The constants a job's law is instantiated at -/

/-- The `{UPPER}` placeholders of `law.job` (`job/fields.json` `placeholders`). -/
structure Params where
  CALLER : Int
  PROGRAM : Int
  WINDOW : Int
  NEG_WINDOW : Int
  RAN_SLOT : String

/-- K-RAN's run slot for a program (`Pred.ranSlot` on the `n11` line, k-ran.md:61). -/
def ranSlot (program : Int) : String := s!"run/program/{program}"

-- The field numbers (`job/fields.json`).
namespace F
def state : Nat := 0
def program : Nat := 1
def input : Nat := 2
def caller : Nat := 3
def callerAcct : Nat := 4
def price : Nat := 5
def claimBy : Nat := 6
def answerBy : Nat := 7
def escrow : Nat := 8
def provider : Nat := 9
def providerAcct : Nat := 10
def bond : Nat := 11
def output : Nat := 12
def steps : Nat := 13
def finalAt : Nat := 14
def truth : Nat := 15
/-- Every declared field. -/
def all : List Nat := [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
end F

/-! ## §2. The law, literally (`deploy/shell/templates/job/law.job.json`, clauses 0–43) -/

section Law
set_option linter.unusedVariables false

/-- clause 0 -/
def jobClause0 (p : Params) : Pred :=
  Pred.any [
    .eq "request/verb" 1,
    .eq "request/verb" 2,
    Pred.all [
      .eq "request/verb" 3,
      .eq "request/subject" p.CALLER]]

/-- clause 1 -/
def jobClause1 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .memberOf "resource/field/0/after" [0, 1, 2, 3, 4, 5, 6]]

/-- clause 2 -/
def jobClause2 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/0/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
      .eq "resource/field/0/after" 0],
    Pred.all [
      .eq "resource/field/0/before" 0,
      .memberOf "resource/field/0/after" [1, 5]],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .memberOf "resource/field/0/after" [2, 3, 4]],
    Pred.all [
      .eq "resource/field/0/before" 2,
      .memberOf "resource/field/0/after" [3, 4]],
    Pred.all [
      .memberOf "resource/field/0/before" [3, 4, 5],
      .eq "resource/field/0/after" 6]]

/-- clause 3 -/
def jobClause3 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "request/subject" p.CALLER]

/-- clause 4 -/
def jobClause4 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "resource/field/3/after" p.CALLER]

/-- clause 5 -/
def jobClause5 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "resource/field/1/after" p.PROGRAM]

/-- clause 6 -/
def jobClause6 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eqSlots "resource/field/2/after" "resource/field/2/after"]

/-- clause 7 -/
def jobClause7 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eqSlots "resource/field/4/after" "resource/field/4/after"]

/-- clause 8 -/
def jobClause8 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    Pred.all [
      .eqSlots "resource/field/5/after" "resource/field/5/after",
      .not (.le "resource/field/5/after" 0)]]

/-- clause 9 -/
def jobClause9 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .leSlots "clock/now" "resource/field/6/after"]

/-- clause 10 -/
def jobClause10 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .leSlots "resource/field/6/after" "resource/field/7/after"]

/-- clause 11 -/
def jobClause11 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eqSlots "resource/field/8/after" "resource/field/5/after"]

/-- clause 12 -/
def jobClause12 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eqSlots "resource/field/0/before" "resource/field/0/before",
    .eq "resource/field/11/after" 0]

/-- clause 13 -/
def jobClause13 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    Pred.all [
      .eq "resource/field/1/delta" 0,
      .eq "resource/field/2/delta" 0,
      .eq "resource/field/3/delta" 0,
      .eq "resource/field/4/delta" 0,
      .eq "resource/field/5/delta" 0,
      .eq "resource/field/6/delta" 0,
      .eq "resource/field/7/delta" 0]]

/-- clause 14 -/
def jobClause14 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    .eq "resource/field/8/delta" 0,
    Pred.all [
      .memberOf "resource/field/0/before" [3, 4, 5],
      .eq "resource/field/0/after" 6]]

/-- clause 15 -/
def jobClause15 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (.eqSlots "resource/field/0/before" "resource/field/0/before"),
    .eq "resource/field/11/delta" 0,
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 1],
    Pred.all [
      .memberOf "resource/field/0/before" [3, 4, 5],
      .eq "resource/field/0/after" 6]]

/-- clause 16 -/
def jobClause16 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/9/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/9/before" "resource/field/9/before"),
      .not (.eqSlots "resource/field/9/after" "resource/field/9/after")],
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 1]]

/-- clause 17 -/
def jobClause17 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/10/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/10/before" "resource/field/10/before"),
      .not (.eqSlots "resource/field/10/after" "resource/field/10/after")],
    Pred.all [
      .eq "resource/field/0/before" 0,
      .eq "resource/field/0/after" 1]]

/-- clause 18 -/
def jobClause18 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/12/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/12/before" "resource/field/12/before"),
      .not (.eqSlots "resource/field/12/after" "resource/field/12/after")],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .eq "resource/field/0/after" 2]]

/-- clause 19 -/
def jobClause19 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/13/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/13/before" "resource/field/13/before"),
      .not (.eqSlots "resource/field/13/after" "resource/field/13/after")],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .eq "resource/field/0/after" 2]]

/-- clause 20 -/
def jobClause20 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/14/delta" 0,
    Pred.all [
      .not (.eqSlots "resource/field/14/before" "resource/field/14/before"),
      .not (.eqSlots "resource/field/14/after" "resource/field/14/after")],
    Pred.all [
      .eq "resource/field/0/before" 1,
      .eq "resource/field/0/after" 2]]

/-- clause 21 -/
def jobClause21 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .eq "resource/field/15/delta" 0,
    .not (.eqSlots "resource/field/15/before" "resource/field/15/before")]

/-- clause 22 -/
def jobClause22 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .eq p.RAN_SLOT 1]

/-- clause 23 -/
def jobClause23 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    Pred.all [
      .memberOf "resource/field/0/before" [1, 2],
      .eq "resource/field/0/delta" 0]]

/-- clause 24 -/
def jobClause24 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .not (.eq "resource/field/0/before" 1),
    .eqSlots "request/subject" "resource/field/9/after"]

/-- clause 25 -/
def jobClause25 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .not (.eq "resource/field/0/before" 1),
    .leSlots "clock/now" "resource/field/7/after"]

/-- clause 26 -/
def jobClause26 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .not (.eqSlots "resource/field/15/before" "resource/field/15/before"),
        .eqSlots "resource/field/15/after" "resource/field/15/after"]),
    .not (.eq "resource/field/0/before" 2),
    .leSlots "clock/now" "resource/field/14/after"]

/-- clause 27 -/
def jobClause27 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .leSlots "clock/now" "resource/field/6/after"]

/-- clause 28 -/
def jobClause28 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .eqSlots "request/subject" "resource/field/9/after"]

/-- clause 29 -/
def jobClause29 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .eqSlots "resource/field/10/after" "resource/field/10/after"]

/-- clause 30 -/
def jobClause30 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 1]),
    .leSlots "resource/field/5/after" "resource/field/11/after"]

/-- clause 31 -/
def jobClause31 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .eqSlots "request/subject" "resource/field/9/after"]

/-- clause 32 -/
def jobClause32 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .leSlots "clock/now" "resource/field/7/after"]

/-- clause 33 -/
def jobClause33 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    Pred.all [
      .eqSlots "resource/field/12/after" "resource/field/12/after",
      .eqSlots "resource/field/13/after" "resource/field/13/after"]]

/-- clause 34 -/
def jobClause34 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .leSlotsOff "resource/field/14/after" "clock/now" p.WINDOW]

/-- clause 35 -/
def jobClause35 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .leSlotsOff "clock/now" "resource/field/14/after" p.NEG_WINDOW]

/-- clause 36 -/
def jobClause36 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 2]),
    .not (.eqSlots "resource/field/15/before" "resource/field/15/before")]

/-- clause 37 -/
def jobClause37 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 3]),
    .eqSlots "resource/field/15/before" "resource/field/15/before"]

/-- clause 38 -/
def jobClause38 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 2,
        .eq "resource/field/0/after" 3]),
    .eqSlots "resource/field/15/after" "resource/field/12/after",
    Pred.all [
      .not (.eqSlots "resource/field/15/after" "resource/field/15/after"),
      .leSlotsOff "resource/field/14/after" "clock/now" (-1)]]

/-- clause 39 -/
def jobClause39 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 2,
        .eq "resource/field/0/after" 4]),
    Pred.all [
      .eqSlots "resource/field/15/after" "resource/field/15/after",
      .eqSlots "resource/field/12/after" "resource/field/12/after",
      .not (.eqSlots "resource/field/15/after" "resource/field/12/after")]]

/-- clause 40 -/
def jobClause40 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 1,
        .eq "resource/field/0/after" 4]),
    Pred.all [
      .not (.eqSlots "resource/field/15/after" "resource/field/15/after"),
      .leSlotsOff "resource/field/7/after" "clock/now" (-1)]]

/-- clause 41 -/
def jobClause41 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .eq "resource/field/0/before" 0,
        .eq "resource/field/0/after" 5]),
    .eq "request/subject" p.CALLER,
    .leSlotsOff "resource/field/6/after" "clock/now" (-1)]

/-- clause 42 -/
def jobClause42 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .memberOf "resource/field/0/before" [3, 4, 5],
        .eq "resource/field/0/after" 6]),
    .eq "resource/field/8/after" 0]

/-- clause 43 -/
def jobClause43 (p : Params) : Pred :=
  Pred.any [
    .not (.eq "request/verb" 2),
    .not (Pred.all [
        .memberOf "resource/field/0/before" [3, 4, 5],
        .eq "resource/field/0/after" 6]),
    .eq "resource/field/11/after" 0]

/-- The clauses in the installed order. -/
def jobClauses (p : Params) : List Pred :=
  [jobClause0 p, jobClause1 p, jobClause2 p, jobClause3 p, jobClause4 p, jobClause5 p, jobClause6 p, jobClause7 p, jobClause8 p, jobClause9 p, jobClause10 p, jobClause11 p, jobClause12 p, jobClause13 p, jobClause14 p, jobClause15 p, jobClause16 p, jobClause17 p, jobClause18 p, jobClause19 p, jobClause20 p, jobClause21 p, jobClause22 p, jobClause23 p, jobClause24 p, jobClause25 p, jobClause26 p, jobClause27 p, jobClause28 p, jobClause29 p, jobClause30 p, jobClause31 p, jobClause32 p, jobClause33 p, jobClause34 p, jobClause35 p, jobClause36 p, jobClause37 p, jobClause38 p, jobClause39 p, jobClause40 p, jobClause41 p, jobClause42 p, jobClause43 p]

end Law

/-- The job law: `all` of its clauses, as installed. -/
def jobLaw (p : Params) : Pred := Pred.all (jobClauses p)

/-! ## §3. Reading the law -/

theorem job_clause {p : Params} {o n : State} (h : eval (jobLaw p) o n = true) {q : Pred}
    (hq : q ∈ jobClauses p) : eval q o n = true :=
  ev_all.mp h q hq

/-- `present s` (COMPUTE §2.3's `eqSlots s s`, §10 A6) holds exactly when the slot is present. -/
theorem present_iff {o n : State} {s : String} :
    eval (.eqSlots s s) o n = true ↔ ∃ x, n.get s = some x := by
  rw [ev_eqSlots]; simp

/-- A6 settled: a slot-pair atom on an absent slot is false. -/
theorem present_false_on_absent {o n : State} {s : String} (h : n.get s = none) :
    eval (.eqSlots s s) o n = false := by
  simp [eval, Minidregg.Pred.evalWith, h]

/-! ## §4. Law-level theorems: every (old, new) pair the job law admits

Slot names are the projection's (`resource/field/{n}/{view}`; fields as in `F`). Every statement
below is about an admitted WRITE (`request/verb = 2`); a read changes no field. -/

section LawLevel
variable (p : Params) (o n : State)

/-- **`caller_cannot_forge_truth`.** An admitted write either leaves the truth slot alone (unchanged
when present, absent when absent) or carries the run verdict `RAN_SLOT = 1`. The slot is the kernel's
projection of a re-execution it performed (K-RAN); no field write, by any subject, supplies it. -/
theorem caller_cannot_forge_truth (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) :
    n.get "resource/field/15/delta" = some 0 ∨
      (n.get "resource/field/15/before" = none ∧ n.get "resource/field/15/after" = none) ∨
      n.get p.RAN_SLOT = some 1 := by
  have c21 := job_clause adm (q := jobClause21 p) (by simp [jobClauses])
  have c22 := job_clause adm (q := jobClause22 p) (by simp [jobClauses])
  simp only [jobClause21, jobClause22, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, List.mem_cons,
    List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, not_true_eq_false, false_or,
    forall_eq_or_imp, forall_eq, and_self] at c21 c22
  rcases c21 with c21 | c21
  · exact .inl c21
  · rcases c22 with c22 | c22
    · right; left
      refine ⟨Option.eq_none_iff_forall_ne_some.mpr fun x hx => c21 ⟨x, hx⟩, ?_⟩
      exact Option.eq_none_iff_forall_ne_some.mpr fun x hx =>
        c22 ⟨fun ⟨y, hy⟩ => c21 ⟨y, hy⟩, ⟨x, hx⟩⟩
    · exact .inr (.inr c22)

/-- **`truth_needs_ran`.** An admitted write that introduces the truth carries `RAN_SLOT = 1`, is in
state 1 or 2, and moves no state. -/
theorem truth_needs_ran (adm : eval (jobLaw p) o n = true) (w : n.get "request/verb" = some 2)
    (fresh : n.get "resource/field/15/before" = none) (x : Int)
    (written : n.get "resource/field/15/after" = some x) :
    n.get p.RAN_SLOT = some 1 ∧
      (n.get "resource/field/0/before" = some 1 ∨ n.get "resource/field/0/before" = some 2) ∧
      n.get "resource/field/0/delta" = some 0 := by
  have c22 := job_clause adm (q := jobClause22 p) (by simp [jobClauses])
  have c23 := job_clause adm (q := jobClause23 p) (by simp [jobClauses])
  simp only [jobClause22, jobClause23, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_memberOf,
    List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, fresh, written,
    not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self, reduceCtorEq, exists_false,
    not_false_eq_true, Option.some.injEq, exists_eq'] at c22 c23
  obtain ⟨⟨s, hs, hmem⟩, hd⟩ := c23
  refine ⟨c22, ?_, hd⟩
  rcases hmem with rfl | rfl
  · exact .inl hs
  · exact .inr hs

/-- **`bond_slashed_iff_mismatch`.** A decide out of state 2 with the kernel's truth on the cell is
admitted into `slashed` (4) exactly when the truth disagrees with the posted output, and into `upheld`
(3) exactly when it agrees. The truth is the kernel's (`caller_cannot_forge_truth`). -/
theorem bond_slashed_iff_mismatch (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (from2 : n.get "resource/field/0/before" = some 2)
    (decided : n.get "resource/field/0/after" = some 3 ∨ n.get "resource/field/0/after" = some 4)
    (t : Int) (truth : n.get "resource/field/15/after" = some t) :
    n.get "resource/field/0/after" = some 4 ↔
      ∃ y, n.get "resource/field/12/after" = some y ∧ t ≠ y := by
  have c38 := job_clause adm (q := jobClause38 p) (by simp [jobClauses])
  have c39 := job_clause adm (q := jobClause39 p) (by simp [jobClauses])
  simp [jobClause38, jobClause39, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_leSlotsOff, w, from2,
    truth] at c38 c39
  rcases decided with d | d <;> simp [d] at c38 c39 ⊢
  · intro x hx
    rw [c38] at hx
    exact Option.some.inj hx
  · obtain ⟨⟨y, hy⟩, hne⟩ := c39
    exact ⟨y, hy, fun e => hne (by rw [e]; exact hy)⟩


/-- **The stall (`stall_forfeits_bond`), and the only two ways into `slashed`.** An admitted write into
state 4 came out of state 2 with the truth present and different from the output, or out of state 1
with no truth and `answerBy` strictly before `clock/now`. -/
theorem slashed_only_by_mismatch_or_stall (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (into4 : n.get "resource/field/0/after" = some 4)
    (from12 : n.get "resource/field/0/before" = some 1 ∨ n.get "resource/field/0/before" = some 2) :
    (n.get "resource/field/0/before" = some 2 ∧
      ∃ x y, n.get "resource/field/15/after" = some x ∧ n.get "resource/field/12/after" = some y ∧
        x ≠ y) ∨
    (n.get "resource/field/0/before" = some 1 ∧ n.get "resource/field/15/after" = none ∧
      ∃ a now, n.get "resource/field/7/after" = some a ∧ n.get "clock/now" = some now ∧
        a ≤ now + -1) := by
  have c39 := job_clause adm (q := jobClause39 p) (by simp [jobClauses])
  have c40 := job_clause adm (q := jobClause40 p) (by simp [jobClauses])
  rcases from12 with f | f
  · simp only [jobClause40, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_leSlotsOff,
      List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into4,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c40
    obtain ⟨hn, a, now, ha, hnow, hle⟩ := c40
    exact .inr ⟨f, Option.eq_none_iff_forall_ne_some.mpr fun x hx => hn ⟨x, hx⟩, a, now, ha, hnow, hle⟩
  · simp only [jobClause39, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, List.mem_cons,
      List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into4,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c39
    obtain ⟨⟨x, hx⟩, ⟨y, hy⟩, hne⟩ := c39
    refine .inl ⟨f, x, y, hx, hy, fun e => hne ⟨x, hx, e ▸ hy⟩⟩

/-- **Into `upheld`, per step.** An admitted write from state 1 or 2 into state 3 had the provider's
own run on the cell (from 1), or the truth equal to the output, or no truth and `finalAt` strictly
before `clock/now` (from 2). -/
theorem upheld_requires_match_or_timeout (adm : eval (jobLaw p) o n = true)
    (w : n.get "request/verb" = some 2) (into3 : n.get "resource/field/0/after" = some 3)
    (from12 : n.get "resource/field/0/before" = some 1 ∨ n.get "resource/field/0/before" = some 2) :
    (n.get "resource/field/0/before" = some 1 ∧ ∃ x, n.get "resource/field/15/before" = some x) ∨
    (n.get "resource/field/0/before" = some 2 ∧
      ∃ x, n.get "resource/field/15/after" = some x ∧ n.get "resource/field/12/after" = some x) ∨
    (n.get "resource/field/0/before" = some 2 ∧ n.get "resource/field/15/after" = none ∧
      ∃ f now, n.get "resource/field/14/after" = some f ∧ n.get "clock/now" = some now ∧
        f ≤ now + -1) := by
  have c37 := job_clause adm (q := jobClause37 p) (by simp [jobClauses])
  have c38 := job_clause adm (q := jobClause38 p) (by simp [jobClauses])
  rcases from12 with f | f
  · simp only [jobClause37, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, List.mem_cons,
      List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into3,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c37
    obtain ⟨x, hx⟩ := c37
    exact .inl ⟨f, x, hx⟩
  · simp only [jobClause38, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_leSlotsOff,
      List.mem_cons, List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, f, into3,
      not_true_eq_false, false_or, forall_eq_or_imp, forall_eq, and_self] at c38
    rcases c38 with ⟨x, hx, hy⟩ | ⟨hn, g, now, hg, hnow, hle⟩
    · exact .inr (.inl ⟨f, x, hx, hy⟩)
    · exact .inr (.inr ⟨f, Option.eq_none_iff_forall_ne_some.mpr fun x hx => hn ⟨x, hx⟩,
        g, now, hg, hnow, hle⟩)

/-- **Closing pays out nothing the cell still holds**: an admitted write into state 6 from 3, 4 or 5
leaves `escrow = 0` and `bond = 0` (the pay-out legs are K-JOB-MONEY's, C3). -/
theorem close_empties_cell (adm : eval (jobLaw p) o n = true) (w : n.get "request/verb" = some 2)
    (s : Int) (from345 : n.get "resource/field/0/before" = some s) (hs : s = 3 ∨ s = 4 ∨ s = 5)
    (into6 : n.get "resource/field/0/after" = some 6) :
    n.get "resource/field/8/after" = some 0 ∧ n.get "resource/field/11/after" = some 0 := by
  have c42 := job_clause adm (q := jobClause42 p) (by simp [jobClauses])
  have c43 := job_clause adm (q := jobClause43 p) (by simp [jobClauses])
  simp only [jobClause42, jobClause43, ev_any, ev_all, ev_not, ev_eq, ev_memberOf, List.mem_cons,
    List.not_mem_nil, or_false, exists_eq_or_imp, exists_eq_left, w, from345, into6,
    not_true_eq_false, false_or, forall_eq_or_imp, forall_eq,
    Option.some.injEq, exists_eq_left'] at c42 c43
  rcases hs with rfl | rfl | rfl <;> simp_all

/-- **`no_double_settle`, per step (slot form).** An admitted write on a closed job (state 6 before)
keeps the state and leaves every declared field alone: unchanged where present, absent where absent. -/
theorem closed_step_frame (adm : eval (jobLaw p) o n = true) (w : n.get "request/verb" = some 2)
    (closed : n.get "resource/field/0/before" = some 6) :
    ∀ N ∈ F.all, n.get (fieldName N "delta") = some 0 ∨
      (n.get (fieldName N "before") = none ∧ n.get (fieldName N "after") = none) := by
  have c2 := job_clause adm (q := jobClause2 p) (by simp [jobClauses])
  have c13 := job_clause adm (q := jobClause13 p) (by simp [jobClauses])
  have c14 := job_clause adm (q := jobClause14 p) (by simp [jobClauses])
  have c15 := job_clause adm (q := jobClause15 p) (by simp [jobClauses])
  have c16 := job_clause adm (q := jobClause16 p) (by simp [jobClauses])
  have c17 := job_clause adm (q := jobClause17 p) (by simp [jobClauses])
  have c18 := job_clause adm (q := jobClause18 p) (by simp [jobClauses])
  have c19 := job_clause adm (q := jobClause19 p) (by simp [jobClauses])
  have c20 := job_clause adm (q := jobClause20 p) (by simp [jobClauses])
  have c21 := job_clause adm (q := jobClause21 p) (by simp [jobClauses])
  have c23 := job_clause adm (q := jobClause23 p) (by simp [jobClauses])
  simp [jobClause2, jobClause13, jobClause14, jobClause15, jobClause16, jobClause17, jobClause18,
    jobClause19, jobClause20, jobClause21, jobClause23, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots,
    ev_memberOf, w, closed] at c2 c13 c14 c15 c16 c17 c18 c19 c20 c21 c23
  have nn : ∀ x : Option Int, (∀ y, ¬ x = some y) → x = none :=
    fun x h => Option.eq_none_iff_forall_ne_some.mpr h
  intro N hN
  simp only [F.all, List.mem_cons, List.not_mem_nil, or_false] at hN
  rcases hN with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact .inl c2
  · exact .inl c13.1
  · exact .inl c13.2.1
  · exact .inl c13.2.2.1
  · exact .inl c13.2.2.2.1
  · exact .inl c13.2.2.2.2.1
  · exact .inl c13.2.2.2.2.2.1
  · exact .inl c13.2.2.2.2.2.2
  · exact .inl c14
  · rcases c16 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c17 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · exact .inl c15
  · rcases c18 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c19 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c20 with h | ⟨h1, h2⟩
    · exact .inl h
    · exact .inr ⟨nn _ h1, nn _ h2⟩
  · rcases c21 with h | h
    · exact .inl h
    · exact .inr ⟨nn _ h, nn _ (c23 h)⟩


end LawLevel

/-! ## §5. The kernel's view, and histories -/

section View
open Minidregg.Theory.SheetLaw (Turn view request clockSlots)

/-- One write (or read) on a job cell: who, which verb, the clock, the run verdict the controller
projects (K-RAN; `none` when the command carries no run claim) and the post-state. -/
structure JobTurn where
  verb : Int
  subject : Int
  now : Option Int
  ran : Option Int
  post : Values

/-- The SheetLaw turn with no joint participants. -/
def JobTurn.base (t : JobTurn) : Turn := ⟨t.verb, t.subject, t.now, [], t.post⟩

def ranSlots (p : Params) : Option Int → List (String × Int)
  | none => []
  | some v => [(p.RAN_SLOT, v)]

/-- The policy's view: `SheetLaw.view` (request, fields, clock) and then the run slot. -/
def jview (p : Params) (t : JobTurn) (pre post : Values) : State :=
  ⟨(view t.base pre post).slots ++ ranSlots p t.ran⟩

/-- The law's verdict on a turn from `pre`. -/
def admits (p : Params) (pre : Values) (t : JobTurn) : Bool :=
  eval (jobLaw p) (jview p t pre pre) (jview p t pre t.post)

/-- The clause a refusal names (`Compiler.RefusalReason.LawLeaf`'s path), on the same views. -/
def refusalPath (p : Params) (pre : Values) (t : JobTurn) : Option (List Nat) :=
  firstFailingLeaf (jobLaw p) (jview p t pre pre) (jview p t pre t.post)

/-- The run slot is none of the declared fields' names. -/
def Params.Fresh (p : Params) : Prop :=
  ∀ N ∈ F.all, ∀ v ∈ ["before", "after", "delta"], p.RAN_SLOT ≠ fieldName N v

instance (p : Params) : Decidable p.Fresh := by unfold Params.Fresh; infer_instance

theorem jget (p : Params) (t : JobTurn) (pre post : Values) (k : String) :
    (jview p t pre post).get k =
      ((view t.base pre post).get k).or ((State.mk (ranSlots p t.ran)).get k) := by
  unfold jview State.get
  rw [List.find?_append]
  cases (view t.base pre post).slots.find? (fun q => q.1 == k) <;> rfl

theorem ran_get_ne (p : Params) (r : Option Int) (k : String) (h : p.RAN_SLOT ≠ k) :
    (State.mk (ranSlots p r)).get k = none := by
  cases r <;> simp [ranSlots, State.get, h]

theorem jget_field (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) (v : String) (hv : v ∈ ["before", "after", "delta"]) :
    (jview p t pre post).get (fieldName N v) = (view t.base pre post).get (fieldName N v) := by
  rw [jget, ran_get_ne p _ _ (fr N hN v hv)]
  cases (view t.base pre post).get (fieldName N v) <;> rfl

theorem jget_after (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) : (jview p t pre post).get (fieldName N "after") = get post N := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact Minidregg.Theory.SheetLaw.get_after _ _ _ _

theorem jget_before (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) : (jview p t pre post).get (fieldName N "before") = get pre N := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact Minidregg.Theory.SheetLaw.get_before _ _ _ _

theorem jget_delta (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) (o : Int) (hpre : get pre N = some o) :
    (jview p t pre post).get (fieldName N "delta") = (get post N).map (· - o) := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact Minidregg.Theory.SheetLaw.get_delta _ _ _ _ _ hpre

/-- The `delta` slot is absent when the pre-state lacks the field. -/
theorem view_delta_none (t : Turn) (pre post : Values) (N : Nat) (hpre : get pre N = none) :
    (view t pre post).get (fieldName N "delta") = none := by
  open Minidregg.Theory.SheetLaw in
  have hw : lastc "delta" = some 'r' ∨ lastc "delta" = some 'e' ∨ lastc "delta" = some 'a' :=
    .inr (.inr (by decide))
  open Minidregg.Theory.SheetLaw in
  have hreq := find_none (l := request t.verb t.subject) (k := fieldName N "delta")
    (fun q hq => request_ne_field hq N _ hw (by decide))
  open Minidregg.Theory.SheetLaw in
  have hbef := find_none (l := pre.map (fun p => (fieldName p.1 "before", p.2))) (k := fieldName N "delta")
    (fun q hq => by
      simp only [List.mem_map] at hq
      obtain ⟨p, -, rfl⟩ := hq
      exact ne_of_lastc (by rw [lastc_before, lastc_delta]; decide))
  open Minidregg.Theory.SheetLaw in
  have haft := find_none (l := post.map (fun p => (fieldName p.1 "after", p.2))) (k := fieldName N "delta")
    (fun q hq => by
      simp only [List.mem_map] at hq
      obtain ⟨p, -, rfl⟩ := hq
      exact ne_of_lastc (by rw [lastc_delta, lastc_after]; decide))
  open Minidregg.Theory.SheetLaw in
  have hdel := find_none (k := fieldName N "delta")
    (l := post.filterMap (fun p => (get pre p.1).map fun old => (fieldName p.1 "delta", p.2 - old)))
    (fun q hq => by
      simp only [List.mem_filterMap, Option.map_eq_some_iff] at hq
      obtain ⟨a, -, old, hold, rfl⟩ := hq
      intro e
      have : a.1 = N := fieldName_inj.mp e
      rw [this, hpre] at hold
      cases hold)
  open Minidregg.Theory.SheetLaw in
  have hpair := find_none (k := fieldName N "delta")
    (l := post.flatMap (fun a => post.filterMap fun b => do
        let oldA ← get pre a.1
        let oldB ← get pre b.1
        return (Minidregg.Kernel.DeclaredResourceProjection.pairName a.1 b.1, a.2 + b.2 - oldA - oldB)))
    (fun q hq => by
      obtain ⟨a, b, e⟩ := mem_pairs hq
      rw [e]; exact pairName_ne_fieldName a b N _)
  open Minidregg.Theory.SheetLaw in
  have hclock := find_none (k := fieldName N "delta") (l := clockSlots t.now)
    (fun q hq => clock_ne_field hq N _ hw (by decide))
  open Minidregg.Theory.SheetLaw in
  have hjoint := find_none (k := fieldName N "delta") (l := jointSlots t.joint)
    (fun q hq => joint_ne_field hq N _)
  open Minidregg.Theory.SheetLaw in
  simp only [view, state_get, scalarSlots_split, List.find?_append, hreq, hbef, haft, hdel, hpair,
    hclock, hjoint, Option.or_none, Option.map_none]

theorem jget_delta_none (p : Params) (fr : p.Fresh) (t : JobTurn) (pre post : Values) (N : Nat)
    (hN : N ∈ F.all) (hpre : get pre N = none) :
    (jview p t pre post).get (fieldName N "delta") = none := by
  rw [jget_field p fr t pre post N hN _ (by simp)]
  exact view_delta_none _ _ _ _ hpre

theorem jget_verb (p : Params) (t : JobTurn) (pre post : Values) :
    (jview p t pre post).get "request/verb" = some t.verb := by
  rw [jget, Minidregg.Theory.SheetLaw.get_verb]; rfl

theorem jget_clock (p : Params) (fr : p.RAN_SLOT ≠ "clock/now") (t : JobTurn) (pre post : Values) :
    (jview p t pre post).get "clock/now" = t.now := by
  rw [jget, Minidregg.Theory.SheetLaw.get_clock, ran_get_ne p _ _ fr, Option.or_none]; rfl

/-- A field the slot-pair frame leaves alone is unchanged in the store. -/
theorem frame_eq (p : Params) (fr : p.Fresh) (t : JobTurn) (pre : Values) (N : Nat) (hN : N ∈ F.all)
    (h : (jview p t pre t.post).get (fieldName N "delta") = some 0 ∨
      ((jview p t pre t.post).get (fieldName N "before") = none ∧
        (jview p t pre t.post).get (fieldName N "after") = none)) :
    get t.post N = get pre N := by
  rw [jget_before p fr t pre t.post N hN, jget_after p fr t pre t.post N hN] at h
  cases hp : get pre N with
  | none =>
    rcases h with h | h
    · rw [jget_delta_none p fr t pre t.post N hN hp] at h; cases h
    · exact h.2
  | some o =>
    rcases h with h | h
    · rw [jget_delta p fr t pre t.post N hN o hp] at h
      cases hq : get t.post N with
      | none => rw [hq] at h; cases h
      | some x => rw [hq] at h; simp at h; rw [show x = o by omega]
    · rw [hp] at h; cases h.1

/-- **`no_double_settle`.** On a closed job (state 6) an admitted write changes no declared field:
state 6 has no outgoing edge, and nothing a closed job holds moves again. (A field outside `F.all`
is not covered: `closed_job_admits_undeclared_field`.) -/
theorem no_double_settle (p : Params) (fr : p.Fresh) (pre : Values) (t : JobTurn)
    (adm : admits p pre t = true) (w : t.verb = 2) (closed : get pre F.state = some 6) :
    ∀ N ∈ F.all, get t.post N = get pre N := by
  have w' : (jview p t pre t.post).get "request/verb" = some 2 := by rw [jget_verb, w]
  have c' : (jview p t pre t.post).get "resource/field/0/before" = some 6 := by
    rw [show "resource/field/0/before" = fieldName 0 "before" from rfl,
      jget_before p fr t pre t.post 0 (by decide)]
    exact closed
  intro N hN
  exact frame_eq p fr t pre N hN (closed_step_frame p _ _ adm w' c' N hN)

/-- The state field after an admitted write that enters 3 from anything but 3 was 1 or 2. -/
theorem enters_upheld_from (p : Params) (fr : p.Fresh) (pre : Values) (t : JobTurn)
    (adm : admits p pre t = true) (w : t.verb = 2) (into3 : get t.post F.state = some 3)
    (was : get pre F.state ≠ some 3) : get pre F.state = some 1 ∨ get pre F.state = some 2 := by
  have c2 := job_clause adm (q := jobClause2 p) (by simp [jobClauses])
  have w' : (jview p t pre t.post).get "request/verb" = some 2 := by rw [jget_verb, w]
  have hb : (jview p t pre t.post).get "resource/field/0/before" = get pre 0 :=
    jget_before p fr t pre t.post 0 (by decide)
  have ha : (jview p t pre t.post).get "resource/field/0/after" = get t.post 0 :=
    jget_after p fr t pre t.post 0 (by decide)
  simp only [F.state] at into3 was ⊢
  simp [jobClause2, ev_any, ev_all, ev_not, ev_eq, ev_eqSlots, ev_memberOf, w', hb, ha, into3] at c2
  cases hp : get pre 0 with
  | none =>
    have hd : (jview p t pre t.post).get "resource/field/0/delta" = none :=
      jget_delta_none p fr t pre t.post 0 (by decide) hp
    simp [hd, hp] at c2
  | some s =>
    have hd : (jview p t pre t.post).get "resource/field/0/delta" = (get t.post 0).map (· - s) :=
      jget_delta p fr t pre t.post 0 (by decide) s hp
    rw [hp] at was
    simp [hd, hp, into3] at c2
    simp only [Option.some.injEq, ne_eq] at was ⊢
    omega


/-- The (pre, turn) pairs of a log started at `v`. -/
def stepsOf : Values → List JobTurn → List (Values × JobTurn)
  | _, [] => []
  | v, t :: ts => (v, t) :: stepsOf t.post ts

def final : Values → List JobTurn → Values
  | v, [] => v
  | _, t :: ts => final t.post ts

/-- A job cell's write history: every step a write the law admits from the previous step's post
(`SheetLaw.Accepted`, over job turns). -/
def Accepted (p : Params) (v : Values) (ts : List JobTurn) : Prop :=
  ∀ s ∈ stepsOf v ts, s.2.verb = 2 ∧ admits p s.1 s.2 = true

theorem Accepted.tail {p : Params} {v : Values} {t : JobTurn} {ts : List JobTurn}
    (h : Accepted p v (t :: ts)) : Accepted p t.post ts :=
  fun s hs => h s (by simp [stepsOf, hs])

theorem Accepted.head {p : Params} {v : Values} {t : JobTurn} {ts : List JobTurn}
    (h : Accepted p v (t :: ts)) : t.verb = 2 ∧ admits p v t = true :=
  h (v, t) (by simp [stepsOf])

/-- Why a step entered `upheld` (COMPUTE §2.7 `settle_requires_match_or_timeout`'s disjuncts). -/
def UpheldBy (pre : Values) (t : JobTurn) : Prop :=
  (get pre F.state = some 1 ∧ ∃ x, get pre F.truth = some x) ∨
  (get pre F.state = some 2 ∧ ∃ x, get t.post F.truth = some x ∧ get t.post F.output = some x) ∨
  (get pre F.state = some 2 ∧ get t.post F.truth = none ∧
    ∃ f now, get t.post F.finalAt = some f ∧ t.now = some now ∧ f < now)

theorem upheld_by (p : Params) (fr : p.Fresh) (fc : p.RAN_SLOT ≠ "clock/now") (pre : Values)
    (t : JobTurn) (adm : admits p pre t = true) (w : t.verb = 2) (into3 : get t.post F.state = some 3)
    (was : get pre F.state ≠ some 3) : UpheldBy pre t := by
  have from12 := enters_upheld_from p fr pre t adm w into3 was
  have w' : (jview p t pre t.post).get "request/verb" = some 2 := by rw [jget_verb, w]
  have g := fun N v (hN : N ∈ F.all) (hv : v ∈ ["before", "after", "delta"]) =>
    jget_field p fr t pre t.post N hN v hv
  have r := upheld_requires_match_or_timeout p _ _ adm w'
  rw [show "resource/field/0/after" = fieldName 0 "after" from rfl, jget_after p fr _ _ _ 0 (by decide),
    show "resource/field/0/before" = fieldName 0 "before" from rfl, jget_before p fr _ _ _ 0 (by decide),
    show "resource/field/15/before" = fieldName 15 "before" from rfl,
    jget_before p fr _ _ _ 15 (by decide),
    show "resource/field/15/after" = fieldName 15 "after" from rfl, jget_after p fr _ _ _ 15 (by decide),
    show "resource/field/12/after" = fieldName 12 "after" from rfl, jget_after p fr _ _ _ 12 (by decide),
    show "resource/field/14/after" = fieldName 14 "after" from rfl, jget_after p fr _ _ _ 14 (by decide),
    jget_clock p fc] at r
  have r := r into3 from12
  unfold UpheldBy
  rcases r with ⟨a, b⟩ | ⟨a, b⟩ | ⟨a, b, f, now, hf, hn, hle⟩
  · exact .inl ⟨a, b⟩
  · exact .inr (.inl ⟨a, b⟩)
  · exact .inr (.inr ⟨a, b, f, now, hf, hn, by omega⟩)

/-- Along an accepted history from a cell without state 3, a cell that reaches state 3 got there by a
step `UpheldBy` justifies. -/
theorem reached_upheld (p : Params) (fr : p.Fresh) (fc : p.RAN_SLOT ≠ "clock/now") :
    ∀ (v : Values) (ts : List JobTurn), Accepted p v ts → get v F.state ≠ some 3 →
      get (final v ts) F.state = some 3 → ∃ s ∈ stepsOf v ts, UpheldBy s.1 s.2
  | v, [], _, was, now => absurd now was
  | v, t :: ts, acc, was, now => by
    obtain ⟨w, adm⟩ := acc.head
    by_cases h3 : get t.post F.state = some 3
    · exact ⟨(v, t), by simp [stepsOf], upheld_by p fr fc v t adm w h3 was⟩
    · obtain ⟨s, hs, hu⟩ := reached_upheld p fr fc t.post ts acc.tail h3 now
      exact ⟨s, by simp [stepsOf, hs], hu⟩

theorem stepsOf_prefix : ∀ (v : Values) (ts : List JobTurn) (s : Values × JobTurn),
    s ∈ stepsOf v ts → ∃ pre, s.1 = final v pre ∧ ∀ q ∈ stepsOf v pre, q ∈ stepsOf v ts
  | v, [], s, h => by simp [stepsOf] at h
  | v, t :: ts, s, h => by
    simp only [stepsOf, List.mem_cons] at h
    rcases h with rfl | h
    · exact ⟨[], rfl, by simp [stepsOf]⟩
    · obtain ⟨pre, e, sub⟩ := stepsOf_prefix t.post ts s h
      exact ⟨t :: pre, e, fun q hq => by
        simp only [stepsOf, List.mem_cons] at hq ⊢
        rcases hq with rfl | hq
        · exact .inl rfl
        · exact .inr (sub q hq)⟩

/-- **`settle_requires_match_or_timeout`.** In any accepted history of a job cell from a store with no
state (a fresh declared cell, `unborn`, before its order), every admitted close out of `upheld` (3 → 6) is preceded by the step that entered
`upheld`, and that step had the provider's own run on the cell (from 1), or the kernel's truth equal to
the posted output, or no truth and the clock past `finalAt` (from 2). -/
theorem settle_requires_match_or_timeout (p : Params) (fr : p.Fresh) (fc : p.RAN_SLOT ≠ "clock/now")
    (v : Values) (unordered : get v F.state = none)
    (ts : List JobTurn) (acc : Accepted p v ts) (s : Values × JobTurn) (hs : s ∈ stepsOf v ts)
    (closesUpheld : get s.1 F.state = some 3) (_into6 : get s.2.post F.state = some 6) :
    ∃ u ∈ stepsOf v ts, UpheldBy u.1 u.2 := by
  obtain ⟨pre, e, sub⟩ := stepsOf_prefix v ts s hs
  have accPre : Accepted p v pre := fun q hq => acc q (sub q hq)
  rw [e] at closesUpheld
  obtain ⟨u, hu, by_⟩ := reached_upheld p fr fc v pre accPre (by rw [unordered]; simp) closesUpheld
  exact ⟨u, sub u hu, by_⟩

end View

/-! ## §6. Both poles of every edge, by `decide`, and the counterexamples -/

section Poles

/-- A job: caller 7, program 42, a 600-second window, the run slot spelled as K-RAN projects it. -/
def demo : Params := ⟨7, 42, 600, -600, "run/program/42"⟩

theorem demo_ranSlot : demo.RAN_SLOT = ranSlot demo.PROGRAM := by decide
theorem demo_fresh : demo.Fresh := by decide
theorem demo_ran_not_clock : demo.RAN_SLOT ≠ "clock/now" := by decide

/-- A fresh declared cell, before the order: the kernel births every declared cell holding field 1 of
its own object at zero (`NativeHostGenesis.declaredCell`; MEASURED on the journey Store, jjob1 r1), so
the order writes `program` (field 1) from 0. -/
def unborn : Values := [(1, 0)]

/-- The order: price 100, claimBy 160, answerBy 700, escrow = price, bond 0; input 5; accounts 70. -/
def ordered : Values :=
  [(0, 0), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 100), (11, 0)]
/-- Claimed by subject 8 (account 80) with bond 100. -/
def claimed : Values :=
  [(0, 1), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 100), (9, 8),
    (10, 80), (11, 100)]
/-- Answered at clock 300: output 77, 1345 steps, finalAt 900. -/
def answered : Values :=
  [(0, 2), (1, 42), (2, 5), (3, 7), (4, 70), (5, 100), (6, 160), (7, 700), (8, 100), (9, 8),
    (10, 80), (11, 100), (12, 77), (13, 1345), (14, 900)]
def withTruth (base : Values) (x : Int) : Values := base ++ [(15, x)]
def setState (base : Values) (s : Int) : Values := base.map fun q => if q.1 = 0 then (0, s) else q
def setField (base : Values) (n : Nat) (x : Int) : Values :=
  base.map fun q => if q.1 = n then (n, x) else q
def closedOf (base : Values) : Values := setField (setField (setState base 6) 8 0) 11 0

def w (subject : Int) (now : Int) (post : Values) : JobTurn := ⟨2, subject, some now, none, post⟩
def wRan (subject : Int) (now : Int) (post : Values) : JobTurn := ⟨2, subject, some now, some 1, post⟩

set_option maxRecDepth 20000

-- order (birth)
theorem order_admitted : admits demo unborn (w 7 100 ordered) = true := by decide
/-- A provider cannot order a job in the caller's name: clause 3. -/
theorem order_by_stranger_refused : refusalPath demo unborn (w 8 100 ordered) = some [3] := by decide
/-- An order without a clock is refused (clause 9 fails closed). -/
theorem order_without_clock_refused :
    refusalPath demo unborn ⟨2, 7, none, none, ordered⟩ = some [9] := by decide
/-- An order whose escrow is short of its price: clause 11. -/
theorem order_short_escrow_refused :
    refusalPath demo unborn (w 7 100 (setField ordered 8 50)) = some [11] := by decide

-- claim 0 → 1
theorem claim_admitted : admits demo ordered (w 8 150 claimed) = true := by decide
/-- Past `claimBy`: clause 27. -/
theorem claim_late_refused : refusalPath demo ordered (w 8 200 claimed) = some [27] := by decide
/-- Claiming in another subject's name (subject 9 writes provider := 8): clause 28. -/
theorem claim_for_another_refused : refusalPath demo ordered (w 9 150 claimed) = some [28] := by decide
/-- A bond below the price: clause 30. -/
theorem claim_underbonded_refused :
    refusalPath demo ordered (w 8 150 (setField claimed 11 50)) = some [30] := by decide

-- answer 1 → 2
theorem answer_admitted : admits demo claimed (w 8 300 answered) = true := by decide
/-- The caller posting the answer: clause 31. -/
theorem answer_by_caller_refused : refusalPath demo claimed (w 7 300 answered) = some [31] := by decide
/-- After `answerBy`: clause 32. -/
theorem answer_late_refused :
    refusalPath demo claimed (w 8 800 (setField answered 14 1400)) = some [32] := by decide
/-- A `finalAt` that shortens the window: clause 35. -/
theorem answer_short_window_refused :
    refusalPath demo claimed (w 8 300 (setField answered 14 800)) = some [35] := by decide
/-- **Counterexample pole: a second answer.** Rewriting the output in state 2: clause 18. -/
theorem second_answer_refused :
    refusalPath demo answered (w 8 400 (setField answered 12 78)) = some [18] := by decide

-- truth (state unchanged)
/-- Anyone (subject 9) writes the truth in state 2 inside the window, with the run verdict. -/
theorem truth_admitted : admits demo answered (wRan 9 400 (withTruth answered 77)) = true := by decide
/-- **`caller_cannot_forge_truth`, both poles.** The caller writes a truth without the run verdict:
clause 22. -/
theorem forged_truth_refused :
    refusalPath demo answered (w 7 400 (withTruth answered 77)) = some [22] := by decide
/-- After the window: clause 26. -/
theorem truth_late_refused :
    refusalPath demo answered (wRan 9 1000 (withTruth answered 77)) = some [26] := by decide
/-- The synchronous path: the provider's own run in state 1. -/
theorem sync_truth_admitted : admits demo claimed (wRan 8 300 (withTruth claimed 77)) = true := by
  decide
/-- In state 1 only the provider runs it: clause 24. -/
theorem sync_truth_by_stranger_refused :
    refusalPath demo claimed (wRan 9 300 (withTruth claimed 77)) = some [24] := by decide
/-- A truth write that also moves the state (truth and decide in one turn): clause 23. -/
theorem truth_with_decide_refused :
    refusalPath demo answered (wRan 9 400 (setState (withTruth answered 77) 3)) = some [23] := by
  decide

-- decide → 3
theorem upheld_match_admitted :
    admits demo (withTruth answered 77) (w 9 500 (setState (withTruth answered 77) 3)) = true := by
  decide
/-- **Counterexample pole: the provider closing early.** Upheld from 2 with no truth inside the window:
clause 38. -/
theorem early_upheld_refused :
    refusalPath demo answered (w 8 500 (setState answered 3)) = some [38] := by decide
theorem upheld_timeout_admitted : admits demo answered (w 8 901 (setState answered 3)) = true := by
  decide
/-- Upheld against a mismatched truth: clause 38. -/
theorem upheld_mismatch_refused :
    refusalPath demo (withTruth answered 78) (w 8 500 (setState (withTruth answered 78) 3)) =
      some [38] := by decide
theorem upheld_sync_admitted :
    admits demo (withTruth claimed 77) (w 9 300 (setState (withTruth claimed 77) 3)) = true := by
  decide
/-- Upheld from 1 without the provider's run: clause 37. -/
theorem upheld_from1_without_run_refused :
    refusalPath demo claimed (w 8 300 (setState claimed 3)) = some [37] := by decide

-- decide → 4
theorem slashed_mismatch_admitted :
    admits demo (withTruth answered 78) (w 9 500 (setState (withTruth answered 78) 4)) = true := by
  decide
/-- Slashing a provider whose output the truth matches: clause 39. -/
theorem slashed_match_refused :
    refusalPath demo (withTruth answered 77) (w 7 500 (setState (withTruth answered 77) 4)) =
      some [39] := by decide
/-- The stall: no truth, past `answerBy`. -/
theorem stall_admitted : admits demo claimed (w 7 701 (setState claimed 4)) = true := by decide
/-- Slashing before `answerBy`: clause 40. -/
theorem stall_early_refused : refusalPath demo claimed (w 7 700 (setState claimed 4)) = some [40] := by
  decide

-- decide → 5
theorem void_by_caller_admitted : admits demo ordered (w 7 100 (setState ordered 5)) = true := by decide
/-- A stranger voiding before `claimBy`: clause 41. -/
theorem void_by_stranger_early_refused :
    refusalPath demo ordered (w 9 100 (setState ordered 5)) = some [41] := by decide
theorem void_by_stranger_late_admitted : admits demo ordered (w 9 161 (setState ordered 5)) = true := by
  decide

-- close → 6
theorem close_upheld_admitted :
    admits demo (setState (withTruth answered 77) 3) (w 9 600 (closedOf (withTruth answered 77))) =
      true := by decide
theorem close_slashed_admitted :
    admits demo (setState (withTruth answered 78) 4) (w 9 600 (closedOf (withTruth answered 78))) =
      true := by decide
theorem close_void_admitted :
    admits demo (setState ordered 5) (w 9 600 (closedOf ordered)) = true := by decide
/-- Closing with the bond still held: clause 43. -/
theorem close_holding_bond_refused :
    refusalPath demo (setState (withTruth answered 77) 3)
      (w 9 600 (setField (closedOf (withTruth answered 77)) 11 100)) = some [43] := by decide
/-- Closing an undecided job (2 → 6): clause 2. -/
theorem close_undecided_refused :
    refusalPath demo answered (w 9 600 (closedOf answered)) = some [2] := by decide

-- closed (no_double_settle, poles)
/-- Re-opening a closed job: clause 2. -/
theorem reopen_refused :
    refusalPath demo (closedOf (withTruth answered 77))
      (w 9 700 (setState (closedOf (withTruth answered 77)) 3)) = some [2] := by decide
/-- A truth on a closed job, even with the run verdict: clause 23. -/
theorem truth_after_close_refused :
    refusalPath demo (closedOf answered) (wRan 9 700 (withTruth (closedOf answered) 77)) =
      some [23] := by decide
/-- **Counterexample (a limitation, recorded): a closed job admits a write that creates an UNDECLARED
field.** `Pred` has no "no other slot" atom, so `no_double_settle` covers `F.all` only. -/
theorem closed_job_admits_undeclared_field :
    admits demo (closedOf answered) (w 9 700 (closedOf answered ++ [(20, 1)])) = true := by decide

-- management (clause 0)
/-- The caller delegates (verb 3; a non-write sees no field or clock slot). -/
theorem delegate_by_caller_admitted : admits demo ordered ⟨3, 7, none, none, ordered⟩ = true := by
  decide
theorem delegate_by_provider_refused :
    refusalPath demo ordered ⟨3, 8, none, none, ordered⟩ = some [0] := by decide
/-- **Nobody installs a new law on a live job** — not even the caller: clause 0. -/
theorem install_by_caller_refused :
    refusalPath demo claimed ⟨4, 7, none, none, claimed⟩ = some [0] := by decide
/-- **Nor revokes**: a revoke after claim would cut the bonded provider off and force the stall. -/
theorem revoke_by_caller_refused :
    refusalPath demo claimed ⟨5, 7, none, none, claimed⟩ = some [0] := by decide
/-- A read by anyone is judged only by management. -/
theorem read_admitted : admits demo claimed ⟨1, 9, none, none, claimed⟩ = true := by decide

-- the counterexamples to the wrong spellings
/-- **Counterexample: a negated deadline passes without a clock.** `not (leSlots clock/now finalAt)`
("now > finalAt") is TRUE on a step that has no `clock/now`, so a law written that way would let the
provider take `upheld` by timeout on a clockless write; clause 38's positive `leSlotsOff finalAt
clock/now -1` refuses it (`early_upheld_refused` is the clocked pole). -/
theorem negated_timeout_fails_open :
    eval (.not (.leSlots "clock/now" "resource/field/14/after"))
      (jview demo ⟨2, 8, none, none, setState answered 3⟩ answered answered)
      (jview demo ⟨2, 8, none, none, setState answered 3⟩ answered (setState answered 3)) = true ∧
    refusalPath demo answered ⟨2, 8, none, none, setState answered 3⟩ = some [38] := by decide
/-- **Counterexample: `not (price <= 0)` passes on an absent price**; clause 8's presence conjunct
refuses the priceless order. -/
theorem negated_price_fails_open :
    eval (.not (.le "resource/field/5/after" 0))
      (jview demo (w 7 100 (ordered.filter (·.1 ≠ 5))) unborn unborn)
      (jview demo (w 7 100 (ordered.filter (·.1 ≠ 5))) unborn (ordered.filter (·.1 ≠ 5))) = true ∧
    refusalPath demo unborn (w 7 100 (ordered.filter (·.1 ≠ 5))) = some [8] := by decide

end Poles

/-! ## §7. Axiom pins -/

/-- info: 'Minidregg.Kernel.Job.job_clause' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.job_clause
/-- info: 'Minidregg.Kernel.Job.present_iff' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.present_iff
/-- info: 'Minidregg.Kernel.Job.present_false_on_absent' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.present_false_on_absent
/-- info: 'Minidregg.Kernel.Job.caller_cannot_forge_truth' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.caller_cannot_forge_truth
/-- info: 'Minidregg.Kernel.Job.truth_needs_ran' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_needs_ran
/-- info: 'Minidregg.Kernel.Job.bond_slashed_iff_mismatch' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.bond_slashed_iff_mismatch
/-- info: 'Minidregg.Kernel.Job.slashed_only_by_mismatch_or_stall' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.slashed_only_by_mismatch_or_stall
/-- info: 'Minidregg.Kernel.Job.upheld_requires_match_or_timeout' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_requires_match_or_timeout
/-- info: 'Minidregg.Kernel.Job.close_empties_cell' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_empties_cell
/-- info: 'Minidregg.Kernel.Job.closed_step_frame' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.closed_step_frame
/-- info: 'Minidregg.Kernel.Job.jget' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget
/-- info: 'Minidregg.Kernel.Job.ran_get_ne' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.ran_get_ne
/-- info: 'Minidregg.Kernel.Job.jget_field' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_field
/-- info: 'Minidregg.Kernel.Job.jget_after' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_after
/-- info: 'Minidregg.Kernel.Job.jget_before' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_before
/-- info: 'Minidregg.Kernel.Job.jget_delta' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_delta
/-- info: 'Minidregg.Kernel.Job.view_delta_none' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.view_delta_none
/-- info: 'Minidregg.Kernel.Job.jget_delta_none' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_delta_none
/-- info: 'Minidregg.Kernel.Job.jget_verb' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_verb
/-- info: 'Minidregg.Kernel.Job.jget_clock' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.jget_clock
/-- info: 'Minidregg.Kernel.Job.frame_eq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.frame_eq
/-- info: 'Minidregg.Kernel.Job.no_double_settle' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.no_double_settle
/-- info: 'Minidregg.Kernel.Job.enters_upheld_from' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.enters_upheld_from
/-- info: 'Minidregg.Kernel.Job.Accepted.tail' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.Accepted.tail
/-- info: 'Minidregg.Kernel.Job.Accepted.head' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.Accepted.head
/-- info: 'Minidregg.Kernel.Job.upheld_by' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_by
/-- info: 'Minidregg.Kernel.Job.reached_upheld' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.reached_upheld
/-- info: 'Minidregg.Kernel.Job.stepsOf_prefix' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.stepsOf_prefix
/-- info: 'Minidregg.Kernel.Job.settle_requires_match_or_timeout' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.settle_requires_match_or_timeout
/-- info: 'Minidregg.Kernel.Job.demo_ranSlot' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.demo_ranSlot
/-- info: 'Minidregg.Kernel.Job.demo_fresh' depends on axioms: [propext] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.demo_fresh
/-- info: 'Minidregg.Kernel.Job.order_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_admitted
/-- info: 'Minidregg.Kernel.Job.order_by_stranger_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_by_stranger_refused
/-- info: 'Minidregg.Kernel.Job.order_without_clock_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_without_clock_refused
/-- info: 'Minidregg.Kernel.Job.order_short_escrow_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.order_short_escrow_refused
/-- info: 'Minidregg.Kernel.Job.claim_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_admitted
/-- info: 'Minidregg.Kernel.Job.claim_late_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_late_refused
/-- info: 'Minidregg.Kernel.Job.claim_for_another_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_for_another_refused
/-- info: 'Minidregg.Kernel.Job.claim_underbonded_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.claim_underbonded_refused
/-- info: 'Minidregg.Kernel.Job.answer_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_admitted
/-- info: 'Minidregg.Kernel.Job.answer_by_caller_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_by_caller_refused
/-- info: 'Minidregg.Kernel.Job.answer_late_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_late_refused
/-- info: 'Minidregg.Kernel.Job.answer_short_window_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.answer_short_window_refused
/-- info: 'Minidregg.Kernel.Job.second_answer_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.second_answer_refused
/-- info: 'Minidregg.Kernel.Job.truth_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_admitted
/-- info: 'Minidregg.Kernel.Job.forged_truth_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.forged_truth_refused
/-- info: 'Minidregg.Kernel.Job.truth_late_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_late_refused
/-- info: 'Minidregg.Kernel.Job.sync_truth_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.sync_truth_admitted
/-- info: 'Minidregg.Kernel.Job.sync_truth_by_stranger_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.sync_truth_by_stranger_refused
/-- info: 'Minidregg.Kernel.Job.truth_with_decide_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_with_decide_refused
/-- info: 'Minidregg.Kernel.Job.upheld_match_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_match_admitted
/-- info: 'Minidregg.Kernel.Job.early_upheld_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.early_upheld_refused
/-- info: 'Minidregg.Kernel.Job.upheld_timeout_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_timeout_admitted
/-- info: 'Minidregg.Kernel.Job.upheld_mismatch_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_mismatch_refused
/-- info: 'Minidregg.Kernel.Job.upheld_sync_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_sync_admitted
/-- info: 'Minidregg.Kernel.Job.upheld_from1_without_run_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.upheld_from1_without_run_refused
/-- info: 'Minidregg.Kernel.Job.slashed_mismatch_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.slashed_mismatch_admitted
/-- info: 'Minidregg.Kernel.Job.slashed_match_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.slashed_match_refused
/-- info: 'Minidregg.Kernel.Job.stall_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.stall_admitted
/-- info: 'Minidregg.Kernel.Job.stall_early_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.stall_early_refused
/-- info: 'Minidregg.Kernel.Job.void_by_caller_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.void_by_caller_admitted
/-- info: 'Minidregg.Kernel.Job.void_by_stranger_early_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.void_by_stranger_early_refused
/-- info: 'Minidregg.Kernel.Job.void_by_stranger_late_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.void_by_stranger_late_admitted
/-- info: 'Minidregg.Kernel.Job.close_upheld_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_upheld_admitted
/-- info: 'Minidregg.Kernel.Job.close_slashed_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_slashed_admitted
/-- info: 'Minidregg.Kernel.Job.close_void_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_void_admitted
/-- info: 'Minidregg.Kernel.Job.close_holding_bond_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_holding_bond_refused
/-- info: 'Minidregg.Kernel.Job.close_undecided_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.close_undecided_refused
/-- info: 'Minidregg.Kernel.Job.reopen_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.reopen_refused
/-- info: 'Minidregg.Kernel.Job.truth_after_close_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.truth_after_close_refused
/-- info: 'Minidregg.Kernel.Job.closed_job_admits_undeclared_field' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.closed_job_admits_undeclared_field
/-- info: 'Minidregg.Kernel.Job.delegate_by_caller_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.delegate_by_caller_admitted
/-- info: 'Minidregg.Kernel.Job.delegate_by_provider_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.delegate_by_provider_refused
/-- info: 'Minidregg.Kernel.Job.install_by_caller_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.install_by_caller_refused
/-- info: 'Minidregg.Kernel.Job.revoke_by_caller_refused' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.revoke_by_caller_refused
/-- info: 'Minidregg.Kernel.Job.read_admitted' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.read_admitted
/-- info: 'Minidregg.Kernel.Job.negated_timeout_fails_open' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.negated_timeout_fails_open
/-- info: 'Minidregg.Kernel.Job.negated_price_fails_open' depends on axioms: [propext, Quot.sound] -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.negated_price_fails_open

/-- info: 'Minidregg.Kernel.Job.demo_ran_not_clock' does not depend on any axioms -/
#guard_msgs (whitespace := lax) in #print axioms Minidregg.Kernel.Job.demo_ran_not_clock

end Minidregg.Kernel.Job
