// Generated by scripts/host-operations.py generate; edit protocol/host-operations.json.
// Request byte allocations only. No payload codecs or admission rules live here.
#![allow(dead_code)]

// active; public,operator; owner: kernel-client
pub const DESCRIBE: u8 = 0;
// active; public,operator; owner: kernel-client
pub const AUTHORIZED_PREPARE: u8 = 1;
// active; public,operator; owner: kernel-client
pub const SUBMIT: u8 = 2;
// active; public,operator; owner: kernel-client
pub const LOOKUP: u8 = 3;
// active; public,operator; owner: kernel-client
pub const OBSERVATION_CHALLENGE: u8 = 4;
// active; public,operator; owner: kernel-client
pub const AUTHORIZED_QUERY: u8 = 5;
// active; public,operator; owner: kernel-client
pub const PROFILE: u8 = 6;
// active; public,operator; owner: kernel-client
pub const AUTHOR: u8 = 7;
// active; public,operator; owner: kernel-client
pub const INSPECT: u8 = 8;
// active; public,operator; owner: kernel-client
pub const SIGNATURES: u8 = 9;
// active; public,operator; owner: kernel-client
pub const OBSERVATION_ASSEMBLE: u8 = 10;
// active; public,operator; owner: kernel-client
pub const CALL_ASSEMBLE: u8 = 11;
// active; public,operator; owner: fn-services
pub const FN_POLL: u8 = 12;
// active; public,operator; owner: fn-services
pub const FN_ACK: u8 = 13;
// active; public,operator; owner: fn-services
pub const FN_REPLY_POLL: u8 = 14;
// active; public,operator; owner: fn-services
pub const FN_REPLY_ACK: u8 = 15;
// active; public,operator; owner: fn-services
pub const FN_ORIGIN_OUTBOX: u8 = 16;
// active; public,operator; owner: inference
pub const PROVIDER_CONTINUITY: u8 = 17;
// active; public,operator; owner: fn-services
pub const FN_ORIGIN_OUTBOX_EXPORT: u8 = 18;
// active; public,operator; owner: inference
pub const PROVIDER_USAGE_QUOTE: u8 = 19;
// active; public,operator; owner: selected-release
pub const SELECTED_RELEASE_SUBMIT: u8 = 20;
// active; public,operator; owner: selected-release
pub const SELECTED_RELEASE_LOOKUP: u8 = 21;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_BEGIN_SUBMIT: u8 = 22;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_BEGIN_LOOKUP: u8 = 23;
// active; Host stdio only; owner: selected-release
pub const SELECTED_SOURCE_PUBLISH_SUBMIT: u8 = 24;
// active; Host stdio only; owner: selected-release
pub const SELECTED_SOURCE_PUBLISH_LOOKUP: u8 = 25;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_CLAIM_SUBMIT: u8 = 26;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_CLAIM_LOOKUP: u8 = 27;
// active; public,operator; owner: spk
pub const APPLICATION_SHARE_ISSUE_SUBMIT: u8 = 28;
// active; public,operator; owner: spk
pub const APPLICATION_SHARE_ISSUE_LOOKUP: u8 = 29;
// active; public,operator; owner: spk
pub const APPLICATION_CURRENT_BIRTH: u8 = 30;
// active; public,operator; owner: spk
pub const APPLICATION_SESSION_CURRENT_BIRTH: u8 = 31;
// active; operator; owner: spk
pub const APPLICATION_SHARE_ISSUE_PLAN: u8 = 32;
// active; operator; owner: spk
pub const APPLICATION_SHARE_ISSUE_ASSEMBLE: u8 = 33;
// active; operator; owner: spk
pub const APPLICATION_DISPATCH_SUBMIT: u8 = 34;
// active; operator; owner: spk
pub const APPLICATION_DISPATCH_LOOKUP: u8 = 35;
// active; operator; owner: spk
pub const APPLICATION_DISPATCH_PLAN: u8 = 36;
// active; operator; owner: spk
pub const APPLICATION_DISPATCH_ASSEMBLE: u8 = 37;
// active; operator; owner: spk
pub const APPLICATION_LIFECYCLE_COMPLETION_SUBMIT: u8 = 38;
// active; operator; owner: spk
pub const APPLICATION_LIFECYCLE_COMPLETION_LOOKUP: u8 = 39;
// active; operator; owner: fn-services
pub const FN_NAMESPACE_SUBMIT: u8 = 40;
// active; operator; owner: fn-services
pub const FN_NAMESPACE_LOOKUP: u8 = 41;
// active; operator; owner: fn-services
pub const FN_NAMESPACE_PLAN: u8 = 42;
// active; operator; owner: fn-services
pub const FN_NAMESPACE_ASSEMBLE: u8 = 43;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_COMPLETION_PLAN: u8 = 44;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_COMPLETION_ASSEMBLE: u8 = 45;
// active; operator; owner: hermes
pub const AGENT_PAID_DISPATCH_SUBMIT: u8 = 46;
// active; operator; owner: hermes
pub const AGENT_PAID_DISPATCH_LOOKUP: u8 = 47;
// active; operator; owner: hermes
pub const AGENT_PAID_DISPATCH_PLAN: u8 = 48;
// active; operator; owner: hermes
pub const AGENT_PAID_DISPATCH_ASSEMBLE: u8 = 49;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_BEGIN_PLAN: u8 = 50;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_BEGIN_ASSEMBLE: u8 = 51;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_CLAIM_PLAN: u8 = 52;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LIFECYCLE_CLAIM_ASSEMBLE: u8 = 53;
// active; operator; owner: spk
pub const GRAIN_SHARE_ISSUE_SUBMIT: u8 = 54;
// active; operator; owner: spk
pub const GRAIN_SHARE_ISSUE_LOOKUP: u8 = 55;
// active; operator; owner: spk
pub const GRAIN_SHARE_ISSUE_PLAN: u8 = 56;
// active; operator; owner: spk
pub const GRAIN_SHARE_ISSUE_ASSEMBLE: u8 = 57;
// active; operator; owner: hermes
pub const AGENT_RESERVE_PLAN: u8 = 58;
// active; operator; owner: hermes
pub const AGENT_RESERVE_ASSEMBLE: u8 = 59;
// active; operator; owner: fn-services
pub const FN_SELECTED_COVERAGE_SUBMIT: u8 = 60;
// active; operator; owner: fn-services
pub const FN_SELECTED_COVERAGE_LOOKUP: u8 = 61;
// active; operator; owner: fn-services
pub const FN_EMPTY_PROGRESS_SUBMIT: u8 = 62;
// active; operator; owner: fn-services
pub const FN_EMPTY_PROGRESS_LOOKUP: u8 = 63;
// active; operator; owner: fn-services
pub const FN_FRONTIER_PLAN: u8 = 64;
// active; operator; owner: fn-services
pub const FN_FRONTIER_ASSEMBLE: u8 = 65;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LAUNCH_BEGIN_PLAN: u8 = 66;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LAUNCH_BEGIN_ASSEMBLE: u8 = 67;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LAUNCH_CLAIM_PLAN: u8 = 68;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LAUNCH_CLAIM_ASSEMBLE: u8 = 69;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LAUNCH_COMPLETION_PLAN: u8 = 70;
// active; operator; owner: spk-lifecycle
pub const APPLICATION_LAUNCH_COMPLETION_ASSEMBLE: u8 = 71;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_GRANT_SUBMIT: u8 = 72;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_GRANT_LOOKUP: u8 = 73;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_GRANT_PLAN: u8 = 74;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_GRANT_ASSEMBLE: u8 = 75;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_DISPATCH_SUBMIT: u8 = 76;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_DISPATCH_LOOKUP: u8 = 77;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_DISPATCH_PLAN: u8 = 78;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_DISPATCH_ASSEMBLE: u8 = 79;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_RESERVE_PLAN: u8 = 80;
// active; operator; owner: hermes
pub const AGENT_LIFETIME_RESERVE_ASSEMBLE: u8 = 81;
// active; operator; owner: spk
pub const APPLICATION_SESSION_ENROLLMENT_PLAN: u8 = 82;
// active; operator; owner: spk
pub const APPLICATION_SESSION_ENROLLMENT_ASSEMBLE: u8 = 83;
// active; operator; owner: spk
pub const APPLICATION_SESSION_ENROLLMENT_SUBMIT: u8 = 84;
// active; operator; owner: spk
pub const APPLICATION_SESSION_ENROLLMENT_LOOKUP: u8 = 85;
// active; public,operator; owner: identity
pub const PARTICIPANT_KEY_ENROLLMENT_PLAN: u8 = 86;
// active; public,operator; owner: identity
pub const PARTICIPANT_KEY_ENROLLMENT_ASSEMBLE: u8 = 87;
// active; public,operator; owner: identity
pub const PARTICIPANT_KEY_ENROLLMENT_SUBMIT: u8 = 88;
// active; public,operator; owner: identity
pub const PARTICIPANT_KEY_ENROLLMENT_LOOKUP: u8 = 89;
// active; public,operator; owner: world
pub const CURRENT_RESOURCE_BIRTH: u8 = 91;
// active; public,operator; owner: identity
pub const PARTICIPANT_PROVISIONING_PLAN: u8 = 92;
// active; public,operator; owner: identity
pub const PARTICIPANT_PROVISIONING_ASSEMBLE: u8 = 93;
// active; public,operator; owner: identity
pub const PARTICIPANT_PROVISIONING_SUBMIT: u8 = 94;
// active; public,operator; owner: identity
pub const PARTICIPANT_PROVISIONING_LOOKUP: u8 = 95;
// active; public,operator; owner: fleet
pub const FLEET_TURN_PLAN: u8 = 96;
// active; public,operator; owner: fleet
pub const FLEET_TURN_ASSEMBLE: u8 = 97;
// active; public,operator; owner: fleet
pub const FLEET_TURN_SUBMIT: u8 = 98;
// active; public,operator; owner: fleet
pub const FLEET_TURN_LOOKUP: u8 = 99;
// active; public,operator; owner: fleet
pub const FLEET_TOPIC_POLL: u8 = 100;
// active; public,operator; owner: fleet
pub const FLEET_HEAD: u8 = 101;
// active; public,operator; owner: fleet
pub const FLEET_RECEIPT: u8 = 102;
// active; public,operator; owner: payments
pub const PAY_COMMAND_PLAN: u8 = 103;
// active; public,operator; owner: payments
pub const PAY_COMMAND_ASSEMBLE: u8 = 104;
// active; public,operator; owner: payments
pub const PAY_COMMAND_SUBMIT: u8 = 105;
// active; public,operator; owner: payments
pub const PAY_COMMAND_LOOKUP: u8 = 106;
// active; public,operator; owner: payments
pub const PAY_VIEW: u8 = 107;
// active; public,operator; owner: payments
pub const PAY_OBSERVATION_PLAN: u8 = 108;
// active; public,operator; owner: payments
pub const PAY_OBSERVATION_ASSEMBLE: u8 = 109;
// active; public,operator; owner: payments
pub const PAY_OBSERVATION_SUBMIT: u8 = 110;
// active; public,operator; owner: payments
pub const PAY_OBSERVATION_LOOKUP: u8 = 111;
// active; public,operator; owner: payments
pub const PAY_ENROLLMENT_VIEW: u8 = 112;
// active; public,operator; owner: payments
pub const PAY_REFILL_PLAN: u8 = 113;
// active; public,operator; owner: payments
pub const PAY_REFILL_ASSEMBLE: u8 = 114;
// active; public,operator; owner: payments
pub const PAY_REFILL_SUBMIT: u8 = 115;
// active; public,operator; owner: payments
pub const PAY_REFILL_LOOKUP: u8 = 116;
// active; operator; owner: payments
pub const PAY_SELF_ENROLLMENT_PLAN: u8 = 117;
// active; operator; owner: payments
pub const PAY_SELF_ENROLLMENT_ASSEMBLE: u8 = 118;
// active; operator; owner: payments
pub const PAY_SELF_ENROLLMENT_SUBMIT: u8 = 119;
// active; operator; owner: payments
pub const PAY_SELF_ENROLLMENT_LOOKUP: u8 = 120;
// active; public,operator; owner: payments
pub const PAY_ENROLLMENT_QUOTE: u8 = 121;
// active; public,operator; owner: world
pub const REALM_WELL_PLAN: u8 = 123;
// active; public,operator; owner: world
pub const REALM_WELL_ASSEMBLE: u8 = 124;
// active; public,operator; owner: world
pub const REALM_WELL_SUBMIT: u8 = 125;
// active; public,operator; owner: clock
pub const CLOCK_TICK_PLAN: u8 = 126;
// active; public,operator; owner: clock
pub const CLOCK_TICK_ASSEMBLE: u8 = 127;
// active; public,operator; owner: clock
pub const CLOCK_TICK_SUBMIT: u8 = 128;
// active; public,operator; owner: clock
pub const CLOCK_VIEW: u8 = 129;
// active; public,operator; owner: world
pub const AFFORDANCE_DRY_RUN: u8 = 130;
// active; public,operator; owner: nock
pub const NOCK_PROGRAM_CHECK: u8 = 131;
// active; public,operator; owner: nock
pub const NOCK_PROGRAM_SHOW: u8 = 132;
// active; public,operator; owner: nock
pub const NOCK_SAMPLE: u8 = 133;
// active; public,operator; owner: nock
pub const NOCK_DRY_RUN: u8 = 134;
// active; public,operator; owner: nock
pub const NOCK_APP_POKE_DRY_RUN: u8 = 135;
// active; public,operator; owner: nock
pub const NOCK_APP_PEEK: u8 = 136;
// active; public,operator; owner: nock
pub const NOCK_APP_STATE: u8 = 137;
// active; public,operator; owner: identity
pub const KEY_ROTATION_PLAN: u8 = 140;
// active; public,operator; owner: identity
pub const KEY_ROTATION_ASSEMBLE: u8 = 141;
// active; public,operator; owner: identity
pub const KEY_ROTATION_SUBMIT: u8 = 142;
// active; public,operator; owner: identity
pub const KEY_ROTATION_LOOKUP: u8 = 143;
// active; public,operator; owner: identity
pub const KEY_ROTATION_STATUS: u8 = 144;
// active; public,operator; owner: laws
pub const LAW_SAT: u8 = 150;
// active; public,operator; owner: receipt-continuity
pub const RECEIPT_CONTINUITY: u8 = 151;
// active; operator; owner: spk
pub const APPLICATION_STREAM_RENEW: u8 = 152;
// active; public,operator; owner: checked-carry
pub const CARRY_RECEIPT_LOOKUP: u8 = 153;
// active; operator; owner: spk
pub const APPLICATION_ROUTE_INSPECT: u8 = 154;
// active; public,operator; owner: job-money
pub const JOB_MONEY_PLAN: u8 = 160;
// active; public,operator; owner: job-money
pub const JOB_MONEY_ASSEMBLE: u8 = 161;
// active; public,operator; owner: job-money
pub const JOB_MONEY_SUBMIT: u8 = 162;
// active; public,operator; owner: job-money
pub const JOB_MONEY_LOOKUP: u8 = 163;
// active; operator; owner: spk
pub const APPLICATION_ROUTE_BOUND_DISPATCH: u8 = 164;
// active; public,operator; owner: history
pub const CERTIFY_PLAN: u8 = 170;
// active; public,operator; owner: history
pub const CERTIFY_ASSEMBLE: u8 = 171;
// active; public,operator; owner: history
pub const CERTIFY_SUBMIT: u8 = 172;
// active; public,operator; owner: history
pub const CERTIFY_VIEW: u8 = 173;
// active; public,operator; owner: fleet
pub const FLEET_INCOMING_LEDGER: u8 = 180;
// active; public,operator; owner: payments
pub const PAY_CLAIM_VIEW: u8 = 181;
// active; public,operator; owner: payments
pub const PAY_CLAIM_QUOTE: u8 = 182;
// active; public,operator; owner: payments
pub const PAY_CLAIM_PLAN: u8 = 183;
// active; public,operator; owner: payments
pub const PAY_CLAIM_ASSEMBLE: u8 = 184;
// active; public,operator; owner: payments
pub const PAY_CLAIM_SUBMIT: u8 = 185;
// active; public,operator; owner: payments
pub const PAY_CLAIM_LOOKUP: u8 = 186;
// active; public,operator; owner: identity
pub const NEXT_KEY_ADOPTION_PLAN: u8 = 187;
// active; public,operator; owner: identity
pub const NEXT_KEY_ADOPTION_ASSEMBLE: u8 = 188;
// active; public,operator; owner: identity
pub const NEXT_KEY_ADOPTION_SUBMIT: u8 = 189;
// active; public,operator; owner: identity
pub const NEXT_KEY_ADOPTION_LOOKUP: u8 = 190;
// reserved; public,operator; owner: checked-carry/payments
pub const CARRY_PAY_CLAIM_LOOKUP: u8 = 191;
// reserved; public,operator; owner: law-diagnostics
pub const LAW_DIAGNOSTIC: u8 = 192;
// active; public,operator; owner: application-dispatch/member-workspace
pub const APPLICATION_DISPATCH_READY: u8 = 193;
// active; public,operator; owner: application-dispatch/member-workspace
pub const APPLICATION_DISPATCH_AUTHENTICATED_PLAN: u8 = 194;
// active; public,operator; owner: resource-reserve-birth
pub const RESERVE_RESOURCE_BIRTH_PLAN: u8 = 201;
// active; public,operator; owner: resource-reserve-birth
pub const RESERVE_RESOURCE_BIRTH_ASSEMBLE: u8 = 202;
// active; operator; owner: spk-recovery
pub const APPLICATION_FAILED_START_RECOVERY_PREPARE: u8 = 206;
// active; operator; owner: spk-recovery
pub const APPLICATION_FAILED_START_RECOVERY_ASSEMBLE: u8 = 207;
// active; operator; owner: spk-recovery
pub const APPLICATION_FAILED_START_RECOVERY_SUBMIT: u8 = 208;
// active; operator; owner: spk-recovery
pub const APPLICATION_FAILED_START_RECOVERY_LOOKUP: u8 = 209;
// active; public,operator; owner: activity-native
pub const ACTIVITY_PLAN: u8 = 210;
// active; public,operator; owner: activity-native
pub const ACTIVITY_ASSEMBLE: u8 = 211;
// active; public,operator; owner: activity-native
pub const ACTIVITY_SUBMIT: u8 = 212;
// active; public,operator; owner: activity-native
pub const ACTIVITY_LOOKUP: u8 = 213;
// active; public,operator; owner: activity-native
pub const ACTIVITY_VIEW: u8 = 214;
// active; public,operator; owner: seats-native
pub const SEAT_PLAN: u8 = 215;
// active; public,operator; owner: seats-native
pub const SEAT_ASSEMBLE: u8 = 216;
// active; public,operator; owner: seats-native
pub const SEAT_SUBMIT: u8 = 217;
// active; public,operator; owner: seats-native
pub const SEAT_LOOKUP: u8 = 218;
// active; public,operator; owner: seats-native
pub const SEAT_VIEW: u8 = 219;
