/-
# Compiler.NativeGlueGen — deterministic data-only Rust glue

This generator consumes only `ArtifactBundle.canonicalEncoding`.  It emits a
mechanical Rust integration surface: canonical data constants, plain DTOs, and
three native work-dispatch methods returning a buffer or an error.  It emits no
validation routine, transcript implementation, statement construction,
verifier Boolean, policy procedure, or proof/acceptance token.

The complete artifact encoding is carried as its injective `Encodable` natural
written in decimal.  Selected manifest identifiers and shape counts are also
projected as data constants for convenient glue integration.  Rust is therefore
generated plumbing or unverified compute only; all semantic checking remains in
Lean-owned controllers.
-/
import Compiler.SemanticArtifactBundle

namespace Minidregg.Compiler.NativeGlueGen

open Minidregg.Compiler.SemanticArtifactBundle

set_option autoImplicit false

/-! ## Deterministic source text from the canonical encoding -/

private def rustDecimal (value : Nat) : String :=
  "\"" ++ toString value ++ "\""

private def rustDecimalSlice (values : List Nat) : String :=
  let entries := values.map rustDecimal
  "&[" ++ String.intercalate ", " entries ++ "]"

/-- Rust source generated from the closed first-order encoding, rather than from
the higher-order declaration objects which produced it. -/
def rustSourceFromEncoding (wire : ArtifactBundleEncoding) : String :=
  let manifest := wire.manifest
  let canonicalCode := Encodable.encode wire
  let clauseIds := manifest.nativeClauses.map (·.clauseId)
  let codecIds := manifest.codecs.map (·.codecId)
  String.intercalate "\n"
    ["// @generated by Minidregg.Compiler.NativeGlueGen; do not edit.",
     "// Data transport and opaque work dispatch only.",
     "",
     "pub const ARTIFACT_SCHEMA: &str = \"minidregg/semantic-artifact-bundle/v1\";",
     "pub const ARTIFACT_CANONICAL_CODE_DECIMAL: &str = " ++
       rustDecimal canonicalCode ++ ";",
     "pub const MANIFEST_VERSION_DECIMAL: &str = " ++
       rustDecimal manifest.manifestVersion ++ ";",
     "pub const ABI_ID_DECIMAL: &str = " ++ rustDecimal manifest.abiId ++ ";",
     "pub const SEMANTIC_PROGRAM_ID_DECIMAL: &str = " ++
       rustDecimal manifest.semanticProgramId ++ ";",
     "pub const SEMANTIC_RELATION_ID_DECIMAL: &str = " ++
       rustDecimal manifest.semanticRelationId ++ ";",
     "pub const RECEIPT_CODEC_ID_DECIMAL: &str = " ++
       rustDecimal manifest.receiptCodecId ++ ";",
     "pub const NATIVE_CLAUSE_IDS_DECIMAL: &[&str] = " ++
       rustDecimalSlice clauseIds ++ ";",
     "pub const CODEC_IDS_DECIMAL: &[&str] = " ++
       rustDecimalSlice codecIds ++ ";",
     "pub const EFFECT_DECLARATION_COUNT: usize = " ++
       toString wire.effects.length ++ ";",
     "pub const OUTER_PHASE_COUNT: usize = " ++
       toString wire.phasePlan.length ++ ";",
     "",
     "#[derive(Clone, Debug, PartialEq, Eq)]",
     "pub struct CanonicalArtifactDto {",
     "    pub schema: &'static str,",
     "    pub canonical_code_decimal: &'static str,",
     "}",
     "",
     "pub const CANONICAL_ARTIFACT: CanonicalArtifactDto = CanonicalArtifactDto {",
     "    schema: ARTIFACT_SCHEMA,",
     "    canonical_code_decimal: ARTIFACT_CANONICAL_CODE_DECIMAL,",
     "};",
     "",
     "#[derive(Clone, Debug, PartialEq, Eq)]",
     "pub struct WorkRequestDto {",
     "    pub ordinal: usize,",
     "    pub clause_id_decimal: String,",
     "    pub public_words: Box<[u32]>,",
     "    pub descriptor_bytes: Box<[u8]>,",
     "    pub response_word_bound: usize,",
     "}",
     "",
     "#[derive(Clone, Debug, PartialEq, Eq)]",
     "pub struct KernelBufferDto {",
     "    pub words: Box<[u32]>,",
     "}",
     "",
     "#[derive(Clone, Debug, PartialEq, Eq)]",
     "pub enum NativeErrorKind {",
     "    UnsupportedWork,",
     "    MalformedRequest,",
     "    ExecutionFailure,",
     "}",
     "",
     "#[derive(Clone, Debug, PartialEq, Eq)]",
     "pub struct NativeErrorDto {",
     "    pub kind: NativeErrorKind,",
     "    pub detail: String,",
     "}",
     "",
     "pub trait NativePlanDispatch {",
     "    fn run_arithmetic(",
     "        &mut self,",
     "        request: WorkRequestDto,",
     "    ) -> Result<KernelBufferDto, NativeErrorDto>;",
     "",
     "    fn run_hash(",
     "        &mut self,",
     "        request: WorkRequestDto,",
     "    ) -> Result<KernelBufferDto, NativeErrorDto>;",
     "",
     "    fn run_transform(",
     "        &mut self,",
     "        request: WorkRequestDto,",
     "    ) -> Result<KernelBufferDto, NativeErrorDto>;",
     "}",
     ""]

/-- Public generator entry point.  Its only input to source generation is the
bundle's canonical encoding. -/
def rustSource (bundle : ArtifactBundle) : String :=
  rustSourceFromEncoding bundle.canonicalEncoding

@[simp] theorem rustSource_def (bundle : ArtifactBundle) :
    rustSource bundle = rustSourceFromEncoding bundle.canonicalEncoding :=
  rfl

/-- Equal canonical artifact encodings generate byte-for-byte equal Rust source
text.  No ambient state, target path, clock, or native implementation is read. -/
theorem rustSource_eq_of_canonicalEncoding_eq
    {left right : ArtifactBundle}
    (sameEncoding : left.canonicalEncoding = right.canonicalEncoding) :
    rustSource left = rustSource right := by
  exact congrArg rustSourceFromEncoding sameEncoding

/-- Determinism stated directly at the closed encoding boundary. -/
theorem rustSourceFromEncoding_deterministic
    {left right : ArtifactBundleEncoding} (same : left = right) :
    rustSourceFromEncoding left = rustSourceFromEncoding right := by
  exact congrArg rustSourceFromEncoding same

/-! ## Writer and reusable build target -/

/-- Write generated source only when explicitly run by a build target.  Defining
this function performs no filesystem or Rust mutation. -/
def writeRustSource (path : System.FilePath) (bundle : ArtifactBundle) : IO Unit := do
  if let some directory := path.parent then IO.FS.createDirAll directory
  IO.FS.writeFile path (rustSource bundle)

structure BuildTarget where
  path : System.FilePath
  bundle : ArtifactBundle

def BuildTarget.run (target : BuildTarget) : IO Unit :=
  writeRustSource target.path target.bundle

#print axioms rustSource_eq_of_canonicalEncoding_eq
#print axioms rustSourceFromEncoding_deterministic

end Minidregg.Compiler.NativeGlueGen
