//! minidregg-prover — unverified native compute.
//!
//! This crate exposes arithmetic, transform, raw hash, and buffer-management
//! kernels. Inputs are explicit low-level work data; outputs are buffers or local
//! execution errors. The one protocol-shaped resident is `sumcheck` — the
//! Selvage sumcheck engine, an unverified mirror whose acceptance semantics are
//! bound to the Lean side by the `testdata/` conformance vector.

// This module is generated by Lean from `Compiler.MinidreggV1Artifact`.
// It contains canonical artifact data and opaque dispatch DTOs only: no native
// parser, semantic checker, transcript, verifier verdict, or accepted token.
#[path = "../generated/semantic_artifact_v1.rs"]
pub mod semantic_artifact_v1;

pub mod additive_ntt;
pub mod babybear;
pub mod binary_tower;
pub mod binary_tower_256;
pub mod field6;
pub mod hash_kernels;
pub mod mle_kernels;
pub mod native_dispatch;
pub mod semantic_artifact_arithmetic;
pub mod sumcheck;
pub mod tower256_kernels;
