import Kernel.NativeJointAgreement
import Theory.AssertAxioms

/- This gate audits named general claims. It is not a build/deployment or
cryptographic-finality claim; no closed-case #guard replaces a theorem. -/
#assert_axioms Minidregg.Kernel.JointInvocationCandidate.candidate_encode_injective
#assert_axioms Minidregg.Kernel.JointInvocationCandidate.admitted_guard_in_footprint
#assert_axioms Minidregg.Kernel.JointDecisionRecovery.commit_abort_exclusive
#assert_axioms Minidregg.Kernel.JointDecisionRecovery.decideVote_preserves_decided
#assert_axioms Minidregg.Kernel.JointDecisionRecovery.no_survives_late_yes
#assert_axioms Minidregg.Kernel.JointDecisionRecovery.decideVote_final_yes_requires_others
#assert_axioms Minidregg.Kernel.JointDecisionRecovery.handoff_retains_liabilities
#assert_axioms Minidregg.Kernel.NativeJointAgreement.replay_append
#assert_axioms Minidregg.Kernel.NativeJointAgreement.restore_wrong_candidate
#assert_axioms Minidregg.Kernel.NativeJointAgreement.disabled_cannot_vote
#assert_axioms Minidregg.Kernel.NativeJointAgreement.vote_once

#assert_axioms Minidregg.Kernel.JointReservation.allowed_compatible
#assert_axioms Minidregg.Kernel.JointReservation.allowed_funded
#assert_axioms Minidregg.Kernel.JointReservation.compatible_install_preserves_bytes
#assert_axioms Minidregg.Kernel.JointReservation.compatible_install_preserves_root

#assert_axioms Minidregg.Kernel.JointDecisionRecovery.Trace.preserves_decided
#assert_axioms Minidregg.Kernel.JointDecisionRecovery.abort_stable_under_trace

#assert_axioms Minidregg.Kernel.NativeJointAgreement.journal_encode_injective
