#!/usr/bin/env python3
"""The story law files and Assurance/StoryLaw.lean §8 are the client's generator output; this script writes them.

usage (from the repository root):
  scripts/gen-storylaw.py --mini PATH           run `PATH story-law --table deploy/shell/templates/story/tale/table`
                                                (the parser and generator `story seal` runs) and write
                                                tale/law.player.json, tale/law.player and tale/law.table.json,
                                                then rewrite the GENERATED region of Assurance/StoryLaw.lean
  scripts/gen-storylaw.py --mini PATH --check   exit 1 if any of them is not what the client generates now

The Lean region holds `taleTable` (the table's edges and item scenes, as the client parsed them) and
`taleEmbedded S` (the client's player law, `{S}` -> `S`, nothing re-sorted, dropped or simplified).
`tale_embedded_is_law` proves `taleEmbedded S = law taleTable S` by `rfl`, so the build fails if the
client's generator and the Lean `law` ever disagree on the tale, and the theorems about `law` are about
the law `story seal` installs."""
import json, re, subprocess, sys

T = "deploy/shell/templates/story/tale"
F = "Assurance/StoryLaw.lean"
BEGIN, END = "-- BEGIN GENERATED (scripts/gen-storylaw.py)\n", "-- END GENERATED"
PH = re.compile(r"\{([A-Z_0-9]+)\}")


def val(v):
    v = str(v)
    m = PH.fullmatch(v)
    if m:
        return m.group(1)
    n = int(v)
    return f"({n})" if n < 0 else str(n)


def render(n, ind):
    t = n["type"]
    if t in ("all", "any"):
        if not n["predicates"]:
            return f"Pred.{t} []"
        kids = [" " * (ind + 2) + render(c, ind + 2) for c in n["predicates"]]
        return f"Pred.{t} [\n" + ",\n".join(kids) + "]"
    if t == "not":
        return f".not ({render(n['predicate'], ind + 2)})"
    if t in ("eq", "le"):
        return f'.{t} "{n["slot"]}" {val(n["value"])}'
    if t == "memberOf":
        return f'.memberOf "{n["slot"]}" [' + ", ".join(val(v) for v in n["values"]) + "]"
    sys.exit(f"gen-storylaw: no Lean rendering for atom type {t!r}")


def lean(out):
    edges = ", ".join(f"⟨{a}, {b}, {'none' if i is None else f'some {i}'}⟩" for a, b, i in out["edges"])
    items = ", ".join(str(s) for s in out["items"])
    return (
        "/-- The tale's table, as the client parsed it: edges in (from, to) order, item scenes in item-name order. -/\n"
        f"def taleTable : Table := ⟨[{edges}], [{items}]⟩\n\n"
        "/-- The client's law for player `S` of the tale, as `story seal` generates it. -/\n"
        f"def taleEmbedded (S : Int) : Pred :=\n  {render(out['player'], 2)}\n"
    )


def law_text(out):
    head = ("-- generated by scripts/gen-storylaw.py from `mini story-law --table table`: the law on each\n"
            "-- player's cell, one clause per line, each as the Host renders it in a refusal; {S} is the player.\n")
    lines = []
    for i, (c, text) in enumerate(zip(out["clauses"], out["grammar"].rstrip("\n").split(";\n"))):
        lines.append(f"-- clause {i}: {c['name']}\n{text}")
    return head + ";\n".join(lines) + "\n"


args = sys.argv[1:]
check = "--check" in args
if "--mini" not in args:
    sys.exit("usage: scripts/gen-storylaw.py --mini PATH [--check]")
mini = args[args.index("--mini") + 1]
out = json.loads(subprocess.run([mini, "story-law", "--table", f"{T}/table"], check=True,
                                capture_output=True, text=True).stdout)
files = {
    f"{T}/law.player.json": json.dumps(out["player"], indent=1) + "\n",
    f"{T}/law.player": law_text(out),
    f"{T}/law.table.json": json.dumps(out["tableSealed"], indent=1) + "\n",
}
s = open(F).read()
a, b = s.index(BEGIN) + len(BEGIN), s.index(END)
files[F] = s[:a] + lean(out) + s[b:]
bad = []
for path, text in files.items():
    try:
        same = open(path).read() == text
    except FileNotFoundError:
        same = False
    if not same:
        if check:
            bad.append(path)
        else:
            open(path, "w").write(text)
if bad:
    sys.exit("gen-storylaw: not what the client generates now: " + ", ".join(bad) + "; run scripts/gen-storylaw.py --mini PATH")
print(f"gen-storylaw: {'checked' if check else 'wrote'} {len(files)} files ({len(out['clauses'])} clauses, "
      f"{len(out['edges'])} edges, {len(out['items'])} items)")
