#!/usr/bin/env python3
"""Kernel/Job.lean §2 is a mechanical embed of the job law JSON; this script is that embed.

usage (from the repository root):
  scripts/gen-joblaw.py           re-render law.job -> law.job.json and law.job.shell, then rewrite
                                  §2 from the JSON
  scripts/gen-joblaw.py --check   exit 1 if law.job.json or law.job.shell is not law.job's
                                  rendering, or §2 differs from what the JSON generates

Source: deploy/shell/templates/job/law.job (the grammar; clause numbers in its `-- N` comments),
rendered by deploy/shell/templates/mud/render.py to law.job.json (an `all` of clauses 0..N).
A value placeholder `{X}` becomes `p.X`; a slot that is a placeholder (`slot {RAN_SLOT}`) becomes
`p.RAN_SLOT`; negative literals are parenthesised; nothing is re-sorted, dropped or simplified.
law.job.shell is the same law in the shell's one-line grammar (native/resource-client/src/shell/law.rs),
each clause spelled exactly as the Host renders a refused clause (Compiler/RefusalReason.lean
`renderClause`), one clause per line; law.rs's `job_law_grammar_is_the_template_json` parses it back
to law.job.json.
Changing the law without re-running this script leaves the theorems about a different law."""
import json, os, re, subprocess, sys, tempfile

T = "deploy/shell/templates/job"
F = "Kernel/Job.lean"
PH = re.compile(r"\{([A-Z_0-9]+)\}")

def val(v):
    v = str(v)
    m = PH.fullmatch(v)
    if m:
        return "p." + m.group(1)
    n = int(v)
    return f"({n})" if n < 0 else str(n)

def slot(s):
    m = PH.fullmatch(s)
    if m:
        return "p." + m.group(1)
    if PH.search(s):
        sys.exit(f"gen-joblaw: a placeholder inside a slot name is not embedded: {s!r}")
    return '"' + s + '"'

def render(n, ind):
    t = n["type"]
    if t in ("all", "any"):
        kids = [" " * (ind + 2) + render(c, ind + 2) for c in n["predicates"]]
        return f"Pred.{t} [\n" + ",\n".join(kids) + "]"
    if t == "not":
        return f".not ({render(n['predicate'], ind + 2)})"
    if t in ("eq", "le"):
        return f".{t} {slot(n['slot'])} {val(n['value'])}"
    if t == "memberOf":
        return f".memberOf {slot(n['slot'])} [" + ", ".join(val(v) for v in n["values"]) + "]"
    if t in ("monotone", "writeOnce"):
        return f".{t} {slot(n['slot'])}"
    if t in ("eqSlots", "leSlots"):
        return f".{t} {slot(n['left'])} {slot(n['right'])}"
    if t == "leSlotsOff":
        return f".leSlotsOff {slot(n['left'])} {slot(n['right'])} {val(n['offset'])}"
    sys.exit(f"gen-joblaw: no Lean rendering for atom type {t!r}")

VERBS = {1: "read", 2: "write", 3: "delegate", 4: "install", 5: "revoke"}

def sh_slot(x):
    p = x.split("/")
    if len(p) == 4 and p[:2] == ["resource", "field"]:
        return f"field {p[2]}" if p[3] == "after" else f"field {p[2]} {p[3]}"
    if len(p) == 5 and p[:2] == ["resource", "pair"] and p[4] == "delta":
        return f"pair {p[2]},{p[3]} delta"
    if x in ("request/subject", "request/verb", "request/cost"):
        return p[1]
    return '"'.join(["slot ", x, ""])

def sh_val(slot, v):
    if slot == "request/verb" and not PH.fullmatch(v) and int(v) in VERBS:
        return VERBS[int(v)]
    return v

def shell(n):
    t = n["type"]
    if t in ("all", "any"):
        if not n["predicates"]:
            return "open" if t == "all" else "sealed"
        return f"{t} [ " + ", ".join(shell(c) for c in n["predicates"]) + " ]"
    if t == "not":
        return f"not ({shell(n['predicate'])})"
    if t == "eq":
        return f"{sh_slot(n['slot'])} == {sh_val(n['slot'], n['value'])}"
    if t == "le":
        return f"{sh_slot(n['slot'])} <= {sh_val(n['slot'], n['value'])}"
    if t == "memberOf":
        return f"{sh_slot(n['slot'])} in {{" + ",".join(sh_val(n['slot'], v) for v in n["values"]) + "}"
    if t in ("monotone", "writeOnce"):
        return f"{sh_slot(n['slot'])} {t}"
    if t == "eqSlots":
        return f"{sh_slot(n['left'])} == {sh_slot(n['right'])}"
    if t == "leSlots":
        return f"{sh_slot(n['left'])} <= {sh_slot(n['right'])}"
    if t == "leSlotsOff":
        return f"{sh_slot(n['left'])} <= {sh_slot(n['right'])} + {n['offset']}"
    sys.exit(f"gen-joblaw: no shell rendering for atom type {t!r}")

def shell_law(law):
    head = ("-- generated by scripts/gen-joblaw.py from law.job.json: the job law in the shell grammar,\n"
            "-- each clause as the Host renders it in a refusal. Bind the {UPPER} placeholders, then\n"
            "-- `law NAME J \"$(grep -v '^--' law.job.shell)\"`.\n")
    return head + ";\n".join(shell(c) for c in law["predicates"]) + "\n"

def rendered_json():
    with tempfile.TemporaryDirectory() as d:
        for f in ("fields.json", "law.job"):
            open(os.path.join(d, f), "w").write(open(os.path.join(T, f)).read())
        subprocess.run([sys.executable, "deploy/shell/templates/mud/render.py", d, "law.job"],
                       check=True, stdout=subprocess.DEVNULL)
        return open(os.path.join(d, "law.job.json")).read()

def generate(law):
    if law["type"] != "all":
        sys.exit("gen-joblaw: law.job.json is not an `all` of clauses")
    out = []
    for i, c in enumerate(law["predicates"]):
        out += [f"/-- clause {i} -/", f"def jobClause{i} (p : Params) : Pred :=", "  " + render(c, 2), ""]
    n = len(law["predicates"])
    out += ["/-- The clauses in the installed order. -/", "def jobClauses (p : Params) : List Pred :=",
            "  [" + ", ".join(f"jobClause{i} p" for i in range(n)) + "]", ""]
    return "\n".join(out) + "\n", n

check = "--check" in sys.argv[1:]
js = rendered_json()
if check:
    if open(f"{T}/law.job.json").read() != js:
        sys.exit(f"gen-joblaw: {T}/law.job.json is not the rendering of {T}/law.job; run scripts/gen-joblaw.py")
else:
    open(f"{T}/law.job.json", "w").write(js)
sh = shell_law(json.loads(js))
if check:
    if not os.path.exists(f"{T}/law.job.shell") or open(f"{T}/law.job.shell").read() != sh:
        sys.exit(f"gen-joblaw: {T}/law.job.shell is not the shell rendering of law.job.json; run scripts/gen-joblaw.py")
else:
    open(f"{T}/law.job.shell", "w").write(sh)
gen, n = generate(json.loads(js))
s = open(F).read()
a, b = s.index("/-- clause 0 -/"), s.index("end Law")
if check:
    if s[a:b] != gen:
        sys.exit(f"gen-joblaw: {F} §2 is not the embed of {T}/law.job.json; run scripts/gen-joblaw.py")
    print(f"gen-joblaw: law.job.json is law.job's rendering and {F} §2 matches it ({n} clauses)")
else:
    open(F, "w").write(s[:a] + gen + s[b:])
    print(f"gen-joblaw: wrote {T}/law.job.json and {F} §2 ({n} clauses)")
