#!/usr/bin/env bash
# Render the source-owned Poseidon2 primitive data as a deterministic Lean
# module.  The repository trust gate diffs this output against the committed
# consumer file, so its tables cannot drift from the admitted JSON payload.
set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd -P)
repo_root=$(cd "$script_dir/.." && pwd -P)
stem=dregg-ir2-babybear-poseidon2-w16-fri-v1
payload=$repo_root/artifacts/zkml-suites/$stem.payload.json
envelope=$repo_root/artifacts/zkml-suites/$stem.envelope.json

line() {
  printf '%s\n' "$1"
}

json_string() {
  jq -er "$1 | @json" "$2"
}

json_compact() {
  jq -ec "$1" "$payload"
}

suite_id=$(json_string '.suite_id' "$payload")
payload_sha=$(json_string '.payload.sha256' "$envelope")
source_commit=$(json_string '.source.commit' "$envelope")
source_tree=$(json_string '.source.tree' "$envelope")

line '/- This file is generated by scripts/render-zkml-poseidon2-data.sh.'
line '   Its exact source payload and producer identity are enforced by'
line '   scripts/check-zkml-suite-artifact.sh.  Do not edit it by hand. -/'
line ''
line 'namespace Minidregg.Selvage.ZkmlPoseidon2Data'
line ''
line 'set_option autoImplicit false'
line ''
line "def sourceSuiteId : String := $suite_id"
line "def sourcePayloadSha256 : String := $payload_sha"
line "def sourceCommit : String := $source_commit"
line "def sourceTree : String := $source_tree"
line ''
printf 'def externalInitialConstants : List (List Nat) := '
json_compact '.external_initial_constants'
printf 'def internalConstants : List Nat := '
json_compact '.internal_constants'
printf 'def externalFinalConstants : List (List Nat) := '
json_compact '.external_final_constants'
printf 'def externalLinearColumns : List (List Nat) := '
json_compact '.external_linear_columns'
printf 'def internalLinearColumns : List (List Nat) := '
json_compact '.internal_linear_columns'
line ''
line '/-- The admitted payload has the exact deployed round/table dimensions. -/'
line 'theorem sourceData_shapes :'
line '    externalInitialConstants.length = 4 ∧'
line '    (∀ row ∈ externalInitialConstants, row.length = 16) ∧'
line '    internalConstants.length = 13 ∧'
line '    externalFinalConstants.length = 4 ∧'
line '    (∀ row ∈ externalFinalConstants, row.length = 16) ∧'
line '    externalLinearColumns.length = 16 ∧'
line '    (∀ column ∈ externalLinearColumns, column.length = 16) ∧'
line '    internalLinearColumns.length = 16 ∧'
line '    (∀ column ∈ internalLinearColumns, column.length = 16) := by'
line '  decide'
line ''
line 'end Minidregg.Selvage.ZkmlPoseidon2Data'
