//! Minimal worker-visible Hermes profile for the controller's local gateway.
//! The provider's BYO key never enters this file; its API key is a single
//! prompt lease token, rotated before each worker launch.
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::net::SocketAddr;
use std::os::unix::fs::{MetadataExt, OpenOptionsExt, PermissionsExt};
use std::path::Path;

const MARKER: &str = "# mini-grain-generated-provider-v1\n";

pub fn private_key(path: &Path, state_dir: &Path) -> Result<String, String> {
    if path.parent() != Some(state_dir) {
        return Err("provider key must be directly inside private controller state".into());
    }
    let meta = fs::symlink_metadata(path).map_err(|e| format!("provider key metadata: {e}"))?;
    if !meta.file_type().is_file()
        || meta.file_type().is_symlink()
        || meta.uid() != unsafe { libc::geteuid() }
        || meta.permissions().mode() & 0o077 != 0
        || meta.len() == 0
        || meta.len() > 4097
    {
        return Err("provider key must be an owned private regular file under 4097 bytes".into());
    }
    let value = fs::read_to_string(path).map_err(|e| format!("provider key read: {e}"))?;
    let value = value.strip_suffix('\n').unwrap_or(&value);
    if value.is_empty()
        || value.len() > 4096
        || value.bytes().any(|byte| !(0x21..=0x7e).contains(&byte))
    {
        return Err("provider key has unsupported encoding".into());
    }
    Ok(value.to_owned())
}

pub fn random_token() -> Result<String, String> {
    let mut bytes = [0u8; 32];
    File::open("/dev/urandom")
        .and_then(|mut file| file.read_exact(&mut bytes))
        .map_err(|e| format!("provider token entropy: {e}"))?;
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut token = String::with_capacity(64);
    for byte in bytes {
        token.push(HEX[(byte >> 4) as usize] as char);
        token.push(HEX[(byte & 0xf) as usize] as char);
    }
    Ok(token)
}

/// The fixed scoped bwrap workspace is mounted at `/workspace`; upstream
/// Hermes reads `/workspace/.hermes/config.yaml` through HERMES_HOME.
pub fn install_worker_profile(
    home: &Path,
    model: &str,
    gateway: SocketAddr,
    token: &str,
    mcp_timeout_seconds: u64,
) -> Result<(), String> {
    if model.is_empty()
        || model.len() > 256
        || !model
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"._-/".contains(&byte))
        || token.len() != 64
        || !token.bytes().all(|byte| byte.is_ascii_hexdigit())
        || !gateway.ip().is_loopback()
        || gateway.port() == 0
        || !(1..=1740).contains(&mcp_timeout_seconds)
    {
        return Err("provider profile route, model, or token invalid".into());
    }
    let home_meta = fs::symlink_metadata(home).map_err(|e| format!("Hermes home metadata: {e}"))?;
    if !home_meta.file_type().is_dir()
        || home_meta.file_type().is_symlink()
        || home_meta.uid() != unsafe { libc::geteuid() }
        || home_meta.permissions().mode() & 0o077 != 0
    {
        return Err("Hermes home must be owned private real directory".into());
    }
    let config = home.join("config.yaml");
    match fs::symlink_metadata(&config) {
        Ok(meta) => {
            if !meta.file_type().is_file()
                || meta.file_type().is_symlink()
                || meta.uid() != unsafe { libc::geteuid() }
                || meta.permissions().mode() & 0o077 != 0
                || meta.len() > 16_384
            {
                return Err("existing Hermes config is not an owned generated file".into());
            }
            let old = fs::read_to_string(&config).map_err(|e| e.to_string())?;
            if !old.starts_with(MARKER) {
                return Err("existing Hermes config was not generated by Mini".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(format!("Hermes config metadata: {error}")),
    }
    let text = format!(
        "{MARKER}model:\n  provider: custom\n  default: {model}\n  context_length: 65536\n  base_url: http://{gateway}/v1\n  api_key: {token}\n  api_mode: chat_completions\nmcp_servers: {{}}\ntimeouts:\n  mcp:\n    tool_call: {mcp_timeout_seconds}\nmemory:\n  memory_enabled: false\n  user_profile_enabled: false\nagent:\n  max_iterations: 6\ntools:\n  tool_search:\n    enabled: false\n"
    );
    let tmp = home.join(".config.yaml.tmp");
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&tmp)
        .map_err(|e| format!("Hermes profile temp: {e}"))?;
    file.write_all(text.as_bytes())
        .and_then(|_| file.sync_all())
        .map_err(|e| format!("Hermes profile sync: {e}"))?;
    fs::rename(&tmp, &config).map_err(|e| format!("Hermes profile replace: {e}"))?;
    File::open(home)
        .and_then(|directory| directory.sync_all())
        .map_err(|e| format!("Hermes profile directory sync: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_holds_gateway_token_and_never_provider_key() {
        let home =
            std::env::temp_dir().join(format!("grain-provider-profile-{}", std::process::id()));
        fs::create_dir(&home).unwrap();
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700)).unwrap();
        let token = "a".repeat(64);
        install_worker_profile(
            &home,
            "test-model",
            "127.0.0.1:18761".parse().unwrap(),
            &token,
            540,
        )
        .unwrap();
        let text = fs::read_to_string(home.join("config.yaml")).unwrap();
        assert!(text.contains("base_url: http://127.0.0.1:18761/v1"));
        assert!(text.contains(&format!("api_key: {token}")));
        assert!(text.contains("tool_call: 540"));
        assert!(!text.contains("BYO_PROVIDER_KEY"));
        assert!(install_worker_profile(
            &home,
            "bad:yaml",
            "127.0.0.1:18761".parse().unwrap(),
            &token,
            540
        )
        .is_err());
        fs::remove_dir_all(home).unwrap();
    }
}
