//! Minimal worker-visible Hermes profile for the controller's local gateway.
//! The provider's BYO key never enters this file; its API key is a single
//! prompt lease token, rotated before each worker launch.
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::net::SocketAddr;
use std::os::unix::fs::{MetadataExt, OpenOptionsExt, PermissionsExt};
use std::path::Path;

/// Read the same private config.yaml that a scoped worker sees at
/// /workspace/.hermes. Hermes resolves MCP timeouts from this nested key;
/// ACP-provided MCP server parameters do not carry a timeout through its
/// adapter. Refuse a too-short configured value before reserving Mini budget.
pub fn require_worker_mcp_timeout(home: &Path, worker_wall_seconds: u64) -> Result<(), String> {
    if !(1..=1800).contains(&worker_wall_seconds) {
        return Err("worker wall lifetime is outside the scoped profile".into());
    }
    let path = home.join("config.yaml");
    let meta =
        fs::symlink_metadata(&path).map_err(|e| format!("Hermes config for MCP timeout: {e}"))?;
    if !meta.file_type().is_file()
        || meta.file_type().is_symlink()
        || meta.uid() != unsafe { libc::geteuid() }
        || meta.permissions().mode() & 0o077 != 0
        || meta.len() == 0
        || meta.len() > 16_384
    {
        return Err("Hermes config must be an owned private regular file under 16 KiB".into());
    }
    let bytes = fs::read(&path).map_err(|e| format!("Hermes config read: {e}"))?;
    let value: serde_yaml::Value =
        serde_yaml::from_slice(&bytes).map_err(|e| format!("Hermes config YAML: {e}"))?;
    let timeout = value
        .get("timeouts")
        .and_then(|timeouts| timeouts.get("mcp"))
        .and_then(|mcp| mcp.get("tool_call"))
        .and_then(|number| match number {
            serde_yaml::Value::Number(number) => number.as_f64(),
            serde_yaml::Value::String(text) => text.parse::<f64>().ok(),
            _ => None,
        })
        .ok_or("Hermes config needs timeouts.mcp.tool_call in seconds")?;
    let required = worker_wall_seconds.saturating_sub(60).max(1);
    if !timeout.is_finite() || timeout < required as f64 {
        return Err(format!(
            "Hermes config timeouts.mcp.tool_call must be finite and at least {required}s for this worker lifetime; actual {timeout}s"
        ));
    }
    Ok(())
}

const MARKER: &str = "# mini-grain-generated-provider-v1\n";

pub fn random_token() -> Result<String, String> {
    let mut bytes = [0u8; 32];
    File::open("/dev/urandom")
        .and_then(|mut file| file.read_exact(&mut bytes))
        .map_err(|e| format!("provider token entropy: {e}"))?;
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut token = String::with_capacity(64);
    for byte in bytes {
        token.push(HEX[(byte >> 4) as usize] as char);
        token.push(HEX[(byte & 0xf) as usize] as char);
    }
    Ok(token)
}

/// The fixed scoped bwrap workspace is mounted at `/workspace`; upstream
/// Hermes reads `/workspace/.hermes/config.yaml` through HERMES_HOME.
pub fn install_worker_profile(
    home: &Path,
    model: &str,
    gateway: SocketAddr,
    token: &str,
    mcp_timeout_seconds: u64,
    max_iterations: u8,
    max_input_tokens: Option<u32>,
) -> Result<(), String> {
    if model.is_empty()
        || model.len() > 256
        || !model
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"._-/".contains(&byte))
        || token.len() != 64
        || !token.bytes().all(|byte| byte.is_ascii_hexdigit())
        || !gateway.ip().is_loopback()
        || gateway.port() == 0
        || !(1..=1740).contains(&mcp_timeout_seconds)
        || !(1..=6).contains(&max_iterations)
        || max_input_tokens.is_some_and(|tokens| !(1..=131_072).contains(&tokens))
    {
        return Err("provider profile route, model, or token invalid".into());
    }
    let home_meta = fs::symlink_metadata(home).map_err(|e| format!("Hermes home metadata: {e}"))?;
    if !home_meta.file_type().is_dir()
        || home_meta.file_type().is_symlink()
        || home_meta.uid() != unsafe { libc::geteuid() }
        || home_meta.permissions().mode() & 0o077 != 0
    {
        return Err("Hermes home must be owned private real directory".into());
    }
    let config = home.join("config.yaml");
    match fs::symlink_metadata(&config) {
        Ok(meta) => {
            if !meta.file_type().is_file()
                || meta.file_type().is_symlink()
                || meta.uid() != unsafe { libc::geteuid() }
                || meta.permissions().mode() & 0o077 != 0
                || meta.len() > 16_384
            {
                return Err("existing Hermes config is not an owned generated file".into());
            }
            let old = fs::read_to_string(&config).map_err(|e| e.to_string())?;
            if !old.starts_with(MARKER) {
                return Err("existing Hermes config was not generated by Mini".into());
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(format!("Hermes config metadata: {error}")),
    }
    let context_length = max_input_tokens.unwrap_or(65_536);
    let text = format!(
        "{MARKER}model:\n  provider: custom\n  default: {model}\n  context_length: {context_length}\n  base_url: http://{gateway}/v1\n  api_key: {token}\n  api_mode: chat_completions\nmcp_servers: {{}}\ntimeouts:\n  mcp:\n    tool_call: {mcp_timeout_seconds}\nmemory:\n  memory_enabled: false\n  user_profile_enabled: false\nauxiliary:\n  title_generation:\n    enabled: false\nagent:\n  max_iterations: {max_iterations}\ntools:\n  tool_search:\n    enabled: false\n"
    );
    let tmp = home.join(".config.yaml.tmp");
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&tmp)
        .map_err(|e| format!("Hermes profile temp: {e}"))?;
    file.write_all(text.as_bytes())
        .and_then(|_| file.sync_all())
        .map_err(|e| format!("Hermes profile sync: {e}"))?;
    fs::rename(&tmp, &config).map_err(|e| format!("Hermes profile replace: {e}"))?;
    File::open(home)
        .and_then(|directory| directory.sync_all())
        .map_err(|e| format!("Hermes profile directory sync: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn profile_holds_gateway_token_and_never_provider_key() {
        let home =
            std::env::temp_dir().join(format!("grain-provider-profile-{}", std::process::id()));
        fs::create_dir(&home).unwrap();
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700)).unwrap();
        let token = "a".repeat(64);
        install_worker_profile(
            &home,
            "test-model",
            "127.0.0.1:18761".parse().unwrap(),
            &token,
            540,
            2,
            Some(8192),
        )
        .unwrap();
        let text = fs::read_to_string(home.join("config.yaml")).unwrap();
        assert!(text.contains("base_url: http://127.0.0.1:18761/v1"));
        assert!(text.contains(&format!("api_key: {token}")));
        assert!(text.contains("tool_call: 540"));
        assert!(text.contains("max_iterations: 2"));
        assert!(text.contains("context_length: 8192"));
        assert!(text.contains("auxiliary:\n  title_generation:\n    enabled: false"));
        assert!(!text.contains("BYO_PROVIDER_KEY"));
        require_worker_mcp_timeout(&home, 600).unwrap();
        assert!(install_worker_profile(
            &home,
            "bad:yaml",
            "127.0.0.1:18761".parse().unwrap(),
            &token,
            540,
            2,
            None,
        )
        .is_err());
        fs::remove_dir_all(home).unwrap();
    }

    #[test]
    fn profile_rejects_iterations_outside_bounded_range_before_writing() {
        let home =
            std::env::temp_dir().join(format!("grain-provider-iterations-{}", std::process::id()));
        fs::create_dir(&home).unwrap();
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700)).unwrap();
        let token = "a".repeat(64);
        for invalid in [0, 7, u8::MAX] {
            assert!(install_worker_profile(
                &home,
                "test-model",
                "127.0.0.1:18761".parse().unwrap(),
                &token,
                540,
                invalid,
                None,
            )
            .is_err());
            assert!(!home.join("config.yaml").exists());
        }
        fs::remove_dir_all(home).unwrap();
    }

    #[test]
    fn profile_rejects_invalid_context_ceiling_before_writing() {
        let home = std::env::temp_dir().join(format!(
            "grain-provider-context-ceiling-{}",
            std::process::id()
        ));
        fs::create_dir(&home).unwrap();
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700)).unwrap();
        let token = "a".repeat(64);
        for invalid in [0, 131_073] {
            assert!(install_worker_profile(
                &home,
                "test-model",
                "127.0.0.1:18761".parse().unwrap(),
                &token,
                540,
                2,
                Some(invalid),
            )
            .is_err());
            assert!(!home.join("config.yaml").exists());
        }
        fs::remove_dir_all(home).unwrap();
    }

    #[test]
    fn scoped_worker_refuses_upstream_mcp_default_before_reserve() {
        let home =
            std::env::temp_dir().join(format!("grain-worker-mcp-timeout-{}", std::process::id()));
        fs::create_dir(&home).unwrap();
        fs::set_permissions(&home, fs::Permissions::from_mode(0o700)).unwrap();
        let config = home.join("config.yaml");
        fs::write(&config, "model:\n  provider: custom\n").unwrap();
        fs::set_permissions(&config, fs::Permissions::from_mode(0o600)).unwrap();
        assert!(require_worker_mcp_timeout(&home, 1500).is_err());
        fs::write(&config, "timeouts:\n  mcp:\n    tool_call: 300\n").unwrap();
        assert!(require_worker_mcp_timeout(&home, 1500).is_err());
        fs::write(&config, "timeouts:\n  mcp:\n    tool_call: 1440\n").unwrap();
        require_worker_mcp_timeout(&home, 1500).unwrap();
        fs::remove_dir_all(home).unwrap();
    }
}
